### ISSUE TITLE
New term request for Coignard PMID 33597508

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1010]
For new term requests, please provide the following information:

## Preferred term label

BRCA1 carrier status

## Textual definition

Quantification of the presence or absence of a known harmful mutation in the BRCA1 gene.

## Suggested parent term

carrier status

**Comment by kallia-p** [comment]
@zoependlington @earlEBI @dosumis 
Looking at carrier status and some of its children (i.e. APOL1 risk genotype carrier status, GBA carrier status, and this ticket BRAC1/BRAC2 carrier status) I thought that we could improve the definition by using 'determination instead of quantification' because a genotype is determined and not quantified. So for this ticket I suggest the textual definition 'Determination of the presence or absence of known harmful mutation(s) in the BRAC1 gene'.  I could apply the same fix to the 3 other gene carrier status terms that are in EFO but I wanted to double-check whether any changes in the definition of a term would affect the GWAS catalogue so maybe Liz could feedback on this?

**Comment by kallia-p** [comment]
Added new term EFO:0011021 'BRAC1 mutation carrier status' under parent term 'carrier status'

rdfs:label 'BRAC1 mutation carrier status'

definition "Determination of the presence or absence of known harmful mutation(s) in the BRAC1 gene. BRCA1/BRCA2 genes play a central role in DNA repair and their mutations increase sensitivity to DNA-damaging agents. BRCA1/BRCA2 germline mutations significantly increase the risk of breast and ovarian cancer."
definition_citation doi:10.1001/jama.2017.7112

alternative_term "BRAC1 carrier status"

alternative_term "BRAC1 mutation status"

database_cross_reference "PMID:33597508"

gwas_trait true

'term editor' "Elizabeth Lewis"

Added Subclass of is_about some ‘breast cancer’

Added Subclass of is_about some ‘ovarian cancer’
