### ISSUE TITLE
Adding a part_of relationship from EFO:0010183 to EFO:0007832?

### ISSUE THREAD

**Issue by LTLA** [EBISPOT/efo#1027]
Should EFO:0010183 (single cell library construction) have a `part_of` relationship to EFO:0007832 (single cell sequencing)?

Despite its name, the latter term is a child of `assay`, which indicated to me that it represented the entire process of a single-cell sequencing experiment, rather than just literally the sequencing step. If so, a `part_of` relationship would be appropriate here, given that any single-cell sequencing experiment must have involved library construction at some point. 

(From a consumer's perspective, some kind of relationship between these terms would be helpful to connect the relevant parts of the ontology graph. I am building an ontology-aware search application and the lack of connectivity means that searches for EFO:0007832 will not pick up any entries annotated with EFO:0010183 or its children, which is unfortunate.)

I could supply more fine-grained relationships between specific protocols in EFO:0010183 and the full-length/tag child terms of EFO:0007832, but I'm not sure whether "full-length" in this context means "coverage of the entire transcript" or "full-length reads" (a la Nanopore or PacBio). I'm also not sure whether "tag" is equivalent to UMI in this context.

On a similar note, EFO:0008439 could be considered `part_of` EFO:0007832. This touches on some points in #887.

Apologies for not following the format of the term request ticket, the section headers weren't appropriate here.

**Comment by paolaroncaglia** [comment]
Hi @LTLA ,

Thanks for your feedback on EFO. It's great to know that you're using EFO to build ontology-aware apps. No problem about the format of the term request ticket, we're aware that the template will not apply to all cases.

As you already noticed, we're planning some work on sequencing-related terms in EFO. It may not all happen in time for the next EFO release, but it's useful to be collecting ideas/issues. So today I'll focus on the first part of your comments and leave the more fine-grained considerations for later.  
What you say is correct: any single-cell sequencing experiment must have involved library construction at some point. However, the correct ontology relationship to represent that statement would be that 'single-cell sequencing experiment' _has_part_ 'single cell library construction'. The statement 'single cell library construction' part_of 'single-cell sequencing experiment' implies that the former is always and necessarily part of the latter, and that it wouldn't exist at all without it. In principle, a single cell library could be produced to be used in an application that doesn't involve sequencing, or it could even not be used at all (I agree that it would make little sense, but it wouldn't _need_ a sequencing experiment in order to be built). You'd need to "embed" the has_part relationship in your app so that it's displayed meaningfully for your consumers. But as I said, we're planning to improve EFO branches pertaining to single cell technology, so I'd be interested in your feedback here. Other relationships may also be used such as is_about, but that's a more fine-grained discussion.     

The statement "any single-cell sequencing experiment must have involved a single cell nucleic acid sequencing protocol at some point" is trickier to represent. But you'll agree that a protocol can exist independently of an experiment, and in this case more than in the previous one, the most appropriate relationship between the two might be something along the lines of is_about. This is all great food for thought.

Thanks,
Paola

**Comment by LTLA** [comment]
> But as I said, we're planning to improve EFO branches pertaining to single cell technology, so I'd be interested in your feedback here.

Sure. I'm definitely not an ontology expert, and `has_part` sounds pretty good to me as well. So long as I have some kind of directional relationship in the ontology graph, my search app will be able to do something reasonably sensible.

(On another note, I do have some general feedback on the single-cell terms, probably increasing over the next quarter as I try to gauge how to incorporate them into my application. Would you want me to make a separate issue for each point, or perhaps gather them all into one giant issue, or use some other communication channel altogether?)

> the most appropriate relationship between the two might be something along the lines of is_about

I was trying to figure out was `is_about` means, but Google wasn't offering much. A `has_part` here also seems okay to me.

**Comment by paolaroncaglia** [comment]
Hi @LTLA ,

> Sure. I'm definitely not an ontology expert, and `has_part` sounds pretty good to me as well. So long as I have some kind of directional relationship in the ontology graph, my search app will be able to do something reasonably sensible.

Note for self:
- [ ] Look into adding has_part links (or other appropriate ones) as discussed in this ticket

> (On another note, I do have some general feedback on the single-cell terms, probably increasing over the next quarter as I try to gauge how to incorporate them into my application. Would you want me to make a separate issue for each point, or perhaps gather them all into one giant issue, or use some other communication channel altogether?)

Opening tickets in this tracker is the preferred method please. And if you think you'll have multiple requests over a period of time, making separate issues would be better please. Feel free to cross-reference other tickets, that's also helpful.

Thanks,
Paola

**Comment by LTLA** [comment]
Bumping this issue. I just ran into this again where some datasets were annotated with various children of EFO:0010183 (e.g., MARS-seq, CEL-seq2). Most of these terms are various flavors of single-cell RNA-seq, so my users were searching on EFO:0008913 and were expecting to find their datasets. AFAICT there is still no relationship between "single cell library construction" and "single-cell RNA sequencing", so this query was not behaving as expected.

**Comment by paolaroncaglia** [comment]
@zoependlington @dosumis may I please your feedback on this issue? I've come across it before, but I'm not sure on the best course of action. I recall that editing the 'single cell library construction' branch is somewhat constrained by how it's used by e.g. the Expression Atlas at EBI. OTOH I fully agree that a query on single-cell RNA sequencing terms should be able to retrieve some subclasses as expected. My initial suggestion was to make 
'single cell sequencing' has_part 'single cell library construction'
@LTLA would then need to represent/embed the has_part relationship in his tool so that it's displayed meaningfully for his users.
Would you agree with adding that link? Or would you have better suggestions? Ideally I'm looking for a solution that I can implement in time for the next EFO release. An alternative would be to add the superclass 'single-cell RNA sequencing' to any child of 'single cell library construction' that mentions RNA and sequencing. Thanks.

**Comment by paolaroncaglia** [comment]
Hi @LTLA ,

I discussed your request with some of my colleagues offline. In short, we couldn't resolve it straight away, but my colleagues will address it at a meeting scheduled for June 8th.
In a little more detail, our main concerns are that a) the has_part solution is reasonable, but may not address your users' needs or expectations, as it may be the reverse direction that you'd need for grouping; b) significant changes in the single cell sequencing and library EFO terms may affect pipelines of other, internal tools, so the issue needs to be discussed further. We're keen to do that, because it will ultimately benefit the whole ontology. So we've already added this ticket for discussion at that meeting next month.
Please feel free to follow up in June for updates. I will now hand over this ticket to other colleagues, because I'm moving to a different project in a couple of weeks. Thank you for your valuable input, and best wishes!

**Comment by paolaroncaglia** [comment]
@bvarner-ebi @zoependlington handing over to you. Thank you!

**Comment by paolaroncaglia** [comment]
@anjaf @ngeorgeebi @sfexova
As discussed at the single-cell curators call 2 days ago, @dosumis suggested to devote next month's meeting to discuss this issue and the broader context of library and assay terms in EFO. (Anja, you should have received an invite or mention, if not please let us know: all details are in the meeting agenda for June 8th.) It'd be great if you could please start looking into the discussion items in advance of the meeting. Many thanks in advance. Handing over to Bradley and Zoë now - my last day on this EBI project will be May 31st.

**Comment by bvarner-ebi** [comment]
>Should EFO:0010183 (single cell library construction) have a part_of relationship to EFO:0007832 (single cell sequencing)?

@anjaf, do you have concerns with this edit? Would it negatively impact your tools? Please add thoughts here and/or join the "CL for scRNAseq" meeting this Wednesday.

**Comment by anjaf** [comment]
This change won't impact us. You can go ahead with it. (I will try to come to the meeting on Wednesday but I have a clash, so l might join late.)

**Comment by LTLA** [comment]
Thanks @bvarner-ebi, this is a good start. Could the same approach be applied to some of the more specific terms? This is because "single cell RNA sequencing" is a much more common search than its parent "single cell sequencing".

For example:

- One could create a "single cell transcriptome library construction" that is a subclass of "single cell library construction". The appropriate technologies (e.g., MARS-seq, CEL-seq) become subclasses of this hypothetical new term.
- Then, "single cell RNA sequencing" (EFO:0008913) could `has_part` the new transcriptome library term.
- This would allow me to search on "scRNA-seq" (synonym of EFO:0008913) and pick up all of the associated technologies.

**Comment by bvarner-ebi** [comment]
Hi, @LTLA,

Thank you for the feedback. If you would like to add a new term, would you mind creating a "new term request" ticket?

WIth the present change, EFO:0008913 'single-cell RNA sequencing' will also have the relationship **'has part' some 'single cell library construction'** since 'single-cell RNA sequencing' is a subclass of 'single cell sequencing'.
