### ISSUE TITLE
New term request for Kim SK PMID 33017352

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1030]
For new term requests, please provide the following information:

## Preferred term label

concussion

## Textual definition

A traumatic brain injury resulting from traumatic forces. 

## Suggested parent term

Head injury

##NCIT term: https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C50502

**Comment by kallia-p** [comment]
@zoependlington 
I added new term 'concussion' (EFO:0011023)
Subclass Of head injury 
Subclass Of brain injury 

\rdfs:label "concussion"@en
\definition "A concussion, also known as a mild traumatic brain injury (mTBI), is a head injury that temporarily affects brain functioning. It is usually caused by a bump, blow or jolt to the head."
\definition_citation https://en.wikipedia.org/wiki/Concussion
\alternative_term "mild TBI"
\alternative_term "mild traumatic brain injury"
\alternative_term "mTBI"
\gwas_trait true
\'term editor' "Elizabeth Langley"

 @dosumis 'injury' is another branch in EFO whose children (i.e. head injury, nervous system injury, brain injury) lack Equivalent Class Axioms i.e. head injury could be Equivalent To injury and (is_about some head). Worth creating a ticket for this?
