### ISSUE TITLE
Vitamin deficiency subtypes

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#106]
For new term requests, please provide the following information:

## Preferred term label

Thiamine deficiency
Vitamin B3 deficiency

### Vitamin B3 deficiency
vitamin B3 niacin deficiency
niacin (vitamin B3) deficiency
Niacin Deficiency
Pellagra

## Suggested parent term

Vitamin deficiency

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
- [ ]  Create new term:
EFO:NEW1 Thiamine deficiency
Subclass of vitamin deficiency (EFO:0005878)
Def: Thiamine deficiency is a condition that occurs due to not enough thiamine (vitamin B1).
X-refs: https://en.wikipedia.org/wiki/Thiamine_deficiency
Synonyms: 

- [ ]  Create new term:
EFO:NEW2 Vitamin B3 deficiency
Subclass of vitamin deficiency (EFO:0005878)
Def: Vitamin B3 deficiency is a condition that occurs due to not enough niacin (vitamin B3).
Synonyms: vitamin B3 niacin deficiency
niacin (vitamin B3) deficiency
Niacin Deficiency
Pellagra

**Comment by paolaroncaglia** [comment]
The IDs for the new terms that Zoe created are:
Thiamine deficiency EFO:0008569
Vitamin B3 deficiency EFO:0008570
Thanks Zoe.
