### ISSUE TITLE
New term request for Tang PMID 33134509

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1071]
For new term requests, please provide the following information:

## Preferred term label

type I collagen metabolite measurement

## Synonyms

matrix metalloproteinase-degraded type I collagen

## Textual definition

Quantification of the metabolite of type I collagen in a sample

## Suggested parent term

metabolite measurement

**Comment by kallia-p** [comment]
@earlEBI Hi Liz, I am not sure about the use of the term metabolite measurement because it sounds to me that what is measured in this study is degraded Type I collagen which is a protein and I found a paper which seems to support this:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4534684/
Recently we developed an ELISA assay detecting MMP-mediated type I collagen degradation fragments in serum (termed C1M). The competitive ELISA measures the end product of tissue degradation, i.e. a pool of peptides/proteins all having this specific MMP-mediated binding site as the denominator. The monoclonal antibody recognizes a 6 amino acid sequence at position 764 in the C-terminus of type 1 collagen (Leeming et al., 2011b).
So I am thinking that protein measurement might be more appropriate than metabolite measurement as a parent term. Could you let me know why do you think it's a metabolite?

**Comment by kallia-p** [comment]
@earlEBI I mean I can see references in the literature that point to Metabolites of type I, II, III, and IV collagen but I was under the impression that the term metabolite is usually for small molecules.

**Comment by earlEBI** [comment]
@kallia-p Hi Kallia, it was more because the paper refers to metabolite throughout, i.e. the header of Figure 1.

**Comment by kallia-p** [comment]
I think it can be classified under both blood protein measurement and metabolite measurement

**Comment by kallia-p** [comment]
@earlEBI @zoependlington New term added in protege 'matrix metalloproteinase–degraded type I collagen measurement' EFO:0011036 under parent term  'blood protein measurement'
Definition "Quantification of matrix metalloproteinase-degraded type I collagen (also known as metabolite of type I collagen) in a sample.")
alternative_term "Matrix metalloproteinase (MMP)-degraded type I collagen (C1M) measurement"
alternative_term "MMP-mediated type I collagen degradation measurement"
alternative_term "type I collagen metabolite measurement"
database_cross_reference "PMID:33134509"
gwas_trait true
'term editor' "Elizabeth Lewis"

**Comment by earlEBI** [comment]
@kallia-p thank you
