### ISSUE TITLE
New assay term for spatial transcriptomics by sequencing

### ISSUE THREAD

**Issue by anjaf** [EBISPOT/efo#1093]
In order to use "spatial transcriptomics" in ArrayExpress as experiment type, we need to put it under the "assay by sequencer" http://www.ebi.ac.uk/efo/EFO_0003740 in EFO (this is where the MINSEQE scorer finds the terms).
Therefore, we are proposing to create the following term:

## Preferred term label

spatial transcriptomics by high throughput sequencing

## Textual definition

A spatial transcriptomics assay that measures spatially defined transcription by high-throughput sequencing

## Suggested parent term

"spatial transcriptomics" http://www.ebi.ac.uk/efo/EFO_0008994
"assay by high throughput sequencer" http://www.ebi.ac.uk/efo/EFO_0002697 

## Child terms

The term "Visium Spatial Gene Expression"  http://www.ebi.ac.uk/efo/EFO_0010961 currently under "spatial transcriptomics" http://www.ebi.ac.uk/efo/EFO_0008994 shall be moved from there to become a child of the new "spatial transcriptomics by high throughput sequencing" term.

**Comment by paolaroncaglia** [comment]
Note for self: the suggested move of 'Visium Spatial Gene Expression' (originally requested by HCA) under the new, more granular parent 'spatial transcriptomics by high throughput sequencing' should not affect the use of 'Visium Spatial Gene Expression' by HCA because it will still maintain its original ancestry to the broader 'assay' term. Its link to the '10x sequencing' branch will be discussed in #1091 .

**Comment by paolaroncaglia** [comment]
@anjaf 
The new term is EFO:0030005 'spatial transcriptomics by high-throughput sequencing'.
**Question**: 'Visium Spatial Gene Expression' is now a subclass of 'spatial transcriptomics by high-throughput sequencing' instead of 'spatial transcriptomics' as requested, but it's also a subclass of '10x technology' (was '10x sequencing'), because that parentage existed before and I didn't change it, as I couldn't find an explicit request to do so in this ticket or in #1091 , and I wasn't sure. Please let me know if that's not ok. Thanks.

**Comment by anjaf** [comment]
> **Question**: 'Visium Spatial Gene Expression' is now a subclass of 'spatial transcriptomics by high-throughput sequencing' instead of 'spatial transcriptomics' as requested, but it's also a subclass of '10x technology' (was '10x sequencing'), because that parentage existed before and I didn't change it, as I couldn't find an explicit request to do so in this ticket or in #1091 , and I wasn't sure. Please let me know if that's not ok. Otherwise, this ticket can be closed. Thanks.

Yes, this is fine. We can keep it under "10x technology".

**Comment by paolaroncaglia** [comment]
P.S. EFO:0030005 'spatial transcriptomics by high-throughput sequencing', and the new placement of 'Visium Spatial Gene Expression' under it, will be visible in the next EFO release, scheduled for Monday May 17th.
