### ISSUE TITLE
Acute kidney failure

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#110]
For new term requests, please provide the following information:

## Preferred term label

Acute kidney failure

## Synonyms

Acute Kidney Insufficiency
Acute Renal Failure
Acute Renal Injury
Acute Renal Insufficiency
Kidney Failure, Acute
Kidney Insufficiency, Acute
Renal Failure, Acute
Renal Insufficiency, Acute
Acute Kidney Injury
ARF
AKI

## X-refs

MESH D058186
NCIT_C26808
HP_0001919
ICD10 N17
UMLS_CUI C0022660

## Textual definition

Sudden and sustained deterioration of the kidney function characterized by decreased glomerular filtration rate, increased serum creatinine or oliguria. [ NCI ]

## Suggested parent term

chronic kidney disease

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
There is an existing phenotype term for 'Acute kidney injury' (HP:0001919) which requires editing.

**Comment by zoependlington** [comment]
###  @gkos-bio please review below:

We have discussed this ticket and the term you have requested already exists within EFO as a phenotype term 'Acute kidney injury' (HP:0001919)

(see here: https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0001919)

Going forward with this ticket, we can add the synonyms and X-refs if this term is sufficient as it stands. Otherwise, please let us know how you would prefer us to proceed. Thank you.

**Comment by gkos-bio** [comment]
All good. Thank you.
One caveat is that there is a relationship to chronic kidney disease that is missing. 
We can discuss this separately.
