### ISSUE TITLE
alcoholic liver disease

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#111]
For new term requests, please provide the following information:

## Preferred term label

alcoholic liver disease

## Synonyms

Alcoholic Liver Diseases

## X-refs

NCIT_C34783
UMLS_ C0023896
ICD10 K70
MESH D008108

## Textual definition

A disorder caused by damage to the liver parenchyma due to alcohol consumption. It may present with an acute onset or follow a chronic course, leading to cirrhosis. [ NCI ]

## Suggested parent term

liver disease

'alcoholic hepatitis' in EFO should be classified under 'alcoholic liver disease'
'alcoholic cirrhosis' should be classified under 'alcoholic liver disease'

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
- [ ]Create new term:
EFO:NEW1 alcoholic liver disease
Subclass of liver disease (EFO:0001421)
Def: A disorder caused by damage to the liver parenchyma due to alcohol consumption. It may present with an acute onset or follow a chronic course, leading to cirrhosis. [ NCI ]
X-refs: NCIT_C34783
UMLS_ C0023896
ICD10 K70
MESH D008108
Synonyms: Alcoholic Liver Diseases

- [ ] Reclassify term 'Hepatitis, Alcoholic' (EFO:1001345) as subclass of alcoholic liver disease

- [ ] Reclassify term 'alcoholic liver cirrhosis' (EFO:1000802) as subclass of alcoholic liver disease

**Comment by zoependlington** [comment]
Here is the ID for the new term:
EFO:0008573 | alcoholic liver disease

**Comment by paolaroncaglia** [comment]
@zoependlington 
Looks good to me.
