### ISSUE TITLE
Relationship b/t 'Immune Repertoire Deep Sequencing' and '10x immune profiling'

### ISSUE THREAD

**Issue by nstrauli** [EBISPOT/efo#1159]
It seems that `10x immune profiling` should be a child of `Immune Repertoire Deep Sequencing`, or at least there should be some type of directional relationship from the latter to the former.

**Comment by nstrauli** [comment]
Dear Paola Roncaglia,

Yes, I was referring to NCIT:C158249. Sorry, I was using [OLS](https://www.ebi.ac.uk/ols/index) to search for terms and didn't realize that I had changed ontologies. 

Yes, I think that it would make sense to have a general class for 'Immune Repertoire Deep Sequencing' within EFO. Essentially, this would encompass assays that use deep sequencing to collect a multitude of genetic sequences for 'B Cell Receptors' (BCRs) and 'T Cell Receptors' (TCRs) within a tissue (these loci have massive amounts of somatic mutations). Within this class there would be 'bulk' and 'single cell' immune repertoire sequencing. The former refers to an assay that lyses cells and sequences BCRs and TCRs indiscriminately, and the latter refers to sequencing BCRs and TCRs that can be mapped to a single cell (the '10X immune profiling' would be an example of this). Does this make sense?

How shall we proceed. Should I submit a request for a new class in a new thread?

Best,

Nicolas Strauli

**Comment by paolaroncaglia** [comment]
Thanks @nstrauli ,

The hierarchy you suggest makes sense and may be useful for other EFO users too. 
No need to open a new ticket.
I have a few questions please:
- [ ] Should the general class 'immune repertoire sequencing', and its children 'bulk immune repertoire sequencing' and 'single cell immune repertoire sequencing', be agnostic to DNA vs RNA, or should it be specifically an RNA assay term? I'd rather keep it agnostic, because some of the terms in my example below analyze DNA, and because that way it'd be easier to classify future terms too;  
- [ ] Should any existing EFO term (in addition to '10X immune profiling') be children or descendants of 'immune repertoire sequencing'? E.g. 'Paired VH:VL Antibody Repertoire Analysis', HTGTS-Rep-seq, Rep-Seq, Ig-Seq; what others if any?  
- [ ] Could you please provide your ORCID ID so I can add it to the new terms for attribution
- [ ] Could you please provide references for the new terms: ideally PMIDs of articles, but other references (URLs) can be acceptable if they are reliable and stable. Wikipedia entries are ok too.
- [ ] @anjaf @ngeorgeebi @sfexova @pnejad I'm hoping that the proposed new terms would be useful for your projects too. If you have any comment on the suggestions, please let me know.

Thank you all,
Paola

**Comment by anjaf** [comment]
Yes, this would be useful. But we usually need to classify the terms based on RNA vs. DNA sequencing. So the issue I see is indeed that "Immune Repertoire Deep Sequencing" is defined as "DNA sequencing of..." and the 10x methods are RNA-sequencing based. If you want to keep the new EFO term agnostic to that, the definition of the new term should make it clear that this includes both types of sequencing, RNA and DNA. Hopefully, this won't lead to confusion with the existing NCIT term, if we keep the label but change the definition.

**Comment by paolaroncaglia** [comment]
Thanks @anjaf ,
If we create 'immune repertoire sequencing' as agnostic, I'd add the NCIT ID as a definition database cross reference, not as an xref, and I'd keep the definition agnostic too.

**Comment by paolaroncaglia** [comment]
Also, once we have the structure in place, we can evaluate the need for further new, intermediate terms that are DNA or RNA-specific to aid automated classification in the future.

**Comment by paolaroncaglia** [comment]
Lastly, to clarify, I'd label the general class 'immune repertoire sequencing' rather than "Immune Repertoire Deep Sequencing" to keep it as broad as possible and because "deep sequencing" isn't easy to axiomatize/differentiate from "sequencing" - unless all experiments that perform 'immune repertoire sequencing' are instances of 'assay by high throughput sequencer'?
Note the current hierarchy - there are several classes under 'assay by sequencer' that don't fall under 'assay by high throughput sequencer'.

**Comment by nstrauli** [comment]
'Immune repertoire sequencing' works for me. However, one thing to consider: the term 'repertoire' might be antagonistic to any low throughput sequencing assay. I.e. one can't really evaluate a 'repertoire' without observing a good deal of sequences, which can only be achieved using high throughput methods. On the other hand, people in the past thought they were viewing the 'repertoire' with Sanger sequencing, and people in the future will probably look back and laugh at studies today that claim to do 'repertoire' sequencing with 10^6 sequences. 

To answer your questions:

"Should the general class 'immune repertoire sequencing', and its children 'bulk immune repertoire sequencing' and 'single cell immune repertoire sequencing', be agnostic to DNA vs RNA, or should it be specifically an RNA assay term? I'd rather keep it agnostic, because some of the terms in my example below analyze DNA, and because that way it'd be easier to classify future terms too."
Yes I suppose it should be agnostic. Bulk immune repertoire seq can be done using DNA or RNA. I believe currently 10X single cell immune repertoire seq only does RNA, but it could do DNA in the future I suppose. 

"Should any existing EFO term (in addition to '10X immune profiling') be children or descendants of 'immune repertoire sequencing'? E.g. 'Paired VH:VL Antibody Repertoire Analysis', HTGTS-Rep-seq, Rep-Seq, Ig-Seq; what others if any?"
'Paired VH:VL Antibody Repertoire Analysis', 'HTGTS-Rep-seq', 'Rep-Seq', and 'Ig-Seq' should all be children of 'bulk immune repertoire sequencing'. 'Rep-Seq' seems to link to a general review, and doesn't seem to outline a specific assay, so perhaps that should be pruned, or linked to the general 'bulk immune repertoire sequencing' class? In addition to these, I found: '10x TCR enrichment' and '10x Ig enrichment'. These are appropriately children of '10X immune profiling'. I also found: 'TCR Chain Paring', which should be a child of 'bulk immune repertoire sequencing'. That's all I could find.

"Could you please provide your ORCID ID so I can add it to the new terms for attribution"
0000-0001-8575-006X

"Could you please provide references for the new terms: ideally PMIDs of articles, but other references (URLs) can be acceptable if they are reliable and stable. Wikipedia entries are ok too."
For 'bulk immune repertoire sequencing' you could use: PMID: 24441474, or the review mentioned above.
For 'immune repertoire sequencing', you can use: PMID: 32199980
I don't know if there are any references specifically for RNA and DNA. Most reviews would just mention that either can be used as template.

That's all. Thanks very much for your help!

**Comment by paolaroncaglia** [comment]
@nstrauli thank you for your useful feedback. I hope to work on these terms next week, I'll comment again here when that's done. 
Best wishes,
Paola

**Comment by paolaroncaglia** [comment]
@nstrauli 
cc @anjaf @ngeorgeebi @sfexova @pnejad
I added 
EFO_0030006 (immune sequencing)
and children
EFO_0030014 (bulk immune repertoire sequencing)
EFO_0030015 (single cell immune repertoire sequencing)
They will be available with the next EFO release, scheduled for tomorrow. When that's available in OLS (couple of days at most), please take a look at labels, definitions, hierarchy, children etc. and let me know if you'd suggest any further change.
Thank you.
Paola

**Comment by paolaroncaglia** [comment]
Hi @nstrauli (cc @anjaf @ngeorgeebi @sfexova @pnejad),
The following EFO terms are now publicly visible in OLS (https://www.ebi.ac.uk/ols/ontologies/efo), could you please take a look at their labels, definitions, hierarchy, children etc. and let me know if you'd suggest any further change:
EFO_0030006 (immune sequencing)
and children
EFO_0030014 (bulk immune repertoire sequencing)
EFO_0030015 (single cell immune repertoire sequencing)
Here's a screenshot for quick reference. Thanks in advance for your feedback.
Paola
![Screen Shot 2021-07-19 at 10 59 39](https://user-images.githubusercontent.com/4982516/126133266-ecbf4661-0957-4871-b0e2-7532a3139a71.png)

**Comment by nstrauli** [comment]
Hi @paolaroncaglia ,

This looks good to me. Thank you for doing this!

**Comment by paolaroncaglia** [comment]
Thanks @nstrauli .
