### ISSUE TITLE
Peritonitis

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#117]
For new term requests, please provide the following information:

## Preferred term label

peritonitis

## X-refs

NCIT_C26849
ICD10 K65
UMLS:C0031154 (Peritonitis) 
HP:0002586 (Peritonitis)
MESH D010538

## Textual definition

Inflammation of the peritoneum due to infection by bacteria or fungi. Causes include liver disease, perforation of the gastrointestinal tract or biliary tract, and peritoneal dialysis. Patients usually present with abdominal pain and tenderness, fever, chills, and nausea and vomiting. It is an emergency medical condition that requires prompt medical attention and treatment. [ NCI ]

## Suggested parent term

peritonitis => digestive system disease
septic peritonitis => peritonitis
tuberculous peritonitis => peritonitis

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
- [ ] EFO:NEW1 peritonitis
subclass of digestive system disease (EFO:0000405)
X-refs: NCIT:C26849 || ICD10 K65 || UMLS:C0031154 || HP:0002586 || MESH_D010538
Def: Inflammation of the peritoneum due to infection by bacteria or fungi. Causes include liver disease, perforation of the gastrointestinal tract or biliary tract, and peritoneal dialysis. Patients usually present with abdominal pain and tenderness, fever, chills, and nausea and vomiting. It is an emergency medical condition that requires prompt medical attention and treatment. [ NCI ]

- [ ] EFO:EDIT septic peritonitis (EFO:0002623)
subclass of peritonitis (EFO:NEW1)

- [ ] EFO:EDIT: tuberculous peritonitis (EFO:0007529)
subclass of peritonitis (EFO:NEW1)

**Comment by zoependlington** [comment]
Here is the ID for the new term:
EFO:0008588 || peritonitis
