### ISSUE TITLE
EFO label and definition for PATO_0000047 differs from PATO's

### ISSUE THREAD

**Issue by ppavlidis** [EBISPOT/efo#1192]
In PATO, this term has the label "biological sex". The EFO usage has it as "sex". The definition is also different. This is causing our curators some (minor) confusion.

Compare http://www.ontobee.org/ontology/EFO?iri=http://purl.obolibrary.org/obo/PATO_0000047 and http://www.ontobee.org/ontology/PATO?iri=http://purl.obolibrary.org/obo/PATO_0000047

Thanks!

**Comment by paolaroncaglia** [comment]
Dear @ppavlidis ,

> In PATO, this term has the label "biological sex". The EFO usage has it as "sex". The definition is also different. This is causing our curators some (minor) confusion.

Thanks for contacting us. The discrepancy is most likely due to an old import of PATO. I suspect that PATO:0000047 has since become PATO:0001894 'phenotypic sex'. We'll fix this in time for the next EFO release (mid-August) and will comment here when done. 

Notes for self/EFO editors:
- [ ] Edit EFO PATO:0000047 'sex' to reflect PATO:0001894 'phenotypic sex'; keep 'sex' as a broad synonym;
- [ ] Import PATO:0000047 'biological sex'; make it a parent of PATO:0001894 'phenotypic sex';
- [ ] Discuss with the EFO team if we wish to import PATO dynamically. If not, are there other stale PATO terms in EFO that need fixing?

**Comment by paolaroncaglia** [comment]
Dear @ppavlidis ,

> In PATO, this term has the label "biological sex". The EFO usage has it as "sex". The definition is also different. This is causing our curators some (minor) confusion.
> 
> Compare http://www.ontobee.org/ontology/EFO?iri=http://purl.obolibrary.org/obo/PATO_0000047 and http://www.ontobee.org/ontology/PATO?iri=http://purl.obolibrary.org/obo/PATO_0000047
> 
> Thanks!

This issue is fixed now, as detailed in https://github.com/EBISPOT/efo/issues/1192#issuecomment-889872395, and the changes will be public with the next release of EFO, scheduled for August 16th.
Thanks,

Paola Roncaglia
