### ISSUE TITLE
infectious arthritis synonyms

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#120]
For new term requests, please provide the following information:

## Preferred term label

infectious arthritis
http://www.ebi.ac.uk/efo/EFO_1001351

## Synonyms

Pyogenic Arthritis
Suppurative Arthritis
Arthritides, Bacterial
Arthritis, Bacterial
Arthritis, Septic
Arthritis, Suppurative
Arthritis, Viral
Bacterial Arthritides
Bacterial Arthritis
Infectious arthritis

## X-refs
NCIT_C118475
UMLS CUI C3891815
ICD10 M00
MSH:D001170
DOID:813

## Textual definition

Acute inflammation of one or more joints caused by the presence of pus within the joint cavity. [ NCI ]

## Suggested parent term

arthritis

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
- [ ] EFO:EDIT infectious arthritis (EFO:1001351)
Synonyms: Pyogenic Arthritis || Suppurative Arthritis || Arthritides, Bacterial || Arthritis, Bacterial || Arthritis, Septic || Arthritis, Suppurative || Arthritis, Viral || Bacterial Arthritides || Bacterial Arthritis || Infectious arthritis
X-refs: NCIT:C118475 || UMLS_CUI:C3891815 || ICD10:M00 || MSH:D001170 || DOID:813
Def: Acute inflammation of one or more joints caused by the presence of pus within the joint cavity. [ NCI ]
