### ISSUE TITLE
New term request for Matzaraki PMID 34512620

### ISSUE THREAD

**Issue by buniello** [EBISPOT/efo#1288]
For new term requests, please provide the following information:

## Preferred term label

monocyte chemotactic protein 2 measurement

## Synonyms

MCP-2

## Textual definition

quantification of the amount of monocyte chemotactic protein 2 in a sample

## Suggested parent term

http://www.ebi.ac.uk/efo/EFO_0007937

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by kallia-p** [comment]
@buniello 
EFO already has a term 'monocyte chemotactic protein-2 measurement' EFO_0010789 with MCP2 as a synonym and dbxref PMID:32641083
I have added two more synonyms to the existing term 'monocyte chemotactic protein 2 measurement and 'MCP-2'. 
There was also an error in the definition it referred to protein-4 instead of 2 which is now fixed. 
All the monocyte chemotactic monocyte terms in EFO are synonyms with several C-C motif chemokine measurements and therefore these terms will be collectively reviewed in a separate ticket for merging. For example the term above is also present in EFO as 'C-C motif chemokine 8 measurement'.
