### ISSUE TITLE
New terms and x-ref for drug safety

### ISSUE THREAD

**Issue by nbosc** [EBISPOT/efo#1439]
A set of adverse event terms that originates from MedDRA and SNOMED-CT and are used for annotating drug withdrawal reasons.

https://docs.google.com/spreadsheets/d/1MXRRR4PEGAdv6gwY59UutUCPI4rIRWOIVTKcgXn1rsA/edit?usp=sharing

**Comment by zoependlington** [comment]
@nbosc I have now curated through your template completely.

Any existing EFO terms, I will add the x-refs and any synonyms to (these are all coloured in teal currently) before tomorrow's release.
Any terms that are in green are terms I will also create in EFO before tomorrow based on your template.
The terms in red are those that exist in ontologies outside of my control and so any x-refs you would like to add to these will need to be requested on their trackers (most are [Mondo](https://github.com/monarch-initiative/mondo/issues/) and [HP](https://github.com/obophenotype/human-phenotype-ontology/issues)), however I will make sure these are imported into EFO to gain these x-refs in the future once they are added to Mondo and HP.
There are two terms I'm still debating what to do with (in yellow, congenital anomaly and congenital malformation) as these were [recently obsoleted in Mondo](https://github.com/monarch-initiative/mondo/issues/3661) where we previously imported them from. I will look into these further, although they might not be in EFO for tomorrow's release.

**Comment by zoependlington** [comment]
You can request for the x-refs/synonyms to be added on their trackers: [Mondo](https://github.com/monarch-initiative/mondo/issues/) and [HP](https://github.com/obophenotype/human-phenotype-ontology/issues). Once they're added to the respective domain ontology, they'll be pulled into EFO automatically after they've been released 😄

**Comment by zoependlington** [comment]
**The following terms have been created and will be available after tomorrow's release:**

<google-sheets-html-origin>
ID | label
-- | --
EFO:0020911 | overdose
EFO_0020912 | decreased kidney function
EFO_0020913 | Electrocardiogram repolarisation abnormality
EFO_0020914 | Disorientation
EFO_0020915 | Uterine hyperstimulation
EFO_0020916 | Performance enhancing product use
EFO_0020917 | Oculomucocutaneous syndrome
EFO_0020918 | Non-allergic anaphylaxis
EFO_0020919 | Subacute myelo-opticoneuropathy
EFO_0020920 | Hepatic lesion
EFO_0020921 | Haemorrhagic stroke
EFO_0020922 | Hospitalisation
EFO_0020909 | Psychomotor skills impaired
EFO_0020910 | Thermal burn
EFO_0020923 | Accidental overdose
EFO_0020924 | Intentional overdose
EFO_0020925 | Angina unstable
EFO_0020926 | Noninfective encephalitis
EFO_0020927 | Skin reaction
EFO_0020928 | Ocular toxicity
EFO_0020929 | Electrocardiogram PR prolongation
EFO_0020930 | Immune-mediated adverse reaction

**The following should be requested to HP:**

<google-sheets-html-origin>
ID | x-refs
-- | --
HP:0030157 | MedDRA:10016750\|\|SCTID:247355005
HP:0002910 | MedDRA:10024690\|\|SCTID:166603001
HP:0001657 | MedDRA:10014387
HP:0001657 | SCTID:111975006
HP:0003401 | MedDRA:10033775\|\|SCTID:91019004
HP:0000708 | MedDRA:10061472\|\|SCTID:75864003
HP:0002910 | MedDRA:10060795
HP:0002605 | MedDRA:10019692\|\|SCTID:87248009
HP:0007185 | MedDRA:10024855\|\|SCTID:419045004
HP:0001787 | MedDRA:10061781
HP:0001787 | SCTID:199745000
HP:0002590 | MedDRA:10021333
HP:0032310 | MedDRA:10018690\|\|SCTID:317226009
HP:0001942 | MedDRA:10027417\|\|SCTID:59455009
HP:0007957 | MedDRA:10011035
HP:0032156 | MedDRA:10041036
HP:0001913 | MedDRA:10018687\|\|SCTID:417672002
HP:0025428 | MedDRA:10006482\|\|SCTID:4386001
HP:0006677 | MedDRA:10014380
HP:0200119 | MedDRA:10019727
HP:0000112 | MedDRA:10029151
HP:0000726 | MedDRA:10078497\|\|SCTID:10171000132106
HP:0001824 | MedDRA:10047895

**The following should be requested to Mondo:**

<google-sheets-html-origin>

ID | x-refs
-- | --
MONDO:0100053 | MedDRA:10002198
MONDO:0100053 | SCTID39579001
MONDO:0005149 | MedDRA:10037400
MONDO:0021553 | MedDRA:10028527
MONDO:0018109 | MedDRA:10019772
MONDO:0001117 | MedDRA:10027496\|\|SCTID:38959009
MONDO:0021084 | MedDRA:10047518\|\|SCTID:95677002
MONDO:0015346 | MedDRA:10084303

The rest have been existing EFO terms I have added the x-refs to (these are available in the template).

I have not added anything for the following as I will need to figure out how to handle previously obsoleted classes:
Congenital anomaly
Congenital malformation

**Comment by nbosc** [comment]
Thanks @zoependlington! I will see with HP and MONDO for the synonyms.

**Comment by nbosc** [comment]
Unfortunately there are 5 terms that I still can’t find in EFO:
- Congenital anomaly: I reiterate what I put in the spreadsheet, I think this term should be created and it would be the parent of all of specific congenital anomalies already present in the ontology (congenital heart disease, congenital anomaly of the great veins … )
- Neuropsychiatric symptoms: this term was mapped to HP_0000726 (Dementia) and I disagree. Neuropsychiatric symptoms are not only associated with dementia but also with neurodegenerative disease such as Alzheimer's disease.
- Skin sensitisation: this term was mapped to EFO:0000701 (skin disease). Although I have no issue categorising skin sensitisation as a skin disease, it is a very specific immunological response to previous exposure to a substance which results in an inflammatory skin reaction. So maybe it should be a child of skin disease.
- Complication of delivery: can be xref with Abnormal delivery (HP:0001787). MedDRA:10061781
- Hepatitis fulminant: was mapped to MONDO:0018109 (fulminant viral hepatitis) and it’s maybe because in the spreadsheet I gave you the definition of fulminant viral hepatitis… However this condition is not necessarily linked to a viral infection since overdose of paracetamol is also a cause. Therefore I suggest to create this entry in EFO and to consider it as the parent of fulminant viral hepatitis.

**Comment by zoependlington** [comment]
Thank you for replying to this, @nbosc.

- I am still looking into congenital anomaly. This term was previously obsoleted in EFO due to being a grouping class that was difficult to maintain and deemed no longer useful after all prior children were "rehoused". It was also obsoleted in Mondo for similar reasons and we typically like to align with Mondo as much as possible. I will continue to discuss this with my fellow ontology developers to figure out a solution.
- Would 'Abnormality of higher mental function' (HP_0011446) work for neuropsychiatric symptoms better? It is defined as "Cognitive, psychiatric or memory anomaly" and contains terms like dementia as descendants.
- I will create a new term for skin sensitisation under skin disease. (note to self x-ref ENM:0000034.)
- For Complication of delivery, I'm not able to add the x-ref to Abnormal delivery as this is a HP term and will have to be added by HP, however the term is in EFO and therefore will gain the x-ref if it is requested to be added to HP.
- Alternatively, I can import HP:0004787 (fulminant hepatitis) from HP if that would be better? The x-ref, again, will have to be requested to be added to HP.

**Comment by nbosc** [comment]
Thank you @zoependlington!

Okay for all the points.

**Comment by zoependlington** [comment]
I've added skin sensitization as EFO:0020984 and imported HP:0004787 (fulminant hepatitis) into EFO. Both will be available after May release on the 16th.

I believe this just leaves the congenital anomaly question to be solved for this ticket, but please let me know if I've missed anything else!

Right now, there is the Mondo term of MONDO_0021140 (congenital), which is not ideal but is used in Mondo terms to distinguish congenital diseases with SubclassOf 'has modifier' some congenital.

**Comment by nbosc** [comment]
Okay, thank you.

I'm clearly not an ontology expert so I'll assume the reasons why 'congenital abnormality' was obsoleted counter-balance the advantages of having the term in EFO.
I suggest to leave this term aside for the moment.

**Comment by zoependlington** [comment]
Thanks for your reply @nbosc, I believe this ticket can be moved to done in that case. If you have any more term requests or further issues, please open a new ticket so they can be addressed.
