### ISSUE TITLE
Investigate dangling CL_0002453

### ISSUE THREAD

**Issue by zoependlington** [EBISPOT/efo#1454]
Currently in EFO CL_0002453 is violating the no-dangling violation when the full pipeline is ran.

**Comment by zoependlington** [comment]
@paolaroncaglia I suspect this is the case. I might be able to force parentage in EFO as a temporary fix, but should this be fixed in CL?

**Comment by paolaroncaglia** [comment]
@zoependlington, the edit didn't seem to break anything in CL, and CL was released a week ago, so we weren't planning to do another release before a few weeks. Perhaps easier/quicker to import the parent and grandparent of the CL term into EFO? Would the no-dangling violation break anything for EFO end-users unless you imported + ran a patch release?
Otherwise I'll liaise for a CL fix.

**Comment by zoependlington** [comment]
I'll look into importing parents, thanks @paolaroncaglia!

**Comment by zoependlington** [comment]
Unfortunately importing the parent term did not fix the issue at all, even after also importing the develops from relationship into EFO. I have added a manual subclass for CL:0002453 as a child of CL:0000123 into EFO using the subclass.csv template in order to continue with the patch release that is needed for https://github.com/EBISPOT/efo/issues/1456

**Comment by paolaroncaglia** [comment]
@zoependlington 

> Unfortunately importing the parent term did not fix the issue at all, even after also importing the develops from relationship into EFO. I have added a manual subclass for CL:0002453 as a child of CL:0000123 into EFO using the subclass.csv template in order to continue with the patch release that is needed for #1456

If you think that this should be fixed in CL, could you please comment on the last green line [here](https://github.com/obophenotype/cell-ontology/pull/1442/files) and tag Bradley and Shawn. I'm not 100% sure that the subclass as is is what's causing the issue, so I'd like Shawn's opinion. Thanks.

**Comment by zoependlington** [comment]
I suspect it's more the way EFO's imports work rather than CL, but I will investigate it more thoroughly and comment if needed. Thanks Paola!
