### ISSUE TITLE
monoclonal gammopathy vs benign monoclonal gammopathy

### ISSUE THREAD

**Issue by cmungall** [EBISPOT/efo#149]
https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0000203

 1. classified as neoplasm - don't think this is right. Error propagated from DO which itself go this from ICD I imagine? Poses some risk but not itself a neoplasm?
 2. this is usually treated as a lab finding (e.g in NCIT) not a disease
 3. it has one child (bad smell), and the distinct between this and the child is unclear, both have syns MGUS. Recommend: merge
 4. looks like the def came from icd but not provenance?

cc @nicolevasilevsky

**Comment by paolaroncaglia** [comment]
Notes for self from a first quick look at this ticket:

The definition in EFO points to monoclonal gammopathy of undetermined significance, rather than simply monoclonal gammopathy (relevant because - see the distinction between these Wikipedia entries: https://en.wikipedia.org/wiki/Paraproteinemia vs. https://en.wikipedia.org/wiki/Monoclonal_gammopathy_of_undetermined_significance)

A recent paper I might want to look at: https://www.ncbi.nlm.nih.gov/pubmed/26732417

**Comment by paolaroncaglia** [comment]
@cmungall
This is a tricky one. In reply to your points:

1 and 2. It’s not a neoplasm though it can progress to one; its diagnosis depends on a measurement, but it’s not a measurement itself; it can or cannot have disease manifestations… but I guess that EFO would still classify it as a disease rather than as a risk factor the way NCIt does, on the basis that a risk factor is
“An aspect of personal behavior or lifestyle, environmental exposure, or inborn or inherited characteristic, which, on the basis of epidemiologic evidence, is known to be associated with a health-related condition considered important to prevent.
Any aspect of an individual's life, behavior, an environmental exposure, or an inborn or inherited characteristic that increases the likelihood of a disease, condition or injury.)”
and that I wouldn’t consider 
“an abnormal amount of a single immunoglobulin [is] present in the serum”
as an inborn or inherited characteristic.
So I’d place it under ‘hematological system disease’.

3. While in principle a subclass to indicate a bening form can be useful, it is true that the benign term xrefs to the NCIt term for the generic, potentially malignant form. So I’d keep the child term but I’d remove the NCIt xref. I can’t find the DOID term (?) so not sure if that should stay or not. The MeSH xref can stay.

4. Not sure…

**Comment by paolaroncaglia** [comment]
cc @nicolevasilevsky

**Comment by paolaroncaglia** [comment]
@cmungall and @nicolevasilevsky 
When you can, please let me know if you have any concern with the plan I outlined in my comment above (dated May 17). Thanks!
Paola

**Comment by nicolevasilevsky** [comment]
Hi @paolaroncaglia 
NCIt classifies '[monoclonal gammopathy](https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&version=18.04e&ns=ncit&code=C35548&key=1750127992&b=1&n=null)' as a 'laboratory finding or test result', which is defined as 'The outcome of the laboratory test assessment.' I don't think they have it classified as a risk factor?

Looks like DO only has '[monoclonal gammopathy of uncertain significance'](https://www.ebi.ac.uk/ols/ontologies/doid/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FDOID_7442).

@cmungall in MONDO, this is classified as a child of MONDO_0004959 'plasma cell neoplasm', which I think is wrong. I'll open a ticket on the MONDO tracker.

**Comment by paolaroncaglia** [comment]
Hi @nicolevasilevsky and @cmungall ,
I can't remember how the 'risk factor' link came about, but it seems that Nicole and I both agree on placing EFO 'monoclonal gammopathy' as a subclass of 'hematological system disease', so that's good. I'd like to hear what your strategy would be wrt the MONDO ticket above, as ideally we'd like to align. Thanks!

**Comment by cmungall** [comment]
We'll do the same thing, thanks!

**Comment by paolaroncaglia** [comment]
Note for self: summing up:
- [ ] Move EFO:0000203 ‘monoclonal gammopathy’ from subclass of ‘plasma cell neoplasm’ to ‘hematological system disease’;
- [ ] Remove the current NCIt xref from EFO:1000836 ‘benign monoclonal gammopathy’.

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky 
@cmungall 
The changes above have been committed and will be visible in our upcoming release, due on Monday (June 18th). Thanks,
Paola
