### ISSUE TITLE
review classification of neurodegenerative diseases

### ISSUE THREAD

**Issue by siiraa** [EBISPOT/efo#15]
More neurodegenerative diseases are being requested at EFO. Need to ensure that terms are created properly and duplications/wrong classification don't get in.

**Comment by siiraa** [comment]
Reference with the latest release of MonDO (Nov.11.2017). Update report at EFO planning next week (Nov.23.2017).

**Comment by paolaroncaglia** [comment]
Notes for self:
General strategy for EFO: don’t create where you can import. So, aim at importing/aligning with the whole branch of “neurodegenerative disease” from MONDO. (The owl file is at http://purl.obolibrary.org/obo/mondo.owl. This is the main OWL edition. Complete ontology, plus inter-ontology equivalence axioms. Uses MONDO IDs.) I’ll assume that the branch in MONDO is up-to-date and in good shape, since their release is only a week old - though the ontology was generated semi-automatically, it should have been manually reviewed.
Things to look into:
- Does the MONDO “neurodegenerative disease” branch make sense to me?
- Does it have big differences with respect to the current corresponding branch in EFO that need clarifying?
- Does it have classes that EFO doesn’t? (It should) If yes, does it make sense to import all of them already - i.e. are they likely be useful for Open Targets?
- Does it NOT have classes that EFO has? (It shouldn’t, since the MONDO release notes mention precise 1:1 equivalence axioms) If so, should those classes be removed from EFO?
- Should we need to rearrange EFO significantly, would that create downstream issues?

**Comment by siiraa** [comment]
@simonjupp @paolaroncaglia we might need to discuss the create VS import. There may be certain benefits in keeping a unified EFO namespace in EFO. So we might want to create the terms under EFO namespace but make full equivalence to MonDO terms.

**Comment by paolaroncaglia** [comment]
@siiraa Thanks, I'll keep that in mind when I start addressing the tasks listed above.

**Comment by paolaroncaglia** [comment]
@simonjupp @siiraa 

I started to look at the ‘neurodegenerative disease’ branch in MONDO (http://purl.obolibrary.org/obo/MONDO_0005559) and to compare it to the corresponding branch in EFO (http://www.ebi.ac.uk/efo/EFO_0005772). Overall, it doesn’t look like we could simply import/duplicate what MONDO has. First thoughts:

- In EFO, we care about the distinction (differentia) between a disease and a *genetic* form of the same disease. So it’s important to have ‘genetic neurodegenerative disease’ is_a ‘neurodegenerative disease’ high up in the branch, as is now in EFO but not in MONDO. 

- In EFO, we wish to lose the distinction (differentia) between a disease and a *rare* form of the same disease, on the ground that ‘rare’ is not an objective classification, and that the frequency of disease cases should be captured in a different way. So we wouldn’t want to import or align to MONDO ‘rare neurodegenerative disease’ (http://purl.obolibrary.org/obo/MONDO_0015918) which is_a MONDO ‘neurodegenerative disease’. Similarly, we may want to lose classes such as the current ’Rare parkinsonian syndrome due to genetic neurodegenerative disease’ (http://www.orpha.net/ORDO/Orphanet_307055) and rather make sure that we keep all of its descendant and rehouse them appropriately.
(Note that EFO has ‘Rare genetic neurological disorder’ (http://www.orpha.net/ORDO/Orphanet_71859) which is_a genetic disorder but has no link to ‘nervous system disease’. It has many children, we may need to look into this branch.)

- I presume that we may want to lose grouping classes derived from Orphanet and named with this cumbersome pattern: ‘Miscellaneous movement disorder due to genetic neurodegenerative disease’ (http://www.orpha.net/ORDO/Orphanet_307058), ‘Rare parkinsonian syndrome due to genetic neurodegenerative disease’ (http://www.orpha.net/ORDO/Orphanet_307055). Their descendants should be kept and classified appropriately if they aren’t already.

- On a minor note, ‘synucleinopathy’ in EFO has no descendants; it would benefit from mirroring the richer MONDO hierarchy.

Simon and Sira, if you could please confirm that my observations above align with an EFO mindset, I’ll then start looking into the finer details. Thanks!

**Comment by siiraa** [comment]
@paolaroncaglia Thank you. Your observations do align with EFO's principle.



    _"In EFO, we care about the distinction (differentia) between a disease and a genetic form of the same disease. So it’s important to have ‘genetic neurodegenerative disease’ is_a ‘neurodegenerative disease’ high up in the branch, as is now in EFO but not in MONDO."_

- yes, this term should be classified under 2 parents: neurodegenerative disease, can genetic disorder.

    _"In EFO, we wish to lose the distinction (differentia) between a disease and a rare form of the same disease, on the ground that ‘rare’ is not an objective classification, and that the frequency of disease cases should be captured in a different way. So we wouldn’t want to import or align to MONDO ‘rare neurodegenerative disease’ (http://purl.obolibrary.org/obo/MONDO_0015918) which is_a MONDO ‘neurodegenerative disease’. Similarly, we may want to lose classes such as the current ’Rare parkinsonian syndrome due to genetic neurodegenerative disease’ (http://www.orpha.net/ORDO/Orphanet_307055) and rather make sure that we keep all of its descendant and rehouse them appropriately."_

- If the term is already in EFO, keep it. If not, do not put it in :)

    _"(Note that EFO has ‘Rare genetic neurological disorder’ (http://www.orpha.net/ORDO/Orphanet_71859) which is_a genetic disorder but has no link to ‘nervous system disease’. It has many children, we may need to look into this branch.)"_

- this would fall into the category of already-there-so-we-keep-it.

    _"I presume that we may want to lose grouping classes derived from Orphanet and named with this cumbersome pattern: ‘Miscellaneous movement disorder due to genetic neurodegenerative disease’ (http://www.orpha.net/ORDO/Orphanet_307058), ‘Rare parkinsonian syndrome due to genetic neurodegenerative disease’ (http://www.orpha.net/ORDO/Orphanet_307055). Their descendants should be kept and classified appropriately if they aren’t already."_

- if the grouping classes are already in EFO, we keep them but we probably should axiomatise them (and their descendant classes) so they classify cleaner.

    _"On a minor note, ‘synucleinopathy’ in EFO has no descendants; it would benefit from mirroring the richer MONDO hierarchy."_

- sure.


Thank you 👍

**Comment by paolaroncaglia** [comment]
Thanks @siiraa !

**Comment by paolaroncaglia** [comment]
@siiraa 
Wrt your note that ‘genetic neurodegenerative disease’ should be classified under 2 ‘neurodegenerative disease’ and ‘genetic disorder’. It currently is a subclass of ‘neurodegenerative disease’ and ‘Rare genetic neurological disorder’; the latter is too specific and therefore incorrect, in my view. I see your point of leaving ‘rare disease’ terms in EFO if they are there already, but I assume it’d be ok if I severed the existing link between ‘genetic neurodegenerative disease’ and ‘Rare genetic neurological disorder’ - and replaced it with one to ‘genetic disorder’? 
Thanks!

**Comment by paolaroncaglia** [comment]
@siiraa @simonjupp 
Another general question please. MONDO has 1:1 equivalence axioms with other ontologies where applicable, including EFO. So e.g. MONDO ‘neurodegenerative disease’ MONDO:0005559 is equivalentTo EFO ‘neurodegenerative disease’ EFO:0005772. Will the reverse equivalences be added automatically to EFO, or should we manually add them as database cross references as we come across them?
Thanks again.

**Comment by siiraa** [comment]
@paolaroncaglia 
- yes, modifying the parents as you see fit.
- @twhetzel is also filing a ticket for me to add a MonDO definition citation in the Disease template. I might as well create another MonDO definition citaiton to make sure that the xRef is definition there. cheers.

**Comment by paolaroncaglia** [comment]
Thanks @siiraa , I won't add MONDO refs then.

**Comment by paolaroncaglia** [comment]
@siiraa 
Looking at the main structure of EFO ‘neurodegenerative disease’ from the top down, here are some suggested edits to start with. Please comment if anything looks incorrect:

Orphanet:183500 Genetic neurodegenerative disease
- [ ] Severe the existing link between ‘genetic neurodegenerative disease’ and ‘Rare genetic neurological disorder’ - and replace it with one to ‘genetic disorder’
- [ ] Need to look at children

EFO:1001809 Marchiafava-Bignami Disease: 
EFO defines it as “A neurodegenerative condition that is characterized by demyelination or necrosis of the CORPUS CALLOSUM”; MONDO says that “Marchiafava Bignami disease is defined by characteristic demyelination of the corpus callosum”. So
- [ ] Place it under EFO:NEW ‘demyelinating disease’ (see MONDO:0002562) but only if this grouping class could be useful to Open Targets
- [ ] If EFO:NEW ‘demyelinating disease’ is created, make it an additional parent of EFO:0003885 ‘multiple sclerosis’
- [ ] Add axiom Marchiafava-Bignami Disease has_disease_location some UBERON:0002336 corpus callosum

Orphanet:307058 Miscellaneous movement disorder due to genetic neurodegenerative disease:
- [ ] Modify its placement, from Subclass of ‘neurodegenerative disease’ and ‘Rare genetic movement disorder’ to Subclass of ‘Genetic neurodegenerative disease’ and ‘movement disorder’
- [ ] Need to look at children

Orphanet:306719 Neurodegenerative disease with chorea:
- [ ] Modify its placement, from Subclass of ‘neurodegenerative disease’ and ‘Rare genetic movement disorder’ to Subclass of ‘Genetic neurodegenerative disease’ and ‘movement disorder’. Note that this makes the class equivalent to ‘Miscellaneous movement disorder due to genetic neurodegenerative disease’. Do we need to introduce a differentia to refer to the choreic nature of the movement disorder? Would it really be useful to Open targets?
- [ ] Need to look at children

EFO:0002508 Parkinson's disease:
- [ ] Modify its placement, from Subclass of ‘neurodegenerative disease’ to more specific Subclass of ‘synucleinopathy’, same as in MONDO

…to be continued.

**Comment by paolaroncaglia** [comment]
Orphanet:307055 Rare parkinsonian syndrome due to genetic neurodegenerative disease:
- [ ] Modify its placement, from Subclass of ‘neurodegenerative disease’ and ‘Rare genetic parkinsonian disorder’ to ‘Genetic neurodegenerative disease’ and ‘movement disorder’. I think we should also make it a Subclass of ‘Parkinson’s disease’? 
- [ ] Need to look at children

**Comment by paolaroncaglia** [comment]
Note for today's meeting: to finish this ticket, I need more time please (the branch is large and complex, and I’ll be at a conference + retreat all of next week), and perhaps some feedback on a few questions. I’ll highlight those in bold in previous comments (and future ones if necessary).

**Comment by paolaroncaglia** [comment]
At OntoTool scrum meeting today, we decided I'll look at this with @siiraa when she's back.

**Comment by siiraa** [comment]
We discussed and concluded that, until the assay hackathon (Jan.31.2018), Paola will work on this ticket.

cc: @simonjupp

**Comment by paolaroncaglia** [comment]
@siiraa kindly agreed to take a look at my questions highlighted in bold in previous comments in this ticket :-) when she has a chance. Then I will move on to the rest of the branch. Thanks!

**Comment by paolaroncaglia** [comment]
Note for self - quick update following our weekly meeting today:
When Sira is back, we will have a discussion on how we can close this issue, or break it down. Also, if/when we can get Open Targets to use MONDO for diseases, that would solve a lot of issues like this one.

**Comment by simonjupp** [comment]
Review has been done. There are some suggestions in here to align with MONDO but we decided that these can wait until we do a larger import of MODNO into EFO. Moving ticket to icebox.

**Comment by gkos-bio** [comment]
Hello, 
Do you have any news on when this will be removed from the icebox?
This is slightly embarrassing on the Open Targets website to see the motor neuron diseases scattered in different branches.
This applies to other type of diseases as well.

**Comment by paolaroncaglia** [comment]
@gkos-bio
Thanks for following up on this. Any current issue in the classification of neurodegenerative diseases would very likely be fixed when we merge MONDO in. Briefly, that would happen with the release of EFO 3, and the expected timeline is the mid-September release; @zoependlington has been working on a prototype and it’s nearly ready (https://github.com/EBISPOT/efo/issues/158). But if there are any bad mistakes that can’t wait until then, please point us to the specifics and we’ll aim for a quick fix. Thanks!

**Comment by simonjupp** [comment]
@gkos-bio we'd like to break this ticket up into specific tasks. It would be useful to get together with Zoe and Paola to go through go over the suggestions already made and priorities any changes that need to be made before EFO 3 is ready.

**Comment by paolaroncaglia** [comment]
In preparation for the dedicated workshop that might take place in conjunction with the next Open Targets Integration Day, 

- [ ] I will start with checking that the motor neuron diseases are placed consistently (rather than scattered) in the current, beta version of EFO 3.

- [ ] Then I will check if the issues/to-do items listed in earlier comments in this ticket are addressed or not in the current, beta version of EFO 3.

If there are cases where we’re in doubt, I’ll make a note of specific questions to ask the experts.

**Comment by paolaroncaglia** [comment]
Hi @gkos-bio ,
In reply to your comment
"This is slightly embarrassing on the Open Targets website to see the motor neuron diseases scattered in different branches"
I am happy to say that in the beta version of EFO 3 and following integration with MONDO, that issue has been addressed, and the 'motor neuron disease' branch is now consistent and enriched.
More on neurodegenerative diseases soon.

**Comment by paolaroncaglia** [comment]
Going through earlier comments in this ticket. [Got as far as Nov 30 2017 excluded.] Most issues noted previously are fixed in EFO 3, except for a few checkboxes. Pending questions so far:

[ ] Due to ORDO having ‘rare’ disease classes (and MONDO inheriting them sometimes), EFO 3 still has ‘Genetic neurodegenerative disease’ (an ORDO term) as a subclass of, among others, ‘Rare genetic neurological disorder’ and ‘rare neurodegenerative disease’. Presumably this happens elsewhere in the disease branch. From a lexical point of view, this classification looks incorrect (a rare form of a disease should be a subclass of the generic disease, and not the other way round). But from a we-know-how-ORDO-works point of view, we’ve lived with this until now. Shall we continue to keep such classifications under ‘rare’ diseases, within the context of ‘if a ‘rare disease’ term is already in EFO, keep it’? 

...TBC.

**Comment by paolaroncaglia** [comment]
- [ ] In EFO 3 and MONDO, ‘Huntington disease’ is a subclass of

Genetic neurodegenerative disease with dementia
Neurodegenerative disease with chorea
Huntington disease and related disorders
eye degenerative disease
Oculomotor apraxia or related oculomotor disease

Also, in MONDO, 
disease has feature some dementia

From some quick reading, it appears that the eye-related problems are among symptoms/ markers of Huntington disease, but classifying that way doesn’t feel correct and may derive from the peculiar way that ORDO uses ‘part of’ (see https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_399). I’d suggest replacing
‘Huntington disease’ subclass of ‘eye degenerative disease’/’Oculomotor apraxia or related oculomotor disease’
with
‘Huntington disease’ has feature some ‘eye degenerative disease’/’Oculomotor apraxia or related oculomotor disease’

**Comment by paolaroncaglia** [comment]
Note for self: when the HD issue is fixed, close this ticket.
