### ISSUE TITLE
New term request for PMID:34437536

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1518]
For new term requests, please provide the following information:

## Preferred term label

response to hydroxyurea

## Synonyms

NA

## Textual definition

Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a hydroxyurea stimulus. [ GOC:mah ]

## Suggested parent term
Present in http://purl.obolibrary.org/obo/GO_0072710

**Comment by zoependlington** [comment]
response to hydroxyurea (GO_0072710) is already in EFO so I'll move this ticket to done, but if there's any problem please reply to this ticket.

**Comment by Santhi1901** [comment]
I am not able to find the term in EFO. when I search with 'GO_0072710', it gives no result
<img width="1611" alt="Screenshot 2022-04-28 at 2 45 46 pm" src="https://user-images.githubusercontent.com/57477790/165766704-a6dfbdc2-b632-4db9-83b6-1b12dd8fc0d7.png">

**Comment by zoependlington** [comment]
Due to some complications with servers and the data centre move the OLS version is stuck in the February release, which may be why you can't see it on OLS. I've double checked this and the other ticket (https://github.com/EBISPOT/efo/issues/1519#issuecomment-1112229552) and they're both definitely in EFO.
