### ISSUE TITLE
Reasoning of Familial dilated cardiomyopathy and Familial idiopathic dilatation of the right atrium

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/efo#154]
The term "Familial dilated cardiomyopathy" [1] reasons under "cardiomyopathy". However since there is also the term "dilated cardiomyopathy" should this be the classification?

Also, should "Familial idiopathic dilatation of the right atrium" [2] have the property "has_disease_location some myocardium" so that it reasons under "cardiomyopathy" or whatever term is decided above for "Familial dilated cardiomyopathy"?

[1] https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_217607

[2] https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_1677

**Comment by paolaroncaglia** [comment]
@twhetzel 
In EFO3, 'Familial dilated cardiomyopathy' is now a subclass of 'dilated cardiomyopathy' and 'familial cardiomiopathy', so that addresses your first question above. It also has the axiom 'has_disease_location some myocardium'.
As for your second question, 'Familial idiopathic dilatation of the right atrium' now has the axiom 'has_disease_location some right atrium' in EFO3. However, as far as I can't see it's not reasoning under cardiomiopathy. I think this is because 'right atrium' and 'myocardium' are not linked at least in EFO. I haven't looked into this in detail - could you please check if you think there's an error somewhere? Thanks!

**Comment by paolaroncaglia** [comment]
Update: we believe this is a non-issue because 'right atrium' and 'myocardium' are not linked - and shouldn't be, other than both being heart parts. Moving to Done.
