### ISSUE TITLE
New term request for 'FMI clinical data'

### ISSUE THREAD

**Issue by gladkia** [EBISPOT/efo#1551]
For new term requests, please provide the following information:

## Preferred term label
FMI clinical data

## Synonyms
Foundation Medicine Inc. clinical data

## Textual definition
Clinical data for FMI genomic profiling data: a diverse array of cancers that underwent genomic profiling using FoundationOne.

## Suggested parent term
EFO:0004600

## Attribution
0000-0002-7059-6378

**Comment by paolaroncaglia** [comment]
Dear @gladkia ,

Thank you for contacting EFO with your term request for 'FMI clinical data' (synonym "Foundation Medicine Inc. clinical data", definition "Clinical data for FMI genomic profiling data: a diverse array of cancers that underwent genomic profiling using FoundationOne."). If your intent is to capture that a dataset contains clinical data, rather than e.g. genomic or transcriptomic data, I'd rather create a new term for 'clinical data' as a child of EFO:0004600 'data set'. If the clinical data produced by FMI has specific characteristics, a child of 'clinical data' could be also created, mentioning how it differs from its parent in the definition. If, instead, you wish to capture specific methodologies, assays or instruments that FMI uses to generate its clinical data and that are not yet represented by existing terms in EFO or other ontologies, please provide the necessary information and we could add those new terms in the appropriate branches of EFO. 

Thank you,

Paola Roncaglia, for the EFO editorial team

**Comment by gladkia** [comment]
Dear @paolaroncaglia thanks for the detailed answer and suggestions.

@paolaroncaglia , @zoependlington yes, my intention was to capture that a dataset contains clinical data.  Creating a new term for 'clinical data' as a child of EFO:0004600 'data set' will do the job. For now there is probably no need to create a 'FMI clinical data' entry, being a child of 'clinical data' entry.

**Comment by paolaroncaglia** [comment]
@gladkia thank you for your feedback. I'll create a new term for 'clinical data' as a child of EFO:0004600 'data set', and will add your ORCID (0000-0002-7059-6378). The term will be available at the next EFO release, scheduled for June 15th; I'll comment here when the ID is ready.
