### ISSUE TITLE
EVA - EFO import

### ISSUE THREAD

**Issue by hannah-mclaren** [EBISPOT/efo#168]
Draft new terms for importing to EFO are in the 'EFOimport' tab of the following sheet:
https://docs.google.com/spreadsheets/d/1wClVV3_wL_xJv6RB7yJYA5WlLvh0NzQGP_Pa4uEMUqY/edit?usp=sharing

Opening this issue ahead of submitting Webulous templates to get a second opinion on the parent terms. Most important are those highlighted in RED (these are high frequency >10 in clinVar). There are 9 terms i cannot find a parent for in EFO and most of these we did not import in the last submission either:

thyroxine-binding globulin quantitative trait locus
blood group--lutheran inhibitor
tyrosine kinase inhibitor response
deoxygalactonojirimycin response
prednisolone response
warfarin response
ivacaftor response - efficacy

I am away next week so aim to submit webulous templates after 4th June.

Other issues:

- Add synonym **muscular dystrophy-dystroglycanopathy** to 
Congenital muscular dystrophy due to dystroglycanopathy [Orphanet:370953]

- Can I have your opinion on whether to map **mental retardation, autosomal dominant 52** to mental retardation [EFO:0003847] or whether we should import a new term under EFO:0003847?
There are a few of these autosomal dominant types.

**Comment by zoependlington** [comment]
I have made a copy of your spreadsheet and completed some of the missing information which can be found here:

https://docs.google.com/spreadsheets/d/1ySfKKPvX-QR1GeKU8n0SAXrx3i4A9Ft3_92flA-Ek5Y/edit?usp=sharing

Any purple indicates changes to parent classification, bright yellow indicates any terms that did not have parent classification in the original spreadsheet and orange indicates terms that still do not have good classification. Pale yellow indicates that there are some notes written that sound be taken into account - typically in red. These are either notes to self or questions.

## For the terms we didn't import last time:

- **thyroxine-binding globulin quantitative trait locus**
     - Unsure of how to classify this as of yet, we currently do not have terms like this in EFO.
     - Will continue to look into this!

- **blood group--lutheran inhibitor**
     - We may need to add a branch for blood group into EFO to accommodate this term as, currently, it would not sit well under any of our existing terminology.
     - Will continue to look into this!

- **tyrosine kinase inhibitor response**
     - **Suggested label:** response to tyrosine kinase inhibitor
     - Subclass of response to drug

- **deoxygalactonojirimycin response**
     - **Suggested label:** response to deoxygalactonojirimycin
     - Subclass of response to drug
     - **Synonym:** migalastat response || response to migalastat

- **prednisolone response**
     - **Suggested label:** response to prednisolone
     - Subclass of response to glucocorticoid

- **warfarin response**
     - **Suggested label:** response to warfarin
     - Subclass of response to anticoagulant

- **ivacaftor response - efficacy**
     - **Suggested label:** response to ivacaftor - efficacy
     - Subclass of response to drug

## Edits to be made:

- [ ] **EFO:EDIT** Congenital muscular dystrophy due to dystroglycanopathy (Orphanet:370953)
     - **Synonym:** muscular dystrophy-dystroglycanopathy

## And finally, to answer your question:

I would create new terms under mental retardation (EFO:0003847) as they are different variants. They could also be added as subclasses of autosomal dominant non-syndromic intellectual disability (or autosomal recessive non-syndromic intellectual disability should there be any recessive types) alongside being subclasses of mental retardation.

This would reflect the DOID classification:

 https://www.ebi.ac.uk/ols/ontologies/doid/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FDOID_0080231

**Comment by hannah-mclaren** [comment]
Webulous templates ready for review and import under:
https://drive.google.com/drive/folders/1Nhlqhw2bpMPdEkyAJRk1sky7Gs4mIVl4?usp=sharing

Outstanding issues:

1. Poor classification for the following terms. Do we import or exclude?

- **thyroxine-binding globulin quantitative trait locus** 
- **blood group--lutheran inhibitor**

2. Review **EFO import phenotypes 05-06-2018**

3. Review **EFO import disease 05-06-2018**

4. Review **HP import 05-06-2018**

5. I found **glycogen storage disease ii, adult form** is a synonym of obsolete class [Orphanet:308604]  which is replaced by EFO term **Rare inborn errors of metabolism**[Orphanet:68367]. Should we still go ahead with importing a new term for **glycogen storage disease ii, adult form** or should we exclude and EVA can map it appropriately on the next round of curation (since we have already submitted to OT)?

**Comment by zoependlington** [comment]
Thanks Hannah! I've reviewed and imported all the templates into EFO.

I've also imported thyroxine-binding globulin quantitative trait locus and blood group--lutheran inhibitor under the classes already agreed - the classification is correct just not overly specific. But I'll make a note to review these.

In EFO, Orphanet:308604 isn't obsolete and does have synonyms indicating GSD2 adult form, so I added "glycogen storage disease ii, adult form" as a synonym for EVA mapping and will make a note to review this when I return from holiday.
