### ISSUE TITLE
Refactor arthritis classification away from asserted autoimmune disease

### ISSUE THREAD

**Issue by siiraa** [EBISPOT/efo#17]
We currently assert all forms of arthritis under 'autoimmune disease' when actually only rheumatoid arthritis should be in that category. We should remove the asserted parent for autoimmune disease and axiomatise AD and RA to get the correct inferred classification.

**Comment by simonjupp** [comment]
[] Remove arthritis as subclass of autoimmune disease

[] assert rheumatoid arthritis as a subclass of autoimmune disease

[] check siblings of rheumatoid arthritis that are also autoimmune diseases and assert these as subclasses of autoimmune disease.

**Comment by paolaroncaglia** [comment]
In addition to Simon’s plan above,

- [ ] Classify ’reactive arthritis’ ("An arthritis that is an autoimmune disease which develops due to an infection located elsewhere in the body.”) under ‘autoimmune disease’

- [ ] Correct typo in definition of ‘gout’ (“metabolic disorder characterized by recurrent acute arthritis, hyperuricemia and deposition of sodium urate in and around the joints, sometimes with formation of uric acid calculi. Gout his partly genetic.” should be “…Gout is partly…”)
