### ISSUE TITLE
Illumina NextSeq 500

### ISSUE THREAD

**Issue by hewgreen** [EBISPOT/efo#174]
For new term requests, please provide the following information:

## Preferred term label

Illumina NextSeq 500

## Synonyms

None

## Textual definition

a specific type of Illumina NextSeq.

## Suggested parent term

Illumina NextSeq

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by paolaroncaglia** [comment]
@daniwelter 
Could you please advice on whether the requested new term ‘Illumina NextSeq 500’ should be a child or a sibling of EFO:0008566 ‘Illumina NextSeq’? I’d have said a child, as @hewgreen suggested, but I’m having second thoughts because the definition of EFO:0008566 ‘Illumina NextSeq’ reads “The Illumina NextSeq 550 is a benchtop…”.
Thanks in advance for your feedback.
(Note for editor: I suspect that "It's primary applications" in the definition above should be changed into "Its...".)
