### ISSUE TITLE
New Robot form request for Lee IH PMID 36482414

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1924]
Robot form request for plasma metabolite terms. 
I've mentioned blood plasma in the definition, if that's okay. 
I've also added a synonym column and there are four columns at the end which contain source codes for HMDB, KEGG, LM and/or T3DB. These are from ST1 and ST6. 
https://docs.google.com/spreadsheets/d/1dk_whJPpX31ee5H5yEnGO2fPHMRn_L8o4t0O5Ous1PQ/edit?usp=sharing

Any problems, please let me know

**Comment by ar-ibrahim** [comment]
Hey Lizzy @earlEBI :) The following terms are already in EFO.  I'll add these exact synonyms to the existing terms. If you have any comments please let me know. 


Term   requested | Database x-ref | Notes
-- | -- | --
malic   acid measurement | HMDB0000156\|\|KEGG   COMPOUND:C00149 | EFO:0021622 (L-Malic acid measurement, exact synonym)
octanoate   measurement | HMDB0000482\|\|HMDB0304443 | EFO:0021831   (caprylic acid measurement; exact synonym)
trehalose   measurement | HMDB0000975\|\|KEGG   COMPOUND:C01083 | EFO:0021592   (D-trehalose measurement; exact synonym)
ureidopropionate   measurement | HMDB0000026\|\|KEGG   COMPOUND:C02642 | EFO:0010641   (3-ureidopropionate measurement; exact synonym)
hydroxylysine   measurement | HMDB0000450\|\|KEGG   COMPOUND:C16741 | EFO:0800002   (5-hydroxylysine measurement; exact synonym)
mercuric   chloride measurement | KEGG   COMPOUND:C13377 | EFO:0022068   (mercuric chloride measurement)



</body>

</html>

**Comment by ar-ibrahim** [comment]
Hey Lizzy @earlEBI. I added the [new EFO metabolite terms](https://docs.google.com/spreadsheets/d/1dk_whJPpX31ee5H5yEnGO2fPHMRn_L8o4t0O5Ous1PQ/edit#gid=517817626) which will be available after the June (15th) release. Will keep you updated about the lipid terms.

**Comment by udp** [comment]
@ar-ibrahim Hmmm! They should probably go into OBA yes - but it looks like only 6 of them map to SwissLipids:

https://www.swisslipids.org/#/mapper?from=LipidMaps&to=SwissLipids&ids=LMST03020024,LMST03020077,LMGP01050003,LMGP06070001,LMGP06050026,LMGL02070009,LMGL02030030,LMGP03050001,LMGP03020093,LMGP03020068,LMFA13010006,LMFA08010015,LMSP01080062,LMST01031126,LMFA07050145,LMFA01050081,LMFA01040028,LMFA08010010,LMPK12010207,LMFA08040010,LMSP00000010,LMSP03020075,LMSP00000003,LMFA00000004,LMFA08040049,LMFA08020078,LMSP01080013

<img width="988" alt="Screenshot 2023-06-01 at 19 59 58" src="https://github.com/EBISPOT/efo/assets/454895/98eb9cb5-6443-4345-9cb7-618dc1b44106">

I haven't tried to map them to ChEBI (the mapping tool didn't work) so maybe we will get some results there. But maybe we will need an import for lipidmaps into OBA as well as swisslipids.

Tagging https://github.com/obophenotype/bio-attribute-ontology/issues/242

**Comment by earlEBI** [comment]
Hi, could I just check if these lipid terms are still in progress? Please let me know when I can add to the GWAS Catalog.

**Comment by rays22** [comment]
I have updated the [gsheet](https://docs.google.com/spreadsheets/d/1dk_whJPpX31ee5H5yEnGO2fPHMRn_L8o4t0O5Ous1PQ/edit#gid=1910755053) so that the OBA trait IDs can be looked up for the lipid-related EFO terms requested in this ticket.
@ar-ibrahim , could you kindly check if these OBA trait terms have been imported into EFO.

ID | LABEL | REQUESTED LABEL
-- | -- | --
OBA:2045054 | level of 25-hydroxycholesterol in blood serum | 25-hydroxycholesterol measurement
OBA:2045037 | level of (5Z,7E)-(3S)-26,26,26-trifluoro-27-nor-9,10-seco-5,7,10(19)-cholestatriene-3,25-diol in blood serum | (5z7e)-(3s)-262626-trifluoro-27-nor-910-seco-5710(19)-cholestatriene-325-diol measurement
OBA:1000312 | vitamin D metabolic process quality | (5z7e)-(3s)-262626272727-hexafluoro-910-seco-5710(19)16-cholestatetraen-23-yne-325-diol measurement
OBA:2045046 | level of PC(19:3(10Z,13Z,16Z)/0:0) in blood serum | 1-(10z13z16z-nonadecatrienoyl)-sn-glycero-3-phosphocholine measurement
OBA:2045060 | level of 1-O-(1Z-eicosenyl)-sn-glycero-3-phospho-1D-myo-inositol in blood serum | 1-(1z-eicosenyl)-glycero-3-phospho-(1-myo-inositol) measurement
OBA:2045059 | level of 1-(5Z,8Z,11Z,14Z,17Z-eicosapentaenoyl)-sn-glycero-3-phospho-1D-myo-inositol in blood serum | 1-(5z8z11z14z17z-eicosapentaenoyl)-glycero-3-phospho-(1-myo-inositol) measurement
OBA:2045038 | level of 1-(8-[3]-ladderane-octanoyl)-2-(8-[3]-ladderane-octanyl)-sn-glycerol in blood serum | 1-(8-3-ladderane-octanoyl-2-(8-3-ladderane-octanyl)-sn-glycerol measurement
OBA:2045052 | level of dialkylglycerol in blood serum | 1-(8-5-ladderane-octanyl)-2-(8-3-ladderane-octanyl)-sn-glycerol measurement
OBA:2045055 | level of 1-O-oleoyl-sn-glycero-3-phosphoserine in blood serum | 1-(9z-octadecenoyl)-sn-glycero-3-phosphoserine measurement
OBA:2045047 | level of PS(O-20:0/22:6(4Z,7Z,10Z,13Z,16Z,19Z)) in blood serum | 1-eicosyl-2-(4z7z10z13z16z19z-docosahexaenoyl)-glycero-3-phosphoserine measurement
OBA:2045045 | level of PS(O-20:0/22:4(7Z,10Z,13Z,16Z)) in blood serum | 1-eicosyl-2-(7z10z13z16z-docosatetraenoyl)-glycero-3-phosphoserine measurement
OBA:2045041 | level of 1-O-alpha-D-Glucopyranosyl-1,2-nonadecandiol in blood serum | 1-o-alpha-d-glucopyranosyl-12-nonadecandiol measurement
OBA:2045053 | level of 12-aminododecanoic acid in blood serum | 12-aminolauramide measurement
OBA:2045049 | level of Sphingofungin B in blood serum | 2s-amino-3r4r5s14r-tetrahydroxyeicos-6e-enoic acid measurement
OBA:2045039 | level of campesterol 3-beta-D-glucoside in blood serum | 3-o-(beta-d-glucopyranosyl)-campest-5-en-3beta-ol measurement
OBA:2045056 | level of (E)-isoheptadec-2-enoyl-CoA in blood serum | (E)-isoheptadec-2-enoyl-CoA measurement
OBA:2045051 | level of Ipurolic acid in blood serum | 311-dihydroxy-tetradecanoic acid measurement
OBA:2045048 | level of 5-hydroperoxy-7-[3,5-epidioxy-2-(2-octenyl)-cyclopentyl]-6-heptenoic acid in blood serum | 5-hydroperoxy-7-35-epidioxy-2-(2-octenyl)-cyclopentyl-6-heptenoic acid measurement
OBA:2045040 | level of palmitoleamide in blood serum | 9z-hexadecenamide measurement
OBA:VT0010487 | response to xenobiotic stimulus trait | cyanidin 35-diglucoside (66-malyl diester) measurement
OBA:2045058 | level of N-gondoylethanolamine in blood serum | n-(11z-eicosaenoyl)-ethanolamine measurement
OBA:2045029 | level of ceramide in blood serum | n-(15z-tetracosenoyl)-1-deoxysphing-4-enine measurement
OBA:2045057 | level of ceramide phosphoethanolamine in blood serum | n-(2-hydroxy-docosanoyl)-pentadecasphing-4-enine-1-phosphoethanolamine measurement
OBA:2045043 | level of N-(3E-hexadecenoyl)-deoxysphing-4-enine-1-sulfonate in blood serum | n-(3e-hexadecenoyl)-deoxysphing-4-enine-1-sulfonate measurement
OBA:2045050 | level of N-linolenoyl glutamine in blood serum | n-(9z12z15z-octadecatrienoyl)-glutamine measurement
OBA:2045042 | level of Margaroyl-EA in blood serum | N-(heptadecanoyl)-ethanolamine measurement
OBA:2045036 | level of N-stearoyltaurine in blood serum | n-octadecanoyl-taurine measurement
OBA:2045044 | level of (4E,8E,10E-d18:3)sphingosine in blood serum | sphinga-4e8e10e-trienine measurement
