### ISSUE TITLE
Roman characters for rare diseases/syndromes

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#194]
There are several types of Mucolipidosis, all in EFO I think.

The problem is that in the scientific literature, they are represented using roman numbers even in 2018.

e.g. Mucolipidosis type 2 => Mucolipidosis type II
https://europepmc.org/abstract/MED/29876240 

Can please add the roman character version for those.
This would apply to other diseases in EFO too like all the sialidosis related diseases too.

It's strange that we get almost no match from EPMC for all the rare diseases.

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by paolaroncaglia** [comment]
Note for self: all ‘mucolipidosis’ terms in EFO are in fact ORDO terms. It appears that ORDO has updated them since EFO imported them, and the current ORDO terms follow the ‘Roman numeral’ format (see http://www.orpha.net/ORDO/Orphanet_79212 and children). I will therefore edit the ORDO terms currently in EFO so that they look the same as in the source ontology:

- [ ] EFO Orphanet:576 ‘Mucolipidosis type 2’ should be the same as ORDO Orphanet:576 ‘Mucolipidosis type II’ (check definition citations).

- [ ] EFO Orphanet:577 ‘Mucolipidosis type 3’ should be the same as ORDO Orphanet:577 ‘Mucolipidosis type III’ (check definition citations).

- [ ] EFO Orphanet:578 ‘Mucolipidosis type 4’ should be the same as ORDO Orphanet:578 ‘Mucolipidosis type IV’ (check definition citations); current parentage may be retained, but the term should also be a subclass of ‘mucolipidosis’.

- [ ] As for the ’sialidosis’ terms in EFO, these are also ORDO terms, but the source ontology retains the non-Roman numerals in the term labels (but has Roman numerals in the definition of the parent term, ’Sialidosis’). If we change the ORDO labels in this case, then the rebuild (part of EFO 3 pipeline) might run into difficulties in this area when we un-merge and re-merge imported terms. So perhaps we should postpone the sialidosis edits to after the release of EFO 3. 
@simonjupp @zoependlington let me know if you have any comments on this.

@gkos-bio 
If there are other specific branches that you are concerned about re. Roman-vs-non-roman-numerals, please list them here.

**Comment by paolaroncaglia** [comment]
@gkos-bio 
@simonjupp 
@zoependlington 
I have edited the 'mucolipidosis' terms as above. The changes will be visible after the July EFO release.
At our meeting today, @zoependlington confirmed that it would be better to wait until after the EFO 3 release to fix the 'sialidosis' terms. For the same reason (i.e. keeping EFO and ORDO as much in synch as possible), MONDO xrefs should not be added to ORDO terms in EFO at the present stage. I will now unassign myself from this ticket, and put it in the 'backlog' queue. Thanks.

**Comment by paolaroncaglia** [comment]
@zoependlington 
Now that EFO 3 is released, could you please confirm that it's ok for me to edit labels of ORDO terms in EFO, and add MONDO xrefs? For details, please see thread above. Thanks!

**Comment by zoependlington** [comment]
@paolaroncaglia Yes, it's absolutely okay. You can edit them in EFO 2 and the changes will be imported into EFO 3. For the MONDO x-refs, could you check that they are mapped in https://github.com/EBISPOT/efo/blob/efo3/src/ontology/imports/mondo_efo_mappings.tsv? If not, please let me know and I'll sort that out.

**Comment by paolaroncaglia** [comment]
@zoependlington 
Yes, all (5) relevant MONDO x-refs are mapped in the tsv file. Thanks!

**Comment by paolaroncaglia** [comment]
To do:

- [ ] EFO Orphanet:812: change label from "Sialidosis type 1" to "sialidosis type I"; keep "Sialidosis type 1" as an exact synonym; add def "Sialidosis type 1 (ST-1) is a very rare lysosomal storage disease, and is the normosomatic form of sialidosis (see this term), characterized by gait abnormalities, progressive visual loss, bilateral macular cherry red spots and myoclonic epilepsy and ataxia, that usually presents in the second to third decade of life. [ Orphanet:812 ]"; add MONDO xref MONDO:0019346. 

[To be continued]
