### ISSUE TITLE
PURL IRIs have returned

### ISSUE THREAD

**Issue by bvarner-ebi** [EBISPOT/efo#2038]
#2011 should have fixed the EFO IRIs that were in the format of http://purl.obolibrary.org/obo/ instead of http://www.ebi.ac.uk/efo. The former have reappeared. 

For example, Protégé shows the IRI of EFO:0700014 ECCITE-seq as http://purl.obolibrary.org/obo/EFO_0700014 instead of http://www.ebi.ac.uk/efo/EFO_0700014, which should have been committed in #2011.

@zoependlington, @anitacaron, other than editing the IRIs in Protégé, is an additional change needed to make the edits persist?

**Comment by zoependlington** [comment]
I'll look into this

**Comment by zoependlington** [comment]
A PR made (my fault) overwrote a couple of PRs.
I have:
- Fixed the above terms with incorrect PURLs and added QC in place to flag if the incorrect EFO PURL is used again in the future.
- Re-added ONT PromethION 2 Solo but with the ID EFO_0700019 (I think the original was EFO_0700017, but that was then used)
- Re-added the temporary GWAS fix to prevent failing due to dangling terms.
