### ISSUE TITLE
EVA-EFO import 08/18

### ISSUE THREAD

**Issue by hannah-mclaren** [EBISPOT/efo#223]
EVA are in the process of curating for the latest OT release on 7th August. There are some potential new terms for import in the "EFO import" tab here:
https://docs.google.com/spreadsheets/d/1ghb7VB6AHMfYKGbIT4L894H9TsPlel7ujWLPUHkPMY4/edit?usp=sharing

Please can you review these ready for import? Unsure of some parent terms but will follow this up on 6th August when Im back in the office.

A couple of Synonyms to add:
Orphanet_2162: Holoprosencephaly Sequence
EFO:0000191: mucosa-associated lymphoma
Orphanet:805: tuberous sclerosis syndrome

**Comment by zoependlington** [comment]
Requested synonyms have been added. Still working on the spreadsheet terms.

**Comment by zoependlington** [comment]
I have started working on the spreadsheet here - I've highlighted changes/suggestions/notes. Let me know if you don't agree with any of the parent classes.

https://docs.google.com/spreadsheets/d/1VIiqePcLjsJNjb0aENxTECpmT7Dh98t6kB-49HLMnVY/edit?usp=sharing

**Comment by hannah-mclaren** [comment]
Webulous templates ready for review. 3 blank definitions still and unsure of parent term for fg syndrome.
https://drive.google.com/drive/folders/1lsyb-TdVSsLC4Kc5Gz3lsu_OrLVm4YsM?usp=sharing

**Comment by zoependlington** [comment]
Here are the new EFO IDs:
EFO_0009302 || amelogenesis imperfecta, type ij 
EFO_0009301 || dystonia 28, childhood-onset 
EFO_0009300 || neurodevelopmental disorder with or without hyperkinetic movements and seizures, autosomal dominant 
EFO_0009299 || marfan syndrome/loeys-dietz syndrome/familial thoracic aortic aneurysms and dissections
EFO_0009298 || hepatic failure, early-onset, and neurologic disorder due to cytochrome c oxidase deficiency
EFO_0009297 || fg syndrome
EFO_0009296 || mutyh-associated polyposis
EFO_0009295 || polyarteritis nodosa, childhoood-onset
