### ISSUE TITLE
New term request for modified version of STRT-seq

### ISSUE THREAD

**Issue by LuJiansen** [EBISPOT/efo#2251]
## Preferred term label

modified STRT-seq

## Synonyms

3' STRT-seq

## Textual definition

A modified version of STRT-seq developed by Fuchou Tang's lab as described in PMID: 28457750, which enriched the 3' end of transcripts and used UMI (unique molecular identifier) for quantification.

## Suggested parent term

STRT-seq (EFO:0008953)

**Comment by jychien** [comment]
Would be great to also have a corresponding `5' STRT-seq` so that both `3' STRT-seq` and `5' STRT-seq` both would be children under `STRT-seq` (EFO:0008953):

Preferred term label:
5' STRT-seq

Textual definition:
A plate based platform that targets the 5' end of transcripts using a barcoded template switching oligonucleotide.

**Comment by zoependlington** [comment]
Added as EFO_0022845 and EFO_0022846, which will be available after the October (15th) release.
