### ISSUE TITLE
 EFO:0000565 leukemia comment

### ISSUE THREAD

**Issue by cmungall** [EBISPOT/efo#235]
This has a comment: "This is potentially too broad as well as overlaps with lymphoma and should be obsoleted."

Do you still believe this to be the case? I think the classification of neoplasms of the lymphoid and hematopoietic system is difficult but I think obsoleting leukemia may be going too far?

Am planning on removing EFO-derived comment from MONDO

**Comment by zoependlington** [comment]
This was an old comment from when the term was imported. Since then we've used this term as an intermediate and so the comment no longer stands. However, we do need to review leukemia (and consequently lymphoma) synonyms to remove any synonyms that are not specific to the term or are covered by child terms.

We will also remove these comments from leukemia and lymphoma. Thanks for bringing it to our attention!
