### ISSUE TITLE
Document how to create a tag release of EFO 3

### ISSUE THREAD

**Issue by simonjupp** [EBISPOT/efo#263]
As part of normal EFO 2 release we also want to start releasing a tagged version of EFO 3 beat

**Comment by daniwelter** [comment]
We shouldn't insert EFO 3 into the normal EFO release but instead create a stand-alone EFO 3 beta release. In order to do this, do the following:
- merge the EFO3-dev branch into the EFO3 branch (clean up as necessary)
- run the release process as per specification
  - set the release version to 3.0-beta
- commit and push all the files to Github
- in the EFO Github repo under "Releases", click "Draft new release"
- change the `@target:` drop-down to point to the EFO3 branch
- enter v3.0.0-beta as the tag
- write appropriate release notes (be more verbose than the normal EFO release tag to make it clear to users that this isn't a standard EFO release!)
- attach the full EFO 3 file to the release via the "Attach binaries.." box as this file isn't committed into Github directly due to its size
-  click "Publish release"

**Comment by paolaroncaglia** [comment]
@simonjupp @zoependlington 
The current release notes say 
"EFO - Release Notes
ArrayExpress Experimental Factor Ontology version 2.100"
(https://github.com/EBISPOT/efo/blob/master/ExFactor%20Ontology%20release%20notes.txt)
I presume we may want to discard the "ArrayExpress" bit in the second line going forward.
