### ISSUE TITLE
Review spindle cell tumor

### ISSUE THREAD

**Issue by zoependlington** [EBISPOT/efo#288]
- [x] Should it have the synonym of hemangiopericytoma
- [x] Should it be a child of sarcoma given we have the term spindle cell sarcoma
- [x] Is it a duplicate of spindle cell sarcoma?
- [x] Should it be mapped to MONDO:0005094 (Brought up in https://github.com/monarch-initiative/mondo/issues/433) in EFO 3? Probably should be remapped to the term added here https://github.com/monarch-initiative/mondo/issues/453

**Comment by S2Ola** [comment]
- Spindle cell tumor and hemangiopericytoma are both types of sarcoma (tumor)
- Hemangiopericytoma is a type of sarcoma and so should be a child of sarcoma 
- It should be a child of sarcoma since its a type of sarcoma
- Its relates with sarcoma that originates from the pericytes in the walls of capillaries and may best map to MONDO_0005094

**Comment by zoependlington** [comment]
- [ ] Should be mapped to MONDO_0020664.
- [ ] Remove hemangiopericytoma as synonym.
