### ISSUE TITLE
Yersinia enterocolitica infections

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#290]
'Yersinia pseudotuberculosis infectious disease' is defined as well as 'Yersinia pseudotuberculosis'.

'Yersinia pseudotuberculosis infectious disease' should be classified under 'Yersinia infectious disease'

In the same way, there should be a term for 'Yersinia enterocolitica infections' for 'Yersinia enterocolitica'.
Same for 'Yersinia pestis'. 'Yersinia pestis infections' should probably be defined.

Thank you!

**Comment by paolaroncaglia** [comment]
Note for self/EFO editor:
To do:

- [ ] Edit EFO:1001245 ‘Yersinia infectious disease' to remove uppercase from the def and add MONDO definition_citation MONDO:0007023;

- [ ] Edit EFO:1001246 'Yersinia pseudotuberculosis infectious disease' to classify it as a subclass of EFO:1001245 ‘Yersinia infectious disease' instead of ‘bacterial disease’; remove uppercase from the def; add MONDO definition_citation MONDO:0007024;

- [ ] Create EFO:NEW ‘Yersinia enterocolitica infectious disease' as a subclass of 1001245 ‘Yersinia infectious disease'; def: “Infections with bacteria of the species Yersinia enterocolitica.”; alternative_term ‘Yersinia enterocolitica infection'; add MONDO definition_citation MONDO:0042370;

- [ ] Create EFO:NEW 'Yersinia pestis infectious disease' as a subclass of 1001245 ‘Yersinia infectious disease'; def: “Infections with bacteria of the species Yersinia pestis.”; alternative_terms 'Yersinia pestis infection' and ‘plague’; add MONDO definition_citation MONDO:0019095;

- [ ] Note down new EFO IDs in this ticket;

- [ ] Edit EFO-MONDO mapping files to reflect all of the above.
