### ISSUE TITLE
Phenotype terms missing from EFO

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#291]
Spasm and Necrosis are typical terms that are not defined in EFO in the phenotype branch,

**Comment by paolaroncaglia** [comment]
Notes for self/EFO editor re. 'spasm':

A spasm pertains to muscles; it is a sudden involuntary contraction of a muscle or a group of muscles (see https://en.wikipedia.org/wiki/Spasm and http://www.ontobee.org/ontology/NCIT?iri=http://purl.obolibrary.org/obo/NCIT_C50656). Therefore, I’d place such a term under EFO HP:0011804 ‘Abnormality of muscle physiology’ (“A functional abnormality of a skeletal muscle.”). We could import the HP term HP:0031988 ‘muscle spasm’, but not its ancestry to ‘Behavioral abnormality’; and we could add definition_citation NCIT:C50656 as well as Wikipedia, and fix the typo in the def of the HP term. In summary:

- [ ] Import HP:0031988 ‘muscle spasm’
Make it subclass of EFO HP:0011804 ‘Abnormality of muscle physiology’
Definition: “A sudden involuntary contraction of a muscle or group of muscles.”
Definition citations: NCIT:C50656, https://en.wikipedia.org/wiki/Spasm 
Synonym: spasm

- [ ] Feed back to HP that HP:0031988 ‘muscle spasm’ has a typo in its definition (http://www.ontobee.org/ontology/HP?iri=http://purl.obolibrary.org/obo/HP_0031988); also, in HP there’s an NBO:0000588 ‘spasm’, but I believe all spasms are muscle spasms, so perhaps merge or revise?

- [ ] Will address 'necrosis' next.

**Comment by paolaroncaglia** [comment]
Notes for self/EFO editor re. 'necrosis':

@gkos-bio asked for a _phenotype_ term, so the new term should represent the _necrotic phenotype at the tissue level_, rather than the cellular processes leading to necrotic cell death. HP doesn’t have a term of its own, but rather imported one from the Mouse pathology ontology, see http://www.ontobee.org/ontology/MPATH?iri=http://purl.obolibrary.org/obo/MPATH_4. We’d want a term suitable for humans too, and I believe we’d rather not import MPATH terms (I see only a few in EFO), so we should create an EFO term:

- [ ] Add EFO:NEW ‘necrosis’
Subclass of ‘phenotypic abnormality’
Definition: “The phenotypic observation that death has occurred in groups of cells or in one or more tissues due to external factors, such as infection, toxins, mechanical trauma, loss of blood supply and other injuries (e.g. corrosion or burning). At the cellular level, morphological changes following necrosis include a translucent cytoplasm, swelling of organelles, modifications of the nucleus and increased cell volume (oncosis), culminating in the disruption of the plasma membrane and subsequent loss of intracellular contents. Necrotic cells do not fragment into discrete corpses as their apoptotic counterparts do. Moreover, their nuclei remain intact and can aggregate and accumulate in necrotic tissues."
Definition citations: MPATH:4, https://en.wikipedia.org/wiki/Necrosis, PMID:20823910, PMID:18846107
Synonym: tissue necrosis

- [ ] Note EFO ID of new term here.

**Comment by paolaroncaglia** [comment]
@gkos-bio 
Here are your new terms:
HP:0031988 ‘muscle spasm’ (imported in EFO)
EFO:0009426 'necrosis'
They'll be visible in our next release scheduled for Dec. 17th.
