### ISSUE TITLE
Cancer progression terms

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#296]
There is a list of related terms to Cancer progression that are missing in EFO that you may want to consider:

Metastasis
Neoplasm Metastasis
Neoplasm Micrometastasis
Metastatic Neoplasm

**Comment by paolaroncaglia** [comment]
Note for self/EFO editor:
There's a term in EFO for 'Lymphatic Metastasis' defined as "Transfer of a neoplasm from its primary site to lymph nodes or to distant parts of the body by way of the lymphatic system." and referencing MSH:D008207. It's placed under 'neoplasm', which doesn't sound perfect, because neoplasm is the tumor mass itself while neoplasm metastasis is the process of transferring cells from one site to another. So we should
- [ ] Create a new term for 'neoplasm metastasis', referencing https://www.ncbi.nlm.nih.gov/mesh/68009362 and finding an appropriate parent
- [ ] Reposition the existing 'Lymphatic Metastasis' under it
- [ ] See if the existing EFO term 'metastasis to lymph node' ("A type of carcinoma which has spread to lymph nodes from some other primary cancer site") should be renamed 'lymph node metastatic carcinoma'

**Comment by paolaroncaglia** [comment]
@gkos-bio 
Could you please review my comment above and address my question when you have a chance? That would enable me to create/edit EFO terms for cancer progression in the most appropriate way. Thanks!

**Comment by gkos-bio** [comment]
Hi Paola,
I agree to create a new term for 'neoplasm metastasis' and place it under the appropriate parent (process).
'metastatic neoplasm' is already defined in MONDO and NCIt and should be classified under neoplasm.
http://purl.obolibrary.org/obo/NCIT_C3261
http://purl.obolibrary.org/obo/MONDO_0024883

Thanks.

**Comment by paolaroncaglia** [comment]
Hi @gkos-bio ,
FYI, for consistency with NCIT, I’ll label the top term ‘metastasis’ instead of ‘neoplasm metastasis’, but I’ll keep the latter as a synonym. Here’s the full lists of edits I will do:

- [ ] Add EFO:NEW metastasis
Subclass of pathological process
The spread or migration of cancer cells from one part of the body (where it first appeared) to another. The secondary tumor contains cells that are like those in the original (primary) tumor. [ NCI ]
Editor_comment: A tumor formed by cells that have spread is referred to as a "metastatic tumor" or a "metastasis", but, strictly speaking, “metastasis” refers to the process of cancer cell migration, not to the tumor mass itself. 
NCIT:C19151      
MSH:D009362                     
Synonyms: neoplasm metastasis, cancer metastasis, , tumor metastasis, tumor cell migration

- [ ] Edit the existing 'Lymphatic Metastasis' to make it subclass of ‘metastasis’ (instead of ‘neoplasm’)

- [ ] Add EFO:NEO metastatic neoplasm
Subclass of neoplasm
A neoplasm that has spread from its original (primary) site of growth to another site, close to or distant from the primary site. Metastatic growth is characteristic of advanced malignancies, but in rare instances can be seen in neoplasms lacking malignant morphology. [ NCI ]                                 
Editor_comment: A tumor formed by cells that have spread is referred to as a "metastatic tumor" or a "metastasis", but, strictly speaking, “metastasis” refers to the process of cancer cell migration, not to the tumor mass itself. 
NCIT:C3261
MONDO:0024883
Synonyms: metastatic disease, metastatic tumor

- [ ] Add MONDO_0024883 metastatic neoplasm to MONDO mapping files

- [ ] Add EFO:NEW micrometastasis
Subclass of metastatic neoplasm
Small number of cancer cells that have spread from a primary tumor to other parts of the body and are too few to be picked up in a screening or diagnostic test, and are identifiable only under a microscope. [ NCI ]      
Editor_comment: A tumor formed by cells that have spread is referred to as a "metastatic tumor" or a "metastasis", but, strictly speaking, “metastasis” refers to the process of cancer cell migration, not to the tumor mass itself. 
NCIT:C38486
Synonym: neoplasm micrometastasis

- [ ] Edit the existing ‘metastasis to lymph node’ to rename it 'lymph node metastatic carcinoma'
Keep ‘metastasis to lymph node’ as a synonym
Add editor_comment: A tumor formed by cells that have spread is referred to as a "metastatic tumor" or a "metastasis", but, strictly speaking, “metastasis” refers to the process of cancer cell migration, not to the tumor mass itself.

- [ ] Edit the existing terms metastatic melanoma, metastatic pancreatic neuroendocrine tumours, metastatic prostate cancer, metastatic colorectal cancer, leptomeningeal metastases to add the extra parent ‘metastatic neoplasm’

- [ ] Further edit the existing ‘leptomeningeal metastases’ to rename it ‘leptomeningeal metastasis’ for consistency (keep the original name as a synonym), and modify its definition to read like the NCIt one: “A malignant neoplasm that has spread from its original site of growth to the leptomeninges. [ NCI ]” (keep the original definition as an additional one).

**Comment by paolaroncaglia** [comment]
@gkos-bio 
All edits above are now done and will be visible after the March release. Thanks.
