### ISSUE TITLE
Hypoxemia/Hypoxia/Anoxia and related terms missing from EFO

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#297]
The following general terms are missing from EFO:
Hypoxemia
Hypoxia
Anoxia
Asphyxia

https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C3890

**Comment by paolaroncaglia** [comment]
As these are non-cancer terms, I’ll create new EFO terms referencing the NCIt ones rather than import the NCIt terms. However, the placement of the whole hypoxia branch is tricky. Hypoxia is a decrease in oxygen level, and as such is a phenotype (see ‘hypoxia’ in MP and ‘hypoxemia’ in HP) rather than a disease (but EFO has ‘brain hypoxia’ and ‘brain hypoxia-Ischemia’ under ‘brain disease’, and ‘fetal hypoxia’ under ‘hematological system disease’). As expected, MONDO doesn’t seem to have any of the terms in Gautier’s list, but it has ‘brain hypoxia - ischemia’ under brain disease, presumably inherited from EFO.
It would seem correct to create these EFO terms and place them in the phenotype branch, possibly under EFO HP:0002086 ‘Abnormality of the respiratory system’. 

@gkos-bio @simonjupp @zoependlington 
May I please have your feedback on 1) placement of new terms and 2) placement of existing ‘brain hypoxia’, ‘brain hypoxia-Ischemia’ and ‘fetal hypoxia’?

(Minor note for self: in the NCIt definition of ‘Asphyxia’, “hypercapnea” should read “hypercapnia” (= a condition of abnormally elevated carbon dioxide (CO2) levels in the blood).)

**Comment by paolaroncaglia** [comment]
At our EFO meeting today, we agreed to have hypoxia terms in the phenotype branch, and also move existing terms there (check 'fetal hypoxia' - it manifests in the blood but it's not a disease of the blood)

**Comment by paolaroncaglia** [comment]
- [ ] Add EFO:NEW ‘hypoxia’
Subclass of EFO HP:0002086 ‘Abnormality of the respiratory system’
“A decrease in the amount of oxygen in the body. Symptoms range from mild (impaired judgment, memory loss, impaired motor coordination) to severe (seizures and coma). [ NCI ]”
NCIT:C3890
MP:0005039

- [ ] Add EFO:NEW ‘anoxya’
Subclass of ‘hypoxia’
“Absence or reduction of oxygen in body tissue. [ NCI ]”
NCIT:C2876

- [ ] Add EFO:NEW ‘asphyxia’
Subclass of ‘hypoxia’
“A state of general hypoxia and hypercapnia (abnormally elevated carbon dioxide (CO2) levels in the blood), resulting in acidosis, which affects all tissues in the body. [ NCI ]”
NCIT:C50465

- [ ] Add EFO:NEW ‘hypoxemia’
Subclass of ‘hypoxia’
“A finding indicating decreased oxygen levels in the blood. [ NCI ]”
NCIT:C93047
HP:0012418
MP:0012549

- [ ] Copy IDs of new terms here

- [ ] Reclassify the following, pre-existing terms accordingly if appropriate:
‘brain hypoxia’ and ‘brain hypoxia-Ischemia’ (both are under ‘brain disease’ atm);
‘fetal hypoxia’(is under ‘hematological system disease’ atm) (also double-check definition and placement - it manifests in the blood but it's not a disease of the blood).

- [ ] Notify MONDO about replacement of EFO ‘brain hypoxia - ischemia’ (they have it under brain disease, presumably inherited from EFO.

**Comment by paolaroncaglia** [comment]
Reopening this ticket. Now that Mondo has deleted the link 
MONDO:0006685 brain hypoxia - ischemia is_a brain disease,
- [ ] We can do the same in EFO for EFO:1000846, so that the term will sit only in the phenotype branch as per our previous discussions.
