### ISSUE TITLE
vascular wound healing / neointima / abnormal vascular wound healing

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#305]
wound healing is defined in EFO in biological process.
vascular wound healing is missing and
abnormal vascular wound healing / neointima is missing too.

**Comment by paolaroncaglia** [comment]
Notes for self/EFO editor:

- [ ] Import GO:0061042 'vascular wound healing' 
Subclass of EFO GO 'wound healing'
Definition: "Blood vessel formation when new vessels emerge from the proliferation of pre-existing blood vessels and contribute to the series of events that restore integrity to damaged vasculature."

To be continued.

**Comment by paolaroncaglia** [comment]
@gkos-bio 
To avoid confusion, could you please clarify the exact label of the neointima-related term you'd like in EFO? Thanks.

**Comment by gkos-bio** [comment]
### Neointima formation 

'Neointima formation' is a term used frequently in the medical literature and many studies have been published to target genes and pathways to reduce it.

'Neointima formation' is a characteristic response of arteries to several form of injuries and resembles the wound healing process as it involves the sequential processes of inflammation, granulation, and remodeling.

It's surprising to see that this term has not been defined while 'neointima formation' is an intense field of research and is currently targeted.

### Related terms 

'neointimal proliferation' and 'adverse neointimal proliferation' are related terms.

'neointimal hyperplasia' (synonym 'artery neointimal hyperplastic lesion')
'neointimal hyperplasia after vascular injury'

'neointimal hyperplasia' (and synonyms) should be defined as a subclass of 'hyperplasia' in EFO3.

'Neointimal healing' would be a subclass of 'vascular wound healing'. Healing would happen after a stent implantation (for instance) with 'neointimal hyperplasia'.

I found the term 'healed neointimal rupture/erosion' and 'healed neointimal rupture or erosion' in the litterature too.

**Comment by paolaroncaglia** [comment]
@gkos-bio 
Thanks for your feedback. I’m not sure about how to define the fine line/discriminate between neointima formation and hyperplasia. Both are non-physiological processes; is there a quantitative or qualitative feature around which the formation becomes hyperplasia? Both require a non-physiological proliferation. So, to keep it simple, I think we could:
 
- [ ] Add EFO:NEW 'neointimal hyperplasia'
Subclass of 'hyperplasia' and of ‘abnormal vascular wound healing’
“A hyperplasia due to proliferation and migration of vascular smooth muscle cells primarily in the tunica intima. It may develop after percutaneous coronary interventions such as stenting or angioplasty, and involves platelet aggregation at site of injury, recruitment of inflammatory cells, proliferation and migration of vascular smooth muscle cells, and collagen deposition, resulting in the thickening of arterial walls and decreased arterial lumen space. The term neointima is used because the cells in the hyperplastic regions of the vascular wall have histological characteristics of both intima and normal artery cells.
Wikipedia:Neointimal_hyperplasia
Synonyms: ‘neointima formation’, 'neointimal proliferation', 'adverse neointimal proliferation', 'artery neointimal hyperplastic lesion', 'neointimal hyperplasia after vascular injury'

- [ ] As for ‘neointimal healing’: you suggested:
“ 'Neointimal healing' would be a subclass of 'vascular wound healing'. Healing would happen after a stent implantation (for instance) with 'neointimal hyperplasia'.”
To me this sounds like neointima formation/hyperplasia itself. Again it’s not a physiological process (so I’d have trouble placing it under the GO term 'vascular wound healing'). I think that healing is intended as a synonym of formation where the formation is not causing trouble, but is still due to a hyperplasia. So I’d suggest adding ‘neointimal healing’ as a synonym of EFO:NEW 'neointimal hyperplasia'. 

- [ ] As for 'healed neointimal rupture/erosion' and 'healed neointimal rupture or erosion', these are even trickier and their placement would partly depend on the terms above.

Thanks,
Paola

**Comment by gkos-bio** [comment]
@paolaroncaglia

I can't really answer the question about quantitative/qualitative discrimination of hyperplasia and neointima.

Please, go for the addition of   'neointimal hyperplasia' with its synonyms.
Let's add ‘neointimal healing’ as a synonym for the time being.

Thank you
Gautier

**Comment by paolaroncaglia** [comment]
I will
- [ ] Add EFO:NEW 'neointimal hyperplasia'
Subclass of 'hyperplasia' [not also of ‘abnormal vascular wound healing’, as I suggested originally, because ‘hyperplasia’ is a disease term in EFO while ‘abnormal vascular wound healing’ is a phenotype]
“A hyperplasia due to proliferation and migration of vascular smooth muscle cells primarily in the tunica intima. It may develop after percutaneous coronary interventions such as stenting or angioplasty, and involves platelet aggregation at site of injury, recruitment of inflammatory cells, proliferation and migration of vascular smooth muscle cells, and collagen deposition, resulting in the thickening of arterial walls and decreased arterial lumen space. The term neointima is used because the cells in the hyperplastic regions of the vascular wall have histological characteristics of both intima and normal artery cells.”
Wikipedia:Neointimal_hyperplasia
Synonyms: ‘neointima formation’, 'neointimal proliferation', 'adverse neointimal proliferation', 'artery neointimal hyperplastic lesion', 'neointimal hyperplasia after vascular injury', ‘neointimal healing’

**Comment by paolaroncaglia** [comment]
Hi @gkos-bio ,
The new term is EFO:0009652 neointimal hyperplasia. Thanks!
