### ISSUE TITLE
sensory perception of pain

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#307]
Can 'sensory perception of pain' (nociception) be added to the biological process branch of EFO, please?
This is a term frequently used in medical literature.

**Comment by S2Ola** [comment]
For self / EFO editor 
**EFO** : NEW 

- **term:** sensory perception of pain
- **subclass** of biological process (GO_0008150)
- **Definition:** The stimulus-response process involving the stimulation of peripheral pain-carrying nerve fibers (e.g., C-fibers, A-delta fibers) and the transmission of impulses along peripheral nerves of the central nervous system, where the stimulus is perceived as pain. (Taber's) [ NCI ]
- **Synonyms:** nociception

**Comment by paolaroncaglia** [comment]
Hi @S2Ola ,

There is an existing GO term that captures the same concept, see https://www.ebi.ac.uk/QuickGO/term/GO:0019233
I think that in a case like this the procedure would be to import the existing GO term rather than create a corresponding EFO one, but I'll ask @simonjupp and @zoependlington for confirmation: is GO one of the ontologies that EFO is happy to import from, like it does for e.g. Uberon, HP and ChEBI? 

Thanks,
Paola

**Comment by daniwelter** [comment]
@paolaroncaglia @S2Ola GO is one of the our import ontologies so if a suitable GO-BP term exists, please import it rather than minting a new EFO terms.

**Comment by S2Ola** [comment]
**New term** sensory perception of pain imported from GO 
**IRI:** http://purl.obolibrary.org/obo/GO_0019233
**term:** sensory perception of pain
