### ISSUE TITLE
7 cells lines derives from some embryonic stem cell

### ISSUE THREAD

**Issue by jahilton** [EBISPOT/efo#327]
We have suggestions for making relationships between 7 cell line terms and embryonic stem cell [CL:0002322]. 

These 5 currently have 'derives from some cell type', which could be replaced by the more information 'derives from some embryonic stem cell'
ES-D3 [EFO:0005910]
ZHBTc4-mESC [EFO:0005914]
WW6 [EFO:0005915]
ES-CJ7 [EFO:0005916]
H7-hESC [EFO:0005904]

These 2 could have the 'derives from some embryonic stem cell' relationship added
46C [EFO:0005484]
ES-E14TG2a [EFO:0006275]

**Comment by jahilton** [comment]
Amendments to some of the above terms, now including some 'organism_part' filling in...

ES-D3 [EFO:0005910]
should be derives_from some (embryonic stem cell [CL:0002322] and (part_of some (embryo [UBERON:0000922] and (part_of some 'Mus musculus'))))
evidence:https://www.atcc.org/products/all/CRL-1934.aspx

ZHBTc4-mESC [EFO:0005914]
should be derives_from some (embryonic stem cell [CL:0002322] and (part_of some (embryo [UBERON:0000922] and (part_of some 'Mus musculus'))))
evidence:http://genome.ucsc.edu/ENCODE/protocols/cell/mouse/ZhBTc4_Stam_protocol.pdf

WW6 [EFO:0005915]
should be derives_from some (embryonic stem cell [CL:0002322] and (part_of some (embryo [UBERON:0000922] and (part_of some 'Mus musculus'))))
evidence:https://www.ncbi.nlm.nih.gov/pubmed/7638196

ES-CJ7 [EFO:0005916]
should be derives_from some (embryonic stem cell [CL:0002322] and (part_of some (embryo [UBERON:0000922] and (part_of some 'Mus musculus'))))
evidence:http://genome.ucsc.edu/ENCODE/protocols/cell/mouse/ES-CJ7_Stam_protocol.pdf

H7-hESC [EFO:0005904]
should be derives_from some (embryonic stem cell [CL:0002322] and (part_of some (embryo [UBERON:0000922] and (part_of some 'Homo sapiens'))))
evidence:https://www.wicell.org/home/stem-cells/catalog-of-stem-cell-lines/wa07.cmsx?closable=true

46C [EFO:0005484] - no amendment from above
derives from some embryonic stem cell [CL:0002322]
evidence: https://www.ncbi.nlm.nih.gov/pubmed/12524553

ES-E14TG2a [EFO:0006275]
should be derives_from some (embryonic stem cell [CL:0002322] and (part_of some (embryo [UBERON:0000922] and (part_of some 'Mus musculus'))))
evidence:https://www.atcc.org/Products/All/CRL-1821.aspx?geo_country=us

**Comment by paolaroncaglia** [comment]
@jahilton 
Thanks. We'll do our best to include the above in the mid-January release.

**Comment by paolaroncaglia** [comment]
@jahilton 
All of the relationships that you suggested are already in EFO (except for ES-E14TG2a part_of embryo and part_of Mus musculus, which I just added and will be visible after Jan 15). Some of those relationships are visible in OLS, some are inherited from the parent term and may not be visible in OLS. I'm attaching a screenshot of Protege (our ontology editor tool) for the term ES-D3. If you have any question, please let us know. 
As for the evidences you listed, I added them in the appropriate format if they weren't present already. The only ones I did not include, because I'm not sure we'd want to reference pdf files and/or entries from commercial catalogs, are:

ZHBTc4-mESC [EFO:0005914]
evidence:http://genome.ucsc.edu/ENCODE/protocols/cell/mouse/ZhBTc4_Stam_protocol.pdf
(already has a PMID definition_citation)

ES-CJ7 [EFO:0005916]
evidence:http://genome.ucsc.edu/ENCODE/protocols/cell/mouse/ES-CJ7_Stam_protocol.pdf
(already has a PMID definition_citation)

H7-hESC [EFO:0005904]
evidence:https://www.wicell.org/home/stem-cells/catalog-of-stem-cell-lines/wa07.cmsx?closable=true
(already has a PMID definition_citation)

- [ ] I'll consult with my colleagues as to adding the links above or not.

Thanks,
Paola

**Comment by paolaroncaglia** [comment]
![screen shot 2019-01-10 at 09 13 20](https://user-images.githubusercontent.com/4982516/50956503-25143800-14bc-11e9-8bd1-aedac72bf951.png)

**Comment by paolaroncaglia** [comment]
Note for self:
At our internal meeting today, we resolved to 
- [ ] add the evidence links (as database_cross_references is my best bet)so they don't go lost. 
- [ ] Also, for this once, for ease of visualization we will add the requested relationships even if they are redundant.
