### ISSUE TITLE
Review EFO:0007481 septicemic plague

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#382]
Stemming from a GWAS user query.
The parentage of EFO:0007481 septicemic plague needs to be reviewed. At a quick glance and considering the definition and placement of the matching MONDO entry (MONDO:0005956 septicemic plague), it looks like the term may be more appropriately placed as a child of EFO:0005803 hematologic disease. This needs to be confirmed also by looking at EXO term cross-references.

**Comment by zoependlington** [comment]
"septicemic plague" currently has the definition axiom of "has_disease_location some (vasculature or (part_of some vasculature))" which is causing it to be classified as a child of cardiovascular disease. The DOID x-ref also is classified as a child of cardiovascular disease. The MeSH mapping is a broad mapping to plague.

I do agree with reclassifying as a child of hematologic disease, but we may need to edit the description to reflect this. Could also be classified as a bacterial disease (it is caused by Yersinia pestis I believe from a quick search, so could be child of Yersinia pestis infectious disease)?

**Comment by paolaroncaglia** [comment]
@zoependlington thanks for your comments. The Wikipedia entry (https://en.wikipedia.org/wiki/Septicemic_plague) supports the parentage to ‘hematologic disease’ and to ‘Yersinia pestis infectious disease’. I agree with editing the definition to reflect this. How about:

- [ ] Replacing the parents ‘cardiovascular disease’ with ‘hematologic disease’, and ‘bacterial disease’ with ‘Yersinia pestis infectious disease’;

- [ ] Editing the definition to read:
“A form of plague (i.e. infection from Yersinia pestis); an infection of the blood, most commonly spread by bites from infected fleas. Bacterial endotoxins may cause coagulation, which leads to formation of tiny clots throughout the body. Symptom include fever, chills, prostration, abdominal pain, shock and bleeding.”;
 
- [ ] Removing the synonym “Plague” (because that’s an alternative label of the parent term and may cause confusion in searches);

- [ ] Changing the disease location axiom from ‘vasculature’ to ‘blood’;

- [ ] Adding the definition_citation Wikipedia:Septicemic_plague.

Thanks.

**Comment by zoependlington** [comment]
@paolaroncaglia This all sounds good to me!
