### ISSUE TITLE
Updated efo.obo file

### ISSUE THREAD

**Issue by sigven** [EBISPOT/efo#502]
According to the [latest release notes](https://github.com/EBISPOT/efo/releases), the `efo.obo` file has not yet been generated. Do you have any updates regarding when the obo file will be released?

**Comment by zoependlington** [comment]
Thank you for your ticket. Due to the growing size of EFO, we are currently in the process of updating our pipeline to build the updated efo.obo version and hope to have it released soon. Apologies for the wait! I will update this ticket once the obo version had been built and added to our latest release.

**Comment by zoependlington** [comment]
@sigven Thank you for your patience! The latest version of the obo file is available as an attached asset of our [latest release](https://github.com/EBISPOT/efo/releases/tag/v3.8.0).

**Comment by sigven** [comment]
Dear @zoependlington, thank you so much for the response. Highly appreciated.

regards,
Sigve
