### ISSUE TITLE
phyllodes tumor clarification

### ISSUE THREAD

**Issue by cmungall** [EBISPOT/efo#51]
```
  is_a EFO:0000408 ! disease
   is_a EFO:0000616 ! neoplasm
    is_a EFO:0000311 ! cancer
     is_a EFO:0000313 ! carcinoma
      is_a EFO:0000305 ! breast carcinoma
       is_a EFO:0000653 ! phyllodes tumor ***
```

But your xref for phyllodes tumor is  NCIT:C2977, which is a generic form that subsumes the prostate form as well as the benign form. Thus both subsumption under 'breast' and 'carcinoma' is wrong for the NCIT interpretation

```
  is_a NCIT:C2991 ! Disease or Disorder
   is_a NCIT:C3262 ! Neoplasm
    is_a NCIT:C4741 ! Neoplasm by Morphology
     is_a NCIT:C6930 ! Mixed Neoplasm
      is_a NCIT:C3743 ! Fibroepithelial Neoplasm
       is_a NCIT:C2977 ! Phyllodes Tumor *** 
        is_a NCIT:C4274 ! Benign Phyllodes Tumor
         is_a NCIT:C5196 ! Benign Breast Phyllodes Tumor
         is_a NCIT:C5532 ! Benign Prostate Phyllodes Tumor
        is_a NCIT:C4275 ! Malignant Phyllodes Tumor
         is_a NCIT:C128165 ! Malignant Vulvar Phyllodes Tumor
         is_a NCIT:C4504 ! Malignant Breast Phyllodes Tumor
         is_a NCIT:C5531 ! Malignant Prostate Phyllodes Tumor
        is_a NCIT:C7503 ! Borderline Phyllodes Tumor
         is_a NCIT:C5316 ! Borderline Breast Phyllodes Tumor
        is_a NCIT:C7574 ! Prostate Phyllodes Tumor
         is_a NCIT:C5531 ! Malignant Prostate Phyllodes Tumor
         is_a NCIT:C5532 ! Benign Prostate Phyllodes Tumor
        is_a NCIT:C7575 ! Breast Phyllodes Tumor
         is_a NCIT:C4504 ! Malignant Breast Phyllodes Tumor
         is_a NCIT:C5196 ! Benign Breast Phyllodes Tumor
         is_a NCIT:C5316 ! Borderline Breast Phyllodes Tumor
```

How would you like EFO:0000653 to be mapped to mondo? We track NCIT for cancer, so if you have used this according to the name, then NCIT:C2977. Otherwise according to your graph it should be NCIT:C4504

**Comment by cmungall** [comment]
See discussion here: https://github.com/monarch-initiative/monarch-disease-ontology/issues/262

**Comment by simonjupp** [comment]
The classification in EFO is wrong. We should keep the term as the more general type and move from under breast carcinoma. We can also add a new term for the malignant breast form. 

- [ ] Move phyllodes tumor under neoplasm. Keep xrefs and definitions as they are. 

- [ ] Create a new term for "Malignant Breast Phyllodes Tumor" that is a subclass of  EFO:0000653 and has an xref to NCIT:C4504. Add a subclassOf has_disease_location some "mammary gland" so that it classifies as a breast neoplasm.

**Comment by cmungall** [comment]
This is consistent with how we have equivalenced  EFO:0000653 in MONDO

**Comment by twhetzel** [comment]
I'm not able to get "Malignant Breast Phyllodes Tumor" to classify under breast neoplasm following "Add a subclassOf has_disease_location some "mammary gland" so that it classifies as a breast neoplasm."

If I add "'breast neoplasm' and has_disease_location some (breast or (part_of some breast))" similar to the other terms, it classifies under breast neoplasm.

**Comment by twhetzel** [comment]
Due to issues with earlier commits, changes were rollled back and both items still need to be addressed.

- [ ] Move phyllodes tumor under neoplasm. Keep xrefs and definitions as they are.

- [ ] Create a new term for "Malignant Breast Phyllodes Tumor" that is a subclass of EFO:0000653 and has an xref to NCIT:C4504. Add a subclassOf has_disease_location some "mammary gland" so that it classifies as a breast neoplasm.

**Comment by paolaroncaglia** [comment]
Here's the ID of the new term: 
EFO_0008545 | Malignant Breast Phyllodes Tumor
