### ISSUE TITLE
ChEBI imports with extra definitions

### ISSUE THREAD

**Issue by sbreiff** [EBISPOT/efo#516]
Hello,

I've come across some EFO terms with multiple definitions - in some cases perhaps
this is by design, but there are at least a few cases where one of the definitions
doesn't make sense so I wanted to bring it to your attention. The ones I came across all
happen to be imported from ChEBI.

1. [CHEBI:100241](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_100241) - Ciprofloxacin - one of the definitions starts with "This gene
is involved in..." (the other is the ChEBI definition)
2. [CHEBI:16113](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_16113) - Cholesterol - has 3 definitions but one is about Cytochrome P450
3. [CHEBI:3347](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_3347) - Candesartan - one of the definitions refers to a chromosome band
4. [CHEBI:4027](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_4027) - Cyclophosphamide - one of the definitions refers to CXCL10 gene
5. [CHEBI:52717](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_52717) - Bortezomib - one of the definitions refers to USP6 gene

Aside from these, generally speaking, could you clarify whether terms sometimes
have multiple definitions by design, or whether this is accidental?

Thanks,
Sarah

**Comment by paolaroncaglia** [comment]
Hi @sbreiff ,

Thanks for contacting us! Yes, we are aware that some terms in EFO have multiple definitions. As you guessed, in most cases this is intentional, but a few cases are due to mistakes. We are already looking into this; we extracted a list of all terms with multiple definitions, sorted them by originating ontology, made a first pass at addressing the cause, and drafted plans to fix errors. This work in progress is documented here (you may not have access to some of our internal documents, but you are welcome to follow the ticket): https://github.com/EBISPOT/efo/issues/420
In most cases multiple definitions are not incorrect and are inherited from originating ontologies, which, in turn, may derive them from the resources they cross-reference to. (When EFO imports a term, by default it adopts all the basic annotation properties the term has in the originating ontology, unless EFO curators spot an obvious error.)       
Where a definition is incorrect, it’s not always straightforward to trace back the cause, e.g. if the wrong definition came from an originating ontology which has since updated its entry. Wrong definitions may also occasionally be due to a glitch in the import process, though EFO editors seek to double-check that.   
We have highlighted about a hundred CHEBI terms in EFO with multiple definitions, including the ones you listed. We’re planning to set up a dynamic import of CHEBI, which would have the added benefit of fixing those errors. We can’t provide a timeline for that yet, so if the cases you listed above are causing issues to you, please let us know and we will aim at fixing at least those manually.

Thanks, 

Paola
