### ISSUE TITLE
Panc1 should be probably pancreatic adenocarcinoma and not breast adenocarcinoma

### ISSUE THREAD

**Issue by gabdank** [EBISPOT/efo#517]
I think that http://www.ebi.ac.uk/efo/EFO_0002713 should be pancreatic adenocarcinoma rather than breast adenocarcinoma.

**Comment by paolaroncaglia** [comment]
@gabdank 
Thanks for spotting that. Yes, the definition citation points to 'human pancreas', and the Wikipedia entry (https://en.wikipedia.org/wiki/PANC-1) says "PANC-1 is a human pancreatic cancer cell line isolated from a pancreatic carcinoma of ductal cell origin.[1] PANC-1 was derived from the tissue of a 56-year-old male."
[1] = Lieber, Michael; et al. (15 May 1975). "Establishment of a continuous tumor‐cell line (PANC‐1) from a human carcinoma of the exocrine pancreas". International Journal of Cancer. 15 (5): 741–747. doi:10.1002/ijc.2910150505
Note for self/EFO editor:
- [ ] Delete subclass of breast adenocarcinoma cell line
- [ ] Add references and axioms based on the above.

**Comment by paolaroncaglia** [comment]
Other note for self/EFO editor:
The issue above is due to a broader one:
ductal adenocarcinoma being textually and logically defined as being breast ductal adenocarcinoma, but at the same time having the two children 'breast d. a." and "pancreatic d. a.". This broader issue affects all cell lines that are bearer of some pancreatic d. a. , so don't be surprised if you notice other pancreatic cell lines that connect to breast cancer while we fix this issue and the fix percolates to the next EFO release.

**Comment by paolaroncaglia** [comment]
Note for self: opened MONDO ticket so they can fix their xref and synonyms: https://github.com/monarch-initiative/mondo/issues/777
