### ISSUE TITLE
Duplicate entries for Meningioma

### ISSUE THREAD

**Issue by MichaelaEBI** [EBISPOT/efo#518]
These two EFO entries seem to be replicates for Meningioma:
[Orphanet:2495: Meningioma](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_2495)
[MONDO:0016642: meningioma (disease)](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0016642)

The Orphanet ID appears as a cross-reference on the page with the MONDO ID. It is also an HP term (HP:0002858) which is referenced in the MONDO entry, but not he Orphanet one. In Open Targets we currently use the [Orphanet ID](https://www.targetvalidation.org/disease/Orphanet_2495/associations).

**Comment by paolaroncaglia** [comment]
@MichaelaEBI 
Thanks for reporting this. The two terms indeed represent the same type of neoplasm. A few quick notes for self/EFO editor:
- [ ] Check if the Orphanet term and the MONDO term are mapped to each other in our MONDO mapping files
- [ ] Check parents (and/or disease locations) of the Orphanet term: 
Is 'endocrine neoplasm' really correct?
Is 'meningeal neoplasm' really the same as (and if so, mapped to) 'tumor of meninges' (see MONDO term)?
- [ ] If the terms become merged, keep in mind that the MONDO one has more xrefs, except for the 2 OMIM ones which need to be checked.

**Comment by paolaroncaglia** [comment]
On further analysis, EFO 'meningeal neoplasm' maps to Uberon 'meninx', while Mondo 'tumor of meninges' (textually defined as "A benign or malignant neoplasm that affects the meninges.", so equivalent to the EFO term) maps to Uberon 'meningeal cluster'. The EFO term is defined as "...involve the meningeal coverings of the brain and spinal cord", of which 'meninx' is only a generic one of the three layers that make up the meninges. Hence, the Mondo location axiom is more correct and we should replace the EFO one:
- [ ] Import Uberon 'meningeal cluster' in EFO
- [ ] Add location axioms EFO 'meningeal neoplasm' -> Uberon 'meningeal cluster' (instead of 'meninx')
- [ ] Add mapping: EFO 'meningeal neoplasm' -> Mondo 'tumor of meninges';
- [ ] Add mapping: EFO Orphanet 'Meningioma' -> Mondo 'meningioma (disease)';
- [ ] Run reasoner, look at inferred view of the branch and check for any issues.

**Comment by paolaroncaglia** [comment]
@MichaelaEBI 
This is now all done. Edits will be in the mid-February EFO release. Thanks for spotting that issue!
