### ISSUE TITLE
Disease term: Sphingolipidosis

### ISSUE THREAD

**Issue by Elysheba** [EBISPOT/efo#526]
Hi, 

I noticed that there might be something off in the hierarchical tree for the term "Sphingolipidosis" (Orphanet:79225). In the original Orphanet ontology, the term Orphanet:79225 has several child term among which "Orphanet:79204" (Lipid storage disease) (you can find it here: https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_79225)

But in the EFO hierarchical tree, Orphanet:79204 is a parent of Orphanet:79225 so I believe there might be an issue here? Not sure if it there any others out there, I'll check for this.

Thanks!
Liesbeth

**Comment by paolaroncaglia** [comment]
Hi @Elysheba ,

Thanks for your feedback. Yes, there is an inconsistency, but it's due to an error in ORDO; it was notified to them and fixed in EFO, but it's still incorrect in ORDO. See https://github.com/Orphanet/ORDO/issues/18 and https://github.com/EBISPOT/efo/issues/250#issuecomment-426964598. I will ask ORDO if they have any update. In the meantime, I will close this ticket, but please feel free to re-open or create a new one if you spot any error in EFO. Thanks!
