### ISSUE TITLE
cystic fibrosis associated meconium ileum

### ISSUE THREAD

**Issue by deniseOme** [EBISPOT/efo#609]
@paolaroncaglia @zoependlington, could you please check EFO:0004608 aka cystic fibrosis associated meconium ileum?

We believe it should be under TA 'pregnancy or perinatal disease' whereas in QA (Open Targets Platform Nov release, https://qa.targetvalidation.org/disease/EFO_0004608) it's 'under gastrointestinal system'. 

![Screen Shot 2019-11-07 at 14 27 39](https://user-images.githubusercontent.com/6472381/68397297-dfbba800-016a-11ea-9da5-3e77655919d9.png)

This may be unrelated to Orphanet issues captured in #322 as 'cystic fibrosis associated meconium ileum' is EFO, rather than ORDO.

(cc-ing @d0choa @smnorthen to be kept in the loop and comment if necessary)

**Comment by zoependlington** [comment]
Hi @deniseOme, we have a ticket regarding this term that @paolaroncaglia has been working on here: https://github.com/EBISPOT/efo/issues/553 (not sure if this is the same issue, but connecting them just in case).

**Comment by paolaroncaglia** [comment]
@deniseOme 
@d0choa
@smnorthen

EFO:0004608 'cystic fibrosis associated meconium ileum' is now a subclass of 'perinatal disease', based on its definition and as agreed/resolved earlier (see https://github.com/EBISPOT/efo/issues/553#issuecomment-547932572). However, you don't see that in your current files because EFO:0010238 'perinatal disease' was not yet created - I added it just now, as part of the pending bits we are still editing for Open targets. The relationship will be visible in OLS after the EFO release scheduled for Nov 18.

As for EFO:0004608 'cystic fibrosis associated meconium ileum' being a subclass of 'intestinal disease', that relationship is correct based on the term definition. As discussed with @d0choa and @smnorthen, we'd rather not remove relationships that are correct (and that should not create issues in Open Targets, hopefully). However, if there are strong reasons not to want 'cystic fibrosis associated meconium ileum' as a child of 'intestinal disease' as well as 'perinatal disease' in OT, we can force that, just let us know. 

Otherwise, I will move this ticket to our "Done" queue. Thanks!

**Comment by deniseOme** [comment]
Thanks @paolaroncaglia & @zoependlington for comments/links to other tickets.

As a non-expert in ontology or CF, I'd have had EFO:0004608 under both Orphanet_586 (cystic fibrosis) **and** EFO_0009431 (intestinal disease) as per Open Targets Platform Sep release..:

![Screen Shot 2019-11-08 at 14 30 42](https://user-images.githubusercontent.com/6472381/68484236-cb43e200-0234-11ea-98bb-629f029efc2f.png)

...rather than only under the latter TA. 

But perhaps one thing worth double checking is the actual name of the disease. Is it really "ileum"? We don't get any papers in our Bibliography section (from our NLP on PubMed abstracts using LINK) for this disease, which made me wonder whether the name is correct:

![Screen Shot 2019-11-08 at 14 38 21](https://user-images.githubusercontent.com/6472381/68484635-8ec4b600-0235-11ea-9d83-f545e5fc51dc.png)

It may actually be called "ileus":
* https://www.cysticfibrosisjournal.com/article/S1569-1993(17)30809-3/fulltext
* https://www.chop.edu/conditions-diseases/meconium-ileus
* https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3085752/

**Comment by d0choa** [comment]
@deniseOme the LINK problem in bibliography is in our side. We are in the process of re-running it with updated dictionaries, including EFO3. But it's not ready yet.

**Comment by d0choa** [comment]
@paolaroncaglia thanks for the solution. This should work for us

**Comment by paolaroncaglia** [comment]
@d0choa 
@deniseOme 
Thanks. I'm moving this ticket to Done then. (I assume you've discussed Denise's question offline, but just in case, 'cystic fibrosis associated meconium ileum' is not a type of 'cystic fibrosis', see https://github.com/EBISPOT/efo/issues/553.)
Have a good weekend,
Paola

**Comment by paolaroncaglia** [comment]
Reopening this ticket:
- [ ] Correct label of EFO:0004608 cystic fibrosis associated meconium ileum
Should be 'cystic fibrosis associated meconium ileus'
(thanks @deniseOme )
- [ ] Tell Mondo as they inherited the typo from EFO

**Comment by paolaroncaglia** [comment]
@deniseOme 
FYI, the label is now fixed. Thanks.

**Comment by deniseOme** [comment]
Thanks for fixing the label and the disease name.
