### ISSUE TITLE
Missing synonym for 'familial hypercholesterolemia'

### ISSUE THREAD

**Issue by MichaelaEBI** [EBISPOT/efo#648]
'[familial hypercholesterolemia](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0004911)' has the exact same term as synonym. 'familial hypercholesterolaemia' would be useful as a synonym especially since that spelling (with 'ae' rather than just 'e') is used in the description.

**Comment by paolaroncaglia** [comment]
@MichaelaEBI 
EFO:0004911 'familial hypercholesterolemia' has the synonym 'familial hypercholesterolemia' because that's the "preferred label" for Mondo and it got imported from them as an annotation. I agree that it's not ideal but I'm not sure if there's any easy way to fix. I'll make a note to 
- [ ] Discuss with group.
As for your synonym request, of course, I will
- [ ] Add 'familial hypercholesterolaemia' as a synonym to EFO:0004911 'familial hypercholesterolemia'. Thanks.

**Comment by paolaroncaglia** [comment]
@MichaelaEBI 
EFO:0004911 'familial hypercholesterolemia' now has the requested synonym 'familial hypercholesterolaemia'. It will be visible in the mid-March EFO release. Thanks.
