### ISSUE TITLE
NTR: MONDO:0010432 thrombophilia, X-linked, due to factor 9 defect

### ISSUE THREAD

**Issue by bmeldal** [EBISPOT/efo#654]
For new term requests, please provide the following information:

## Preferred term label
MONDO:0010432 thrombophilia, X-linked, due to factor 9 defect

## Synonyms
Thrombophilia, X-linked, due to factor IX defect [EXACT]

## Textual definition
A hemostatic disorder characterized by a tendency to thrombosis.

## Suggested parent term
EFO:0009315 thrombophilia

## Attribution
0000-0003-4062-6158

Please pull this term in from MONDO. I have asked them to add the definition from OMIM:300807.
https://github.com/monarch-initiative/mondo/issues/1032

Thanks,
Birgit

**Comment by paolaroncaglia** [comment]
@bmeldal 
The revisions you suggested for MONDO:0010432 'thrombophilia, X-linked, due to factor 9 defect' will likely be visible in the end-of-January Mondo release. I'll import the Mondo term in time for the mid-February EFO release. Also, you indicated your ORCID attribution in this EFO ticket, but it should ideally go to Mondo, and I'm not sure what the best annotation property would be to capture suggested edits rather than suggested new terms (I see that "creator" is often associated with ORCIDs n Mondo). @zoependlington , @nicolevasilevsky , could you advice please? Thanks!

**Comment by nicolevasilevsky** [comment]
I added Birgit's ORCID as a dbxref on the definition and the synonym she requested in Mondo. Perhaps you would would like to do it that way too?

see: https://github.com/monarch-initiative/mondo/issues/1032

**Comment by bmeldal** [comment]
I think I added my ORCID out of habit as MONDO asks for it and these request end up being double tickets. I'll leave it up to you how you attribute a change. I think GO add multiple GOIDs to attribute creators and later contributors...

I'll flag my tickets to check for updates after the relevant releases.

Thanks both!

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky thanks for your feedback.
@bmeldal I imported MONDO:0010432 'thrombophilia, X-linked, due to factor 9 defect', it will be visible in the mid-February EFO release. It will pull in your attribution from Mondo. Thanks.
