### ISSUE TITLE
Revise placement of EFO_0002687 ischemia reperfusion injury

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#657]
Pinging @smnorthen and @d0choa for their information (and comments if any):
EFO_0002687 ischemia reperfusion injury
is an (inferred) subclass of 'cardiomyopathy' in EFO (was subclass of 'cardiovascular disease', but we moved it during construction of the Open targets Therapeutic Areas slim/profile). However, based on its definition, PMID dbxref, and on https://en.wikipedia.org/wiki/Reperfusion_injury, I think that this term has a broader meaning, and that it would be placed more appropriately under 'injury' (not 'complication', because it can occur in a physiological context too, though that's observed in hybernating mammals rather than humans). I suggest to:
- [x] Remove the axiom "has_disease_location some myocardium" from EFO_0002687
- [x] Place it under 'injury'
- [x] Ask Mondo to move MONDO:0005203 'ischemia reperfusion injury' to be subclass of MONDO:0021178 'injury', rather than 'cardiovascular disease' (Mondo took 'ischemia reperfusion injury' from EFO and MeSH), otherwise EFO will keep inheriting the cardiovascular parent from Mondo. DONE, https://github.com/monarch-initiative/mondo/issues/1040

**Comment by d0choa** [comment]
Sounds like an improvement to me. Any comments @smnorthen?


On 13 December 2019 at 10:32:53, paolaroncaglia (notifications@github.com) wrote:

Pinging @smnorthen and @d0choa for their information (and comments if any):
EFO_0002687 ischemia reperfusion injury
is an (inferred) subclass of 'cardiomyopathy' in EFO (was subclass of 'cardiovascular disease', but we moved it during construction of the Open targets Therapeutic Areas slim/profile). However, based on its definition, PMID dbxref, and on https://en.wikipedia.org/wiki/Reperfusion_injury, I think that this term has a broader meaning, and that it would be placed more appropriately under 'injury' (not 'complication', because it can occur in a physiological context too, though that's observed in hybernating mammals rather than humans). I suggest to:

 Remove the axiom "has_disease_location some myocardium" from EFO_0002687
 Place it under 'injury'
 Ask Mondo to move MONDO:0005203 'ischemia reperfusion injury' to be subclass of MONDO:0021178 'injury', rather than 'cardiovascular disease' (Mondo took 'ischemia reperfusion injury' from EFO and MeSH), otherwise EFO will keep inheriting the cardiovascular parent from Mondo.

**Comment by smnorthen** [comment]
@d0choa and @paolaroncaglia 
Agree, I had a look and think it is best placed under injury

**Comment by paolaroncaglia** [comment]
Note for self: Mondo has done the change I requested; it'll be released soon; I can go ahead and edit EFO as outlined in https://github.com/EBISPOT/efo/issues/657#issue-537471684.

**Comment by paolaroncaglia** [comment]
Update/note for self: this ticket is still open as I need to double-check the edits, once the Mondo changes from their latest release are in OLS.

**Comment by paolaroncaglia** [comment]
Update: Mondo release isn't updated in OLS yet, so I'll leave this ticket in the "In progress" queue.

**Comment by paolaroncaglia** [comment]
Update: all is done and checked now for 'ischemia reperfusion injury', so I'll move this ticket to Done.

**Comment by smnorthen** [comment]
thank you! @paolaroncaglia
