### ISSUE TITLE
Orphanet_413 present in EFO but not in ORDO

### ISSUE THREAD

**Issue by AsierGonzalez** [EBISPOT/efo#670]
I have noticed that `Orphanet_413` seems to be part of EFO but not of ORDO, i.e., https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_413 exists but http://www.orpha.net/ORDO/Orphanet_413 doesn’t. Is this an expected behaviour? I thought that Orphanet terms were imported from ORDO.

**Comment by zoependlington** [comment]
Hi @AsierGonzalez, the Orphanet terms in EFO were imported a long time ago and have consequently not changed since import (they're static imports). We are gradually working through all imports to make them dynamic and update in accordance with the original domain ontology (see this epic ticket: https://github.com/EBISPOT/efo/issues/623). Therefore, there are some terms, like for example Orphanet_413, that have been edited/obsoleted/deleted in the domain ontology but not in EFO and therefore EFO is out of sync with these domain ontologies. Orphanet is a more complicated case which requires a more detailed plan to update, but we hope to update these terms as soon as possible. I hope this answers your question!

**Comment by AsierGonzalez** [comment]
I see, that makes sense.
According to the[ EFO 3.13.0 release notes](https://github.com/EBISPOT/efo/blob/v3.13.0/ExFactor%20Ontology%20release%20notes.txt#L4121) the used ORDO version is `2.0` which, [based on the information at the ORDO bioportal](https://bioportal.bioontology.org/ontologies/ORDO), seems to have been released in January 2015 whereas the latest is `2.9` from December 2019 and [the one available in OLS](https://www.ebi.ac.uk/ols/ontologies/ordo) is `2.8`, released in August 2019. Is that correct?

**Comment by zoependlington** [comment]
Yes, that's correct. Hyperlipoproteinemia type 4 (Orphanet_413) exists in ORDO 2.0, but not in the latest version which is available on OLS (I'm unsure when it was removed from Orphanet). EFO's import of Orphanet has not been updated (with potentially the exception of a few terms) since the terms were imported, the majority of which came from ORDO 2.0.

**Comment by AsierGonzalez** [comment]
Thank you for your help. This answers my question, so feel free to close the issue or keep it open until it is actually fixed, whatever is more convenient for you.

**Comment by zoependlington** [comment]
Thanks Asier! I'll move this to done since we have the epic still open. Please feel free to contact us again should you have any further questions!
