### ISSUE TITLE
Add term: Organophosphate poisoning

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#679]
## Preferred term label
Organophosphate poisoning

## Synonyms
Organophosphorus Poisoning
Organothiophosphate Poisoning
Organothiophosphate Poisonings

## Textual definition

see https://en.wikipedia.org/wiki/Organophosphate_poisoning

## Suggested parent term
Poisoning

## X-refs
https://www.ncbi.nlm.nih.gov/mesh/68062025

If you would like a nanoattribution, please indicate your ORCID id

**Comment by paolaroncaglia** [comment]
Note for self:
- [ ] Add EFO:NEW organophosphate poisoning
subclass of poisoning
"Poisoning due to organophosphates (a class of organophosphorus compounds (OPs) also known as phosphate esters, or OPEs). Organophosphates are used as insecticides, medications, and nerve agents. Symptoms include increased saliva and tear production, diarrhea, vomiting, small pupils, sweating, muscle tremors, and confusion."
dbxref: Wikipedia:Organophosphate_poisoning, MeSH:68062025
Synonyms: organophosphorus poisoning, organothiophosphate poisoning, organothiophosphate poisonings

**Comment by paolaroncaglia** [comment]
@gkos-bio 
organophosphate poisoning (EFO:0010581)
will be visible in the Feb 17th EFO release. Thanks.
