### ISSUE TITLE
Otitis media is linked to internal rather than middle ear in location axioms

### ISSUE THREAD

**Issue by cmungall** [EBISPOT/efo#68]
https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0004992

**Comment by paolaroncaglia** [comment]
@cmungall 
I'll fix this in time for the next EFO release, thanks for pointing it out.

**Comment by paolaroncaglia** [comment]
In MONDO, otitis media is_a middle ear disease
While in EFO, it has_disease_location some internal ear (and synonym: inner ear inflammation)
So I’d suggest

- [ ] import UBERON:0001756 middle ear

- [ ] modify axiom for EFO:0004992 otitis media:
from has_disease_location some internal ear
to has_disease_location some middle ear

- [ ] delete synonym for ‘inner ear inflammation’ in EFO:0004992 otitis media? or at least change synonym scope.

- [ ] MONDO can then delete their comment from MONDO:0005441 otitis media (disease) (“Editor note: EFO says inner ear in owl axioms but we restrict to middle”)

**Comment by paolaroncaglia** [comment]
@twhetzel 
Thank you very much for fixing that 'otitis' term.

@cmungall 
Now that this is done, I'll open a (low-priority) ticket on the MONDO tracker for you guys to delete the comment from MONDO:0005441.

**Comment by twhetzel** [comment]
Due to issues with earlier commits, changes were rolled back and this still needs to be addressed.
- [ ] import UBERON:0001756 middle ear

- [ ] modify axiom for EFO:0004992 otitis media:
from has_disease_location some internal ear
to has_disease_location some middle ear

- [ ] delete synonym for ‘inner ear inflammation’ in EFO:0004992 otitis media? or at least change synonym scope.

- [ ] MONDO can then delete their comment from MONDO:0005441 otitis media (disease) (“Editor note: EFO says inner ear in owl axioms but we restrict to middle”)

**Comment by paolaroncaglia** [comment]
All tasks have been addressed and changes are visible in the new EFO release. 
The request to delete the comment from the MONDO term is now in the MONDO tracker.
Therefore, I'm closing this ticket.
