### ISSUE TITLE
Add Term: Morton Neuroma

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#681]
For new term requests, please provide the following information:

## Preferred term label
Morton Neuroma
## Synonyms
interdigital Neuroma, Morton's Neuroma, Interdigital Nerve Scar

## Textual definition
See http://purl.obolibrary.org/obo/NCIT_C4075

## Suggested parent term
Neuroma

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by paolaroncaglia** [comment]
Note for self:
- [ ] Add EFO:NEW Morton Neuroma
subclass of neuroma
Def: "Swelling and inflammation of the nerve between the ends of the metatarsal bones at the base of the toes. It is caused by compression of the nerve, usually between the third and fourth toes. It results in a burning, sharp pain and numbness on the bottom of the foot in the area involved. Symptoms may resolve by resting the foot, taking anti-inflammatory drugs, applying ice packs, or injecting cortisone at the site. Persistent symptoms require surgical excision of the affected nerve. [def-source: NCI]"
Dbxref: NCIT:C4075
Synonyms: interdigital neuroma, Morton's neuroma, interdigital nerve scar

**Comment by paolaroncaglia** [comment]
@gkos-bio 
Morton Neuroma (EFO:0010582) will be visible in EFO's release scheduled for Feb 17th. Thanks.
