### ISSUE TITLE
UniProtKB 2020_01 release OMIM to EFO mappings

### ISSUE THREAD

**Issue by Yvonne-Lussi** [EBISPOT/efo#687]
Dear all,

We have a new release with OMIM terms that I have mapped to EFO. In cyan are the new term requests, and the ones not highlighted are OMIM IDs that can be mapped to existing EFO terms or MONDO/Orphanet terms that we'd like to see added to EFO. There is one term that was deleted at the bottom of the list. Please find the link to the google spreadsheet below.

https://docs.google.com/spreadsheets/d/10ZF9nQC0PUq4w99ZO_zgYOMROnuUW9AF5f0sVQ95ouk/edit?usp=sharing

Many thanks in advance and best regards,
Yvonne

**Comment by paolaroncaglia** [comment]
Note for self: this is in progress, see tab "Paola's working copy" (https://docs.google.com/spreadsheets/d/10ZF9nQC0PUq4w99ZO_zgYOMROnuUW9AF5f0sVQ95ouk/edit#gid=1182431942). Addressed (not committed) 18 OMIM diseases, 10 more to go.

**Comment by paolaroncaglia** [comment]
Note for self/update: I have reviewed all OMIM entries/mapping suggestions; the results are ready to implement and sorted by type of action item in https://docs.google.com/spreadsheets/d/10ZF9nQC0PUq4w99ZO_zgYOMROnuUW9AF5f0sVQ95ouk/edit#gid=1182431942. In summary, 6 new EFO terms to add, 2 Mondo terms to import, 15 OMIM IDs to be mapped to existing terms, and 1 EFO term to obsolete. (4 OMIM IDs are already mapped.)

**Comment by paolaroncaglia** [comment]
Note for self: contact OMIM people (see https://mondo.monarchinitiative.org/pages/contributors/) to ask for more details on removal of OMIM:618428 'Popov-Chang syndrome', and if there's any entry we should replace the EFO term with.

**Comment by paolaroncaglia** [comment]
Dear @jamberger and @ahamosh,
Could you please help with an OMIM query.
In the Experimental Factor Ontology (EFO) we have a term labelled 'Popov-Chang syndrome' and cross-referencing the OMIM entry OMIM:618428. It's been brought to our attention that OMIM removed that entry, but we can't find further information here https://omim.org/entry/618428. Could you please let us know if OMIM:618428 was replaced by another OMIM entry, or if it was deemed invalid/erroneous? So we can modify EFO accordingly. Thanks!
Paola Roncaglia

**Comment by jamberger** [comment]
Dear Paola,

This was an unusual case for OMIM.  The author of the paper underlying
the Popov-Chang syndrome phenotype contacted us and requested that we
reclassify the 5 heterozygous de novo variants in YWHAZ (601288) that 
had defined the Popov-Chang phenotype.  We have modified the REMOVED
entry so that a reader is directed to the YWHAZ gene for the
explanation.

Cordially,

Joanna Amberger


=========================================================================
Joanna S. Amberger		|	tel. 410-955-0313
Program Manager, OMIM
Johns Hopkins Hospital		|	fax  410-955-4999
McKusick-Nathans Institute 
Department of Genetic Medicine	|	e-mail joanna@peas.welch.jhu.edu
Blalock Bldg., Rm. 1007		|
Baltimore, MD  21287-4922	|
=========================================================================



On Thu, 5 Mar 2020, paolaroncaglia wrote:

> Dear @jamberger and @ahamosh,
> Could you please help with an OMIM query.
> In the Experimental Factor Ontology (EFO) we have a term labelled 'Popov-Chang syndrome' and cross-referencing the OMIM entry OMIM:618428. It's been brought to our attention that OMIM removed that entry, but we can't find further information here https://omim.org/entry/618428. Could you please let us know if OMIM:618428 was replaced by another OMIM entry, or if it was deemed invalid/erroneous? So we can modify EFO accordingly. Thanks!
> Paola Roncaglia
>
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/EBISPOT/efo/issues/687#issuecomment-595323892


=========================================================================
Joanna S. Amberger		|	tel. 410-955-0313
Johns Hopkins Hospital		|	fax  410-955-4999
McKusick-Nathans Institute for
 	Genetic Medicine	|	e-mail joanna@peas.welch.jhu.edu
Blalock Bldg., Rm. 1007		|
Baltimore, MD  21287-4922	|
=========================================================================

**Comment by paolaroncaglia** [comment]
@jamberger 
Dear Joanna,
Thank you very much for your prompt reply!
Best wishes,
Paola Roncaglia

**Comment by paolaroncaglia** [comment]
Dear @Yvonne-Lussi ,
All requested OMIM mappings are now in EFO, and will be in our next release, scheduled for March 16th. Please note that, due to the Data Center move, OLS will probably not be able to upload the new EFO version until servers are fully back on (possibly as late as early April). Thanks.

**Comment by Yvonne-Lussi** [comment]
Dear Paola
Thank you very much for the OMIM-EFO mappings of release 2020_01 and for creating the new EFO terms. I am currently working on the mappings for release 2020_02 and will let you know once I am finished.
Best wishes,
Yvonne
