### ISSUE TITLE
Add “primary hypertension” into EFO

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#70]
From an email from Denise:

“We have had a request from one of our Open Targets Platform users.
A child term of hypertension (EFO_0000537) is missing: primary hypertension, the most common type.
This is the MONDO ID for the missing term:
https://monarchinitiative.org/disease/MONDO%3A0001134
Its IRI is
http://purl.obolibrary.org/obo/MONDO_0001134”

(Gautier offered to take a look.)

We won’t import the MONDO term, but we will cross-reference it.

**Comment by paolaroncaglia** [comment]
@gkos-bio suggests:

"If you do that, could you please:
add secondary hypertension
add renal hypertension
reclassify renovascular hypertension under renal hypertension?"

Sure, we will look into that, thanks.

**Comment by paolaroncaglia** [comment]
Summing up, the plan is to:

- [ ] add EFO:NEW1 primary hypertension
is_a EFO_0000537 hypertension
definition: Hypertension that presents without an identifiable cause.
xref: MONDO:0001134 
synonyms: essential hypertension, idiopathic hypertension

- [ ] add EFO:NEW2 secondary hypertension
is_a EFO_0000537 hypertension
definition: High blood pressure caused by an underlying medical condition.
xref: MONDO:0001200

- [ ] add EFO:NEW3 renal hypertension
is_a EFO:NEW2 secondary hypertension
is_a EFO:0003086 kidney disease
definition: Hypertension caused by narrowing or occlusion of the renal arteries.
xref: MONDO:0001105

- [ ] modify axiom for EFO:1001153 renovascular hypertension:
from is_a hypertension
to is_a renal hypertension

**Comment by paolaroncaglia** [comment]
@twhetzel 
Many thanks for adding those hypertension terms. I'll add you as an assignee for documentation purposes.

**Comment by twhetzel** [comment]
Due to issues with earlier commits, changes were rolled back and these still need to be added:
- [ ] add EFO:NEW2 secondary hypertension
is_a EFO_0000537 hypertension
definition: High blood pressure caused by an underlying medical condition.
xref: MONDO:0001200

- [ ] add EFO:NEW3 renal hypertension
is_a EFO:NEW2 secondary hypertension
is_a EFO:0003086 kidney disease
definition: Hypertension caused by narrowing or occlusion of the renal arteries.
xref: MONDO:0001105

- [ ] modify axiom for EFO:1001153 renovascular hypertension:
from is_a hypertension
to is_a renal hypertension

**Comment by paolaroncaglia** [comment]
All tasks have been addressed and changes are visible in yesterday's release. Closing now.

**Comment by paolaroncaglia** [comment]
For reference, here are the EFO IDs for the new terms:
EFO:1002032 primary hypertension 
EFO:1002034 secondary hypertension 
EFO:1002039 renal hypertension
