### ISSUE TITLE
Version IRI on the OLS homepage not valid

### ISSUE THREAD

**Issue by FuqiX** [EBISPOT/efo#704]
Hi, 
I tried to access the EFO Version 3.14,0 using the link provided on the [OLS-EFO homepage](https://www.ebi.ac.uk/ols/ontologies/efo), 

http://www.ebi.ac.uk/efo/releases/3.14.0/efo.owl 

It returned _"404 The requested resource is not available."_  Could you please fix the link?

![EFO_homepage](https://user-images.githubusercontent.com/54043294/74142768-775ce680-4bf1-11ea-9926-7376e4ad16c8.jpg)
![404](https://user-images.githubusercontent.com/54043294/74142776-7a57d700-4bf1-11ea-8672-34ac036526db.jpg)

**Comment by paolaroncaglia** [comment]
@FuqiX 
Thanks for reporting this. While we address the issue on the OLS side (which may not be immediate I'm afraid), you should be able to download efo.owl from the "Download" link here: https://www.ebi.ac.uk/efo/
Please note that downloading will take a few moments as the file is quite large.
Thanks,
Paola

**Comment by paolaroncaglia** [comment]
@simonjupp @henrietteharmse 
Let me know if you'd like me to open a separate OLS ticket please.

**Comment by henrietteharmse** [comment]
@paolaroncaglia Yes, in general I think it is best to open a ticket on OLS if you suspect it is a OLS issue. This is simply because I am monitoring OLS and not EFO and I therefore might miss it.

In this case however I don't think it is an OLS issue. The IRI is indeed specified as follows in EFO:
`<owl:versionIRI rdf:resource="http://www.ebi.ac.uk/efo/releases/3.14.0/efo.owl"/>`

The problem I suspect is with the EFO release process that did not make EFO available at http://www.ebi.ac.uk/efo/releases/3.14.0/efo.owl.

**Comment by paolaroncaglia** [comment]
Thanks @henrietteharmse .
@zoependlington , would you be able to help please? Thanks!

**Comment by zoependlington** [comment]
@henrietteharmse the IRI on OLS should be http://www.ebi.ac.uk/efo/releases/v[VERSION NUMBER]/efo.owl (e.g. http://www.ebi.ac.uk/efo/releases/v3.14.0/efo.owl). This does direct to the correct version download. Is this something that needs changing on our end or on the OLS end?

**Comment by henrietteharmse** [comment]
@zoependlington 
OLS pulls this from the efo.owl file as-is. In EFO the owl:versionIRI needs to be corrected.

**Comment by zoependlington** [comment]
Thanks @henrietteharmse, I spotted the issue in our Makefile! Will update ASAP.
