### ISSUE TITLE
poisoning (unspecified)

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#72]
Many types of poisoning are defined in EFO, however, there is encompassing terms for poisoning like in MeSH or NCIT.

## Preferred term label

Poisoning

## Synonyms

None

## X-refs

MeSH D011041
NCIT C34933
UMLS C0032343

## Textual definition

Injury to the body or interference of normal body functions by a substance that is swallowed, inhaled, injected, or absorbed. [ NCI ] 

OR 

A condition or physical state produced by the ingestion, injection, inhalation of or exposure to a deleterious agent  [ MeSH ]

## Suggested parent term

it's classified under Injury in NCIT.
http://www.ebi.ac.uk/efo/EFO_0000546

It will work better because all poisoning terms in EFO are currently classified under disease:

So, heavy metal poisoning should move under poisoning (http://www.ebi.ac.uk/efo/EFO_1001518)

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by paolaroncaglia** [comment]
@gkos-bio 
Thanks, this will go in the March EFO release. Have a good weekend,
Paola

**Comment by paolaroncaglia** [comment]
@gkos-bio
Here’s a summary and comments for this request:

- [ ] Create new term:
EFO:NEW poisoning
Subclass of disease (see note below) (*)
Def: A condition or physical state produced by the ingestion, injection, inhalation of or exposure to a deleterious agent (**)
MSH definition citation: MSH:D011041
Xrefs: MeSH D011041, NCIT C34933, UMLS C0032343

- [ ] Edit existing term:
EFO:1001518 heavy metal poisoning
from Subclass of disease
to Subclass of poisoning

- [ ] Edit existing term:
EFO:1001291 ciguatera poisoning
add Subclass of poisoning

I would not, instead, place under ‘poisoning’ the following terms:
EFO:0005534 delayed encephalopathy after acute carbon monoxide poisoning (the focus is on the encephalopathy as a consequence of the poisoning)
EFO:0007168 berylliosis (has synonym ‘beryllium poisoning’, but the def. “A pneumoconiosis that involves allergic response located_in lungs caused by inhalation of beryllium compounds.” seems to involve more than the poisoning)
EFO:0007475 Salmonella gastroenteritis (has synonym ‘Salmonella Food Poisoning’ but there’s more to the term than the food poisoning)

(*) For the parentage of ‘poisoning’ in EFO, ‘disease’ seems more appropriate than ‘injury’ because the latter is defined as “Damage inflicted on the body as the direct or indirect result of an external *force*, with or without disruption of structural continuity.”. It has synonyms ‘wound’ and ‘trauma’, and children ’Spinal cord injury’ and ‘ankle injury’. ‘disease’, on the contrary, is generic enough to accommodate poisoning (“A disease is a disposition that describes states of disease associated with a particular sample and/or organism.”). Placing ‘poisoning’ under ‘disease’ would also be consistent with MONDO (MONDO doesn’t have a generic ‘poisoning’ term, but it has several terms such as ‘Lead poisoning’, ‘mercury poisoning’ etc. and they’re all classified in the ‘disease’ branch). It would also be consistent with definition and placement of ‘poisoning’ in MeSH. 

(**) If we go with the ‘disease’ placement, then the more disease-like definition of MeSH seems to fit better than NCIt’s.

Any concern please let me know. Thanks.

**Comment by paolaroncaglia** [comment]
Here's the ID of the new term: EFO_0008546 | poisoning
