### ISSUE TITLE
Add subclass to EFO_0003072 (SK-N-SH)

### ISSUE THREAD

**Issue by bonitalam** [EBISPOT/efo#739]
We would like to request SK-N-SH (https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0003072) to be a subclass of cancer cell line (EFO:0001639).

Cellosaurus has it listed as a cancer cell line.

https://web.expasy.org/cellosaurus/CVCL_0531

Thank you for your help!

**Comment by paolaroncaglia** [comment]
@bonitalam 
Thanks for pointing this out. 

Note for self and @zoependlington : this issue is related to the known classification issue in the neoplasm/cancer branch (https://github.com/EBISPOT/efo/issues/353). SK-N-SH is a subclass of neuroblastoma cell line, but neuroblastoma cell line isn't a child or descendant of cancer cell line. The missing links are due to the disease terms themselves. We need to figure out if neuroblastoma should be linked to cancer or not (it should, based on https://en.wikipedia.org/wiki/Neuroblastoma), and/or if cancer cell line should be axiomatised to neoplasm rather than cancer. These are quick thoughts and may need more work. Once the classification issue are fixed, more terms may reason to be subclasses of 'cancer cell line'.

@bonitalam For now, I will
- [ ] Add EFO:0005214 neuroblastoma cell line subclass of cancer cell line
(that will ensure that SK-N-SH, already a subclass of neuroblastoma cell line, is a descendant of cancer cell line).

**Comment by paolaroncaglia** [comment]
@bonitalam 
This is fixed now, and will be visible after the mid-April EFO release.

**Comment by bonitalam** [comment]
Great, thank you @paolaroncaglia!
