### ISSUE TITLE
Dementia - phenotype to disease move?

### ISSUE THREAD

**Issue by smnorthen** [EBISPOT/efo#764]
Dementia (an imported HP term: http://purl.obolibrary.org/obo/HP_0000726) is currently under the phenotype branch in EFO but I feel it would be better under the disease branch (where it is sitting in Mondo).
Would this be something that could be easily moved or would this be a more complicated structural problem?

**Comment by paolaroncaglia** [comment]
@smnorthen 
The issue of the phenotype-vs-disease duplication of 'dementia' came up before I'm afraid... (see https://github.com/EBISPOT/efo/issues/261) At the time, I think we resolved to keep the phenotype term. However, I'm willing to rectify an unsatisfactory situation.
The Mondo term for 'dementia' is equivalent to
cognitive disorder and (disease has major feature some Dementia) 
where Dementia is the HP term (you can see this in Ontobee, http://www.ontobee.org/ontology/MONDO?iri=http://purl.obolibrary.org/obo/MONDO_0001627). 
I'd suggest to
- [ ] Ask Mondo to re-label MONDO:0001627 from 'dementia' to 'dementia (disease)' 
- [ ] Import MONDO:0001627 in EFO
- [ ] Edit EFO:0002608 'AIDS dementia' (more soon)
- [ ] Edit EFO:0006792 'Lewy body dementia' (more soon)

Note, the HP term 'dementia' would remain in EFO, but the changes above should address any confusion. If this is an acceptable compromise for Open Targets, I'll go ahead. Thanks.

**Comment by smnorthen** [comment]
Thank you @paolaroncaglia. The proposed changes look acceptable for open targets.

**Comment by paolaroncaglia** [comment]
@zoependlington 

When you have time please: I need to import MONDO:0001627 'dementia (disease)' for https://github.com/EBISPOT/efo/issues/764#issuecomment-615331490, but it's in the mondo_blacklist.txt file. I suspect it was put there to avoid duplication with HP 'dementia', but the Mondo term has since been relabeled as 'dementia (disease)' to disambiguate. 
- [ ] Would it be safe to remove it from the exclusion file, or were there other reasons? Happy to remove it myself, but need to make sure first. Thanks.

- [ ] BTW, not urgent, but we should rename all "x_blacklist" files as "x_exclude" or similar. I'll leave that to you in case it affects the pipeline(s) and something needs to cange there too please? Thanks.

**Comment by zoependlington** [comment]
@paolaroncaglia I think it was just due to the duplication, so it should be safe to remove from that file.

I'll make a ticket to update the file names.

**Comment by paolaroncaglia** [comment]
@zoependlington brilliant, thanks!

**Comment by paolaroncaglia** [comment]
@zoependlington 
The remaining edits for this ticket (detailed in https://github.com/EBISPOT/efo/issues/764#issuecomment-615331490) require to liaise with GWAS. The higher-order work has been done (or required from Mondo), so I will now remove my assignment from this ticket. Thanks.

**Comment by zoependlington** [comment]
The remaining edits are now done. GWAS were happy for the changes to be made to these terms.

**Comment by paolaroncaglia** [comment]
Thanks @zoependlington !
