### ISSUE TITLE
UniProtKB 2020_03 release OMIM to EFO mappings

### ISSUE THREAD

**Issue by Antonialock** [EBISPOT/efo#768]
Hello,
We require a number of new mappings between OMIM and EFO. 
The attached spreadsheet contains 
- NTRs with sugggested parent terms
- Suggested exact mappings to orphanet or Mondo
- Suggested "broad mappings" (narrow synonyms) to EFO, orphanet or Mondo terms

Link here
https://docs.google.com/spreadsheets/d/12dqwxYSM8dDY00oZMopgqN6cejnnyB60Q_7FBWlIY5I/edit?usp=sharing

**Comment by paolaroncaglia** [comment]
Hi @Antonialock , nice to be in touch again!
Thanks for your request. I had a quick look at your spreadsheet, thanks for your work there. We will not be able to address the mappings straight away due to other priorities, but I hope to get them in EFO in time for our next release (scheduled for May 18th).

**Comment by Antonialock** [comment]
Thank you Paola, nice to see you too again! :-)

**Comment by paolaroncaglia** [comment]
Hi @Antonialock ,

All the OMIM mappings requested are now in EFO and will be visible in the release scheduled for later today. Note that Mondo recently updated their OMIM ingest (see https://github.com/monarch-initiative/mondo/issues/1283). Unfortunately, the OMIM entries weren’t yet available in Mondo when you opened this ticket… but they are now, so I imported all the relevant Mondo terms and you’ll now have exact mappings in EFO. Going forward, you should find most if not all OMIM entries you’ll need in Mondo, so you can simply send us a list of Mondo terms to import in EFO. If at some point you notice that you can’t find a significant portion of OMIM entries in Mondo, it’s probably time to ask Mondo that they refresh their OMIM ingest again.

This said, if you believe that any of your questions are still applicable (see https://docs.google.com/spreadsheets/d/12dqwxYSM8dDY00oZMopgqN6cejnnyB60Q_7FBWlIY5I/edit#gid=869698632, tab “Paola’s copy”, column ‘Antonia’s comments”), please open separate tickets in Mondo or EFO as necessary. But hopefully all is in place now that the mappings are exact.

Lastly, FYI, I opened a Mondo ticket asking them to fix capitalization of some of their terms (https://github.com/monarch-initiative/mondo/issues/1526).

Best wishes!

**Comment by Antonialock** [comment]
hi @paolaroncaglia 

Im sure I was told that EFO preferred to map broadly than create specific terms eg "Bone marrow failure syndrome", instead of "Bone marrow failure syndrome 6"
but last batch got mapped exactly?

Would you like me to request new MONDO terms (eg Bone marrow failure syndrome 6) instead of mapping to parent?

**Comment by paolaroncaglia** [comment]
Hi @Antonialock ,

> Im sure I was told that EFO preferred to map broadly than create specific terms eg "Bone marrow failure syndrome", instead of "Bone marrow failure syndrome 6"
> but last batch got mapped exactly?

That's correct: as a general rule EFO would prefer a broad mapping rather than inflating the ontology with very specific terms and especially if the differentia is unclear. This is not a hard and fast rule though. Exceptions would include e.g. a) if several siblings (specific) terms are already in EFO, then we might add another sibling; b) if Mondo has imported specific OMIM terms, then we'd import the Mondo terms themselves. (EFO being an application ontology, we're happy to import existing terms from other ontologies wherever possible rather than creating new EFO ones.) The last batch of UniProt's request (this ticket) got mapped exactly because Mondo had just done a fresh ingest of OMIM. In fact, there's a plan to improve the previous broad mappings where applicable (https://github.com/EBISPOT/efo/issues/754). 

> Would you like me to request new MONDO terms (eg Bone marrow failure syndrome 6) instead of mapping to parent?

As a general rule, if the OMIM ID you need is mapped exactly to a Mondo term, please open an EFO ticket requesting that EFO imports the Mondo term. In this specific case, I see that there is no 'Bone marrow failure syndrome 6' in Mondo. You may want to investigate (in OMIM and Mondo) why that is the case. Possible interpretations: the OMIM ID is new and was added after the last Mondo ingest; the OMIM ID is not deemed unique by Mondo (there's a comment in Mondo bone marrow failure syndrome "Genetic heterogeneity of OMIM 614675 includes 615715", not sure if that's relevant). If you can't find a resolution and would like the OMIM mapping to be in EFO, I'd add a broad mapping to the parent. 

Let me, or Mondo, know if you need any further help or clarification. And have a lovely day! :-)
