### ISSUE TITLE
American trypanosomiasis

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#79]
## Preferred term label

American trypanosomiasis

## Synonyms

Chagas disease
Chagas' Disease
human American trypanosomiasis
South American trypanosomiasis
Trypanosoma cruzi Infection

## Textual definition

American trypanosomiasis, commonly known as Chagas disease (ChD), is a tropical disease mainly found in latin America and transmitted by triatomine insects (mostly Triatoma infestans and Rhodnius prolixus and Panstrongylus megistus) harboring the hemoflagellate protozoan parasite Trypanosoma cruzi. The disease is characterized by an acute phase which is either asymptomatic or manifest with fever, inflammation at the inoculation site (inoculation chancre or chagoma), unilateral palpebral edema called the Romaña sign (when the triatomine bite occurs near the eye), enlarged lymph nodes, and splenomegaly. The chronic phase is lifelong and development of chagasic cardiomyopathy (30%; complex arrhythmias, heart failure, and thromboembolic events), digestive (10%; megaoesophagus and megacolon), neurological (10%; stroke, peripheral neuropathy and autonomic dysfunction), or mixed alterations (10%) may be observed. These can all lead to high morbidity and mortality rates. [ ORDO ]

A parasitic infection caused by Trypanosoma cruzi. It is transmitted by insect bites. It is characterized by an acute and chronic phase; in the acute phase patients may have fever, malaise, and swelling at the site of the insect bite. In the chronic phase patients develop hepatosplenomegaly, lymphadenopathy, cardiomyopathy and arrhythmias. [ NCI ]

## X-refs

Orphanet:3386
MSH:D014355
NCIT:C84629
ICD9:086.2
UMLS:C0007932
DOID:12140
KEGG:05142
UMLS:C0041234
ICD10:B57.1
ICD10:B57.4
ICD10:B57.5
ICD10:B57.2
MedDRA:10001935
ICD10:B57.3
ICD10:B57.0

## Suggested parent term

trypanosomiasis

There is also a relation that can be established with 'Chagas cardiomyopathy'

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
- [ ] Create new term:
EFO:NEW1 American trypanosomiasis
Subclass of trypanosomiasis 
Def: American trypanosomiasis, commonly known as Chagas disease (ChD), is a tropical disease mainly found in latin America and transmitted by triatomine insects (mostly Triatoma infestans and Rhodnius prolixus and Panstrongylus megistus) harboring the hemoflagellate protozoan parasite Trypanosoma cruzi. The disease is characterized by an acute phase which is either asymptomatic or manifest with fever, inflammation at the inoculation site (inoculation chancre or chagoma), unilateral palpebral edema called the Romaña sign (when the triatomine bite occurs near the eye), enlarged lymph nodes, and splenomegaly. The chronic phase is lifelong and development of chagasic cardiomyopathy (30%; complex arrhythmias, heart failure, and thromboembolic events), digestive (10%; megaoesophagus and megacolon), neurological (10%; stroke, peripheral neuropathy and autonomic dysfunction), or mixed alterations (10%) may be observed. These can all lead to high morbidity and mortality rates. [ ORDO ]
Def: A parasitic infection caused by Trypanosoma cruzi. It is transmitted by insect bites. It is characterized by an acute and chronic phase; in the acute phase patients may have fever, malaise, and swelling at the site of the insect bite. In the chronic phase patients develop hepatosplenomegaly, lymphadenopathy, cardiomyopathy and arrhythmias. [ NCI ]
X-refs: Orphanet:3386
MSH:D014355
NCIT:C84629
ICD9:086.2
UMLS:C0007932
DOID:12140
KEGG:05142
UMLS:C0041234
ICD10:B57.1
ICD10:B57.4
ICD10:B57.5
ICD10:B57.2
MedDRA:10001935
ICD10:B57.3
ICD10:B57.0
Synonyms: Chagas disease
Chagas' Disease
human American trypanosomiasis
South American trypanosomiasis
Trypanosoma cruzi Infection

**Comment by zoependlington** [comment]
Here is the ID for the new term:
EFO:0008559 | American trypanosomiasis

Still to complete:
- [ ] Establish relationship with Chagas cardiomyopathy (EFO:0005529)

**Comment by paolaroncaglia** [comment]
@zoependlington 
As mentioned previously, all looks good to me.
