### ISSUE TITLE
Staphylococcus Aureus Infection subtypes

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#80]
For new term requests, please provide the following information:

### Methicillin-Resistant Staphylococcus Aureus Infection
http://purl.obolibrary.org/obo/NCIT_C115248

### Methicillin-Resistant Staphylococcus Aureus Pneumonia
http://purl.obolibrary.org/obo/NCIT_C122523

### Methicillin-Susceptible Staphylococcus Aureus Infection
missing

### Vancomycin-Resistant Staphylococcus Aureus Infection
missing

### Methicillin-Resistant Staphylococcus Aureus Infection

MRSA infection
Infection, MRSA
infection by MRSA
MRSA
MRSA bacteremia
MRSA bacteremias
Methicillin-resistant Staphylococcus aureus (MRSA) infection
methicillin-resistant Staphylococcus aureus (MSSA) bacteremia

### Methicillin-Resistant Staphylococcus Aureus Pneumonia

Methicillin-Resistant Staphylococcus Aureus Pneumonia 
MRSA Pneumonia
Methicillin-Resistant Staphylococcus aureus Pneumonia

### Methicillin-Susceptible Staphylococcus Aureus Infection

MSSA
MSSA infection
MSSA bacteremia
MSSA bacteremias
infection by MSSA
Methicillin-susceptible Staphylococcus aureus (MSSA) infection
methicillin-susceptible S. aureus (MSSA) infection
methicillin-susceptible Staphylococcus aureus (MSSA) bacteremia

### Vancomycin-Resistant Staphylococcus Aureus Infection

VRSA
VRSA infection
VRSA bacteremia
VRSA bacteremias
infection by VRSA
vancomycin-resistant Staphylococcus aureus (VRSA)
Vancomycin-Resistant Staphylococcus aureus (VRSA) infection
Vancomycin-Resistant S. Aureus (VRSA) infection
Vancomycin-Resistant Staphylococcus aureus (VRSA) bacteremia
slow-intermediate vancomycin-resistant S. aureus (sVISA)

### Methicillin-Resistant Staphylococcus Aureus Infection

A bacterial infection that is caused by Staphylococcus aureus and is resistant to methicillin treatment. [ NCI ]

### Methicillin-Resistant Staphylococcus Aureus Pneumonia

Pneumonia that is caused by Staphylococcus aureus and is resistant to methicillin treatment. [ NCI ]

### Methicillin-Susceptible Staphylococcus Aureus Infection

A bacterial infection that is caused by Staphylococcus aureus and can be treated by methicillin class antibiotics.

### Vancomycin-Resistant Staphylococcus Aureus Infection

A bacterial infection that is caused by Staphylococcus aureus and is resistant to vancomycin treatment.

## Suggested parent term

Methicillin-Resistant Staphylococcus Aureus Pneumonia => Methicillin-Resistant Staphylococcus Aureus Infection => Staphylococcus aureus infection (http://www.ebi.ac.uk/efo/EFO_0005681)

Methicillin-Susceptible Staphylococcus Aureus Infection =>  Staphylococcus aureus infection (http://www.ebi.ac.uk/efo/EFO_0005681)

Vancomycin-Resistant Staphylococcus Aureus Infection =>  Staphylococcus aureus infection (http://www.ebi.ac.uk/efo/EFO_0005681)

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
- [ ] Create new term:
EFO:NEW1 Methicillin-Resistant Staphylococcus Aureus Infection
Subclass of Staphylococcus aureus infection (EFO:0005681)
Def: A bacterial infection that is caused by Staphylococcus aureus and is resistant to methicillin treatment. [ NCI ]
X-refs: NCIT:C115248
Synonyms: MRSA infection
Infection, MRSA
infection by MRSA
MRSA
MRSA bacteremia
MRSA bacteremias
Methicillin-resistant Staphylococcus aureus (MRSA) infection
methicillin-resistant Staphylococcus aureus (MSSA) bacteremia

- [ ] Create new term:
EFO:NEW2 Methicillin-Resistant Staphylococcus Aureus Pneumonia
Subclass of Methicillin-Resistant Staphylococcus Aureus Infection (EFO:NEW1)
Subclass of pneumonia (EFO:0003106)
Def: Pneumonia that is caused by Staphylococcus aureus and is resistant to methicillin treatment. [ NCI ]
X-refs: NCIT:C122523
Synonyms: Methicillin-Resistant Staphylococcus Aureus Pneumonia
MRSA Pneumonia
Methicillin-Resistant Staphylococcus aureus Pneumonia

- [ ] Create new term:
EFO:NEW3 Methicillin-Susceptible Staphylococcus Aureus Infection
Subclass of Staphylococcus aureus infection (EFO:0005681)
Def: A bacterial infection that is caused by Staphylococcus aureus and can be treated by methicillin class antibiotics.
Synonyms: MSSA
MSSA infection
MSSA bacteremia
MSSA bacteremias
infection by MSSA
Methicillin-susceptible Staphylococcus aureus (MSSA) infection
methicillin-susceptible S. aureus (MSSA) infection
methicillin-susceptible Staphylococcus aureus (MSSA) bacteremia

- [ ] Create new term:
EFO:NEW4 Vancomycin-Resistant Staphylococcus Aureus Infection
Subclass of Staphylococcus aureus infection (EFO:0005681)
Def: A bacterial infection that is caused by Staphylococcus aureus and is resistant to vancomycin treatment.
Synonyms: VRSA
VRSA infection
VRSA bacteremia
VRSA bacteremias
infection by VRSA
vancomycin-resistant Staphylococcus aureus (VRSA)
Vancomycin-Resistant Staphylococcus aureus (VRSA) infection
Vancomycin-Resistant S. Aureus (VRSA) infection
Vancomycin-Resistant Staphylococcus aureus (VRSA) bacteremia
slow-intermediate vancomycin-resistant S. aureus (sVISA)

**Comment by zoependlington** [comment]
Here are the IDs for the new terms:
EFO:0008555 | Methicillin-Resistant Staphylococcus Aureus Infection
EFO:0008556 | Methicillin-Resistant Staphylococcus Aureus Pneumonia
EFO:0008557 | Methicillin-Susceptible Staphylococcus Aureus Infection
EFO:0008558 | Vancomycin-Resistant Staphylococcus Aureus Infection
