### ISSUE TITLE
Add collection method for 'nasal brush'

### ISSUE THREAD

**Issue by mshadbolt** [EBISPOT/efo#822]
## Preferred term label

nasal brush

## Synonyms

nasal mucosal brushing

## Textual definition

A method for sampling of epithelial cells and other effector cells from the nasal mucosa using a small nylon brush which is rotated over the epithelium and soaked and shaken in a small volume of a balanced salt solution. 

pubmed id: 2457054

https://pubmed.ncbi.nlm.nih.gov/2457054/

## Suggested parent term

[Collecting specimen from organism](http://purl.obolibrary.org/obo/OBI_0600005) or perhaps it could be under [scraping](http://www.ebi.ac.uk/efo/EFO_0009122)?

## Attribution

ORCID iD: 0000-0001-7505-5418

**Comment by paolaroncaglia** [comment]
@mshadbolt 
Thanks for your request. We'll add 'nasal brush/nasal mucosal brushing' under 'collecting specimen from organism' rather than 'scraping', because the latter implies the use of a hard or sharp tool, which a nasal brush isn't. 
We'll aim at creating the term in time for the next EFO release (scheduled mid-August) and will comment here when done and provide you with the new EFO ID.

**Comment by mshadbolt** [comment]
Great, thanks for confirming! :)

**Comment by paolaroncaglia** [comment]
@mshadbolt 
Your requested term has been added as EFO_0010741 'nasal brush'. It will be visible after the next EFO release, scheduled for August 17th. Thanks.

**Comment by paolaroncaglia** [comment]
Note for self:
- [ ] Retrospectively add subset tag "added_for_HCA" to EFO_0010741 'nasal brush'.
