### ISSUE TITLE
single cell isolation terms

### ISSUE THREAD

**Issue by anjaf** [EBISPOT/efo#827]
Dear EFO team, 

The last small issue regarding the new EFO terms (https://github.com/EBISPOT/efo/issues/545), about the "single cell isolation" (OBI:0000512) child terms. 

I discovered that "laser capture microdissection" (http://www.ebi.ac.uk/efo/EFO_0009111) is now only under "single cell isolation”. This already existed somewhere else previously. Was it under "sample enrichment" directly? This is not a single-cell specific method/term, so I suggest to put the term back under "sample enrichment” while keeping it as a child of "single cell isolation" as well. 

Similarly, "fluorescence-activated cell sorting" (http://www.ebi.ac.uk/efo/EFO_0009108) should be under “sample enrichment” and under “single cell isolation.

**Comment by zoependlington** [comment]
Thanks @anjaf, I'll update this in time for our August release.

**Comment by zoependlington** [comment]
@anjaf "laser capture microdissection" is currently a child of both "sample enrichment" and "single cell isolation" in EFO. However, as "single cell isolation" is a child of "sample enrichment", during the reasoning process the redundant secondary "is_a" link to "sample enrichment" is lost. I can make "laser capture microdissection" a child of "sample enrichment" only as it is not a single cell specific term if that is more ideal?

The same problem will occur with "fluorescence-activated cell sorting" where the redundant link will not show in the reasoned ontology.

**Comment by zoependlington** [comment]
@anjaf Just double checking about this ticket. Could you let me know if you would like "laser capture microdissection" to be a child of "sample enrichment" only? See the above comment for more details.

**Comment by anjaf** [comment]
@zoependlington Sorry for not getting back earlier. I think I understand now what you mean. Yes, this is fine then to leave as children of "single cell isolation".

**Comment by paolaroncaglia** [comment]
Hi @anjaf and @zoependlington ,

I reviewed the thread in this ticket. No action item is left, though I'd suggest two minor improvements:
- [ ] Remove the link 'laser capture microdissection' subclass of 'sample enrichment' as it is redundant;
- [ ] Remove the two references to "pathologist" in the definition of 'laser capture microdissection', by removing the bits in italic, as the technique is carried out in biology laboratories too ("... It allows sampling of specific cells under direct microscopic visualization _by a pathologist_. ... The system is integrated into a _pathologist's_ microscope so that the cells are microdissected...".

I will make these changes before the next EFO release unless you have objections. Thanks,
Paola

**Comment by paolaroncaglia** [comment]
FYI @anjaf and @zoependlington ,
All done. 
Paola
