### ISSUE TITLE
UniProtKB Swiss-Prot Release 2020_05 Disease Mappings

### ISSUE THREAD

**Issue by Antonialock** [EBISPOT/efo#829]
Hi Paola,
we have a new set of terms that need mapping. Please see the attached spreadsheet. Not sure if I should do anything wrt to MONDO prior to making a ticket here?
https://docs.google.com/spreadsheets/d/1efvKQf4eovo5p4I1KBK-4UOiTgUvMI4YH0Q5N9sHLBc/edit#gid=0

**Comment by paolaroncaglia** [comment]
Hi @Antonialock ,
I asked Mondo if they have any update on their plans to ingest recent OMIM IDs (see 
https://github.com/monarch-initiative/mondo/issues/1735#issuecomment-669253578). Let's see what they say.
Thanks,
Paola

**Comment by Antonialock** [comment]
Thanks, yes I was notified by the tag.

**Comment by paolaroncaglia** [comment]
Hi @Antonialock ,
I see that the related Mondo ticket https://github.com/monarch-initiative/mondo/issues/1735 is in Nicole's list of "Pending questions", meaning she hasn't had a chance to address it with her colleagues. There will be delays due to everyone's summer vacations, but the bottom line is, Mondo just had a release yesterday and the new OMIM IDs you need aren't in it yet (as far as I know; the new Mondo release isn't in OLS yet). Mondo usually releases once a month. Would UniProt be ok with waiting ~1 month (possibly 5-6 weeks as EFO releases happen after Mondo ones) to have the OMIM IDs in EFO? If so, perhaps at some point you could follow up with Mondo please to see where they are. 
Thanks,
Paola

**Comment by Antonialock** [comment]
It looks like the requests from 04 were just released https://github.com/monarch-initiative/mondo/issues/1735

I'm sure it's fine to wait. I'll double check to be sure,

**Comment by Antonialock** [comment]
Yes it looks like it isn't urgent;  Sandra said "I think so, yes. No-one needs them urgently that I am aware of"

**Comment by Antonialock** [comment]
Is it enough to have the ID's? Nicole has put them in the MONDO column here
https://docs.google.com/spreadsheets/d/1efvKQf4eovo5p4I1KBK-4UOiTgUvMI4YH0Q5N9sHLBc/edit?ts=5f32f8a1#gid=0

**Comment by paolaroncaglia** [comment]
@Antonialock 

> Is it enough to have the ID's? Nicole has put them in the MONDO column here
> https://docs.google.com/spreadsheets/d/1efvKQf4eovo5p4I1KBK-4UOiTgUvMI4YH0Q5N9sHLBc/edit?ts=5f32f8a1#gid=0

Yes, I will 
- [ ] Import Mondo terms from column F above. When done,
- [ ] All mappings in column D may be changed to "exact".

**Comment by paolaroncaglia** [comment]
@Antonialock 
This is all done and will be visible in the next EFO release (planned for August 17th). Thank you.

**Comment by Antonialock** [comment]
thanks!
