### ISSUE TITLE
Ontology mappings for EVA

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#83]
Gary Saunders (EVA) wrote: 

"We have around 150 terms that are used in >10 ClinVar records for which our automated pipeline which uses Zooma and OxO cannot find a mapping. (The potential mappings at distance of 2 from OxO have been manually checked.)
We do not expect to find mappings for all of these terms in EFO (e.g. "see cases")."

All available info is in this spreadsheet: https://docs.google.com/spreadsheets/d/1ba-905ZeOtxLE9I7Fld5UPWYzbwAAbpHof7jikeC7lg/edit?ts=5a8ac102#gid=627612479

Note: the final_mappings tab contains the latest new mappings (NOT all the data EVA have mapped). These are added to the trustworthy automated mappings they find from Zooma and Oxo. In total there are about 5500 mappings from ClinVar to EFO.

We should go through the spreadsheet and see what we can map to externally and import into EFO. Once the terms are mapped to something, we’ll give the mappings back to EVA, so they can add them to their Zooma datasource file. (Gary is leaving EBI at end of Feb, so Cristina Yenyxe Gonzalez Garcia will be the main contact.)

**Comment by zoependlington** [comment]
Checked the mappings of the >10_no_mappings tab with Zooma. Some mappings found:
[https://docs.google.com/spreadsheets/d/1Nfa68cMv1nFWWwKRGO3poN5h39ITHUzrEzjzHa63ATs/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1Nfa68cMv1nFWWwKRGO3poN5h39ITHUzrEzjzHa63ATs/edit?usp=sharing)

**Comment by simonjupp** [comment]
AI - Set up meeting with EVA to review

**Comment by zoependlington** [comment]
Thanks for the up-to-date mappings, @hannah-mclaren!

I have compared the "final_mappings" tab against EFO and removed the terms that currently exist in EFO after a quick search and I started to potentially map them to a parent term that already exists in EFO according to an OLS search:
https://docs.google.com/spreadsheets/d/12CTxX_olAIS-B7rhuo_6WMNm9-ehOSzbrFQ5G-zc_tw/edit?usp=sharing

There are two terms (highlighted in green) neoplasm of the breast (http://purl.obolibrary.org/obo/HP_0100013) and cleft palate (http://www.orpha.net/ORDO/Orphanet_2014) that have existing terminology in EFO: breast neoplasm (In EFO as EFO_0003869) and cleft palate (In EFO as HP_0000175) - the HP and Orphanet X-refs could be added to these.

**Comment by hannah-mclaren** [comment]
We now have some webulous templates ready for submission in here:
https://drive.google.com/drive/folders/1VI7ZWY1ByyAyTtfD0BTPpgMMwW8rAqY_?usp=sharing

Thanks to @zoependlington for all her help with this!

Tried submitting the HP import but it fails:
[Failed to validate pattern: add definition editor: Unrecognised token definition_editor at line 4 char position in line 16]
Please advise on this. 

I still have a couple of questions relating to Zoe's final_mappings:

- Which template can we use for importing Orphanet terms? Add EFO disease?
- Do we want to add GO terms to EFO such as drug response and again which template can I use?
- What do the experts think about classifying "developmental delay" as a disease, disorder or phenotype? I cant decide where best to put this one.
- We think "charcot-marie-tooth disease, type 2a2a" and Orphanet_99947 are synonyms so Ive put this one under parent Orphanet_64746 but not sure if this is right. Zoe notes this could be a child of Orphanet_99947 instead so perhaps expert opinion is needed.

I have also created a rolling sheet in the same directory of any remaining unmapped terms so that we can keep track of what is not being imported after each OT submission. At the moment there are 8 but this may reduce pending the above answers.

**Outstanding requests**

- Please can we add the HP and ORDO x-refs below to the existing EFO terms:

HP_0100013 | Neoplasm of the breast | https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0003869 | breast neoplasm

Orphanet_2014 | Cleft palate | https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0000175 | cleft palate

- Can we also add the label "digitorenocerebral syndrome" as a synonym for the existing EFO term:
https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_79500

(Not sure if this is allowed since the class is now obsolete. See https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_1674)

**Comment by zoependlington** [comment]
Thanks @hannah-mclaren!

A quick response to a question I have right now:

> We think "charcot-marie-tooth disease, type 2a2a" and Orphanet_99947 are synonyms so Ive put this one under parent Orphanet_64746 but not sure if this is right. Zoe notes this could be a child of Orphanet_99947 instead so perhaps expert opinion is needed.

- I agree with "charcot-marie-tooth disease, type 2a2a" being a synonym of Orphanet_99947 instead of a child after doing a little more reading and seeing the synonyms listed here: https://www.omim.org/entry/609260. Therefore, I agree with the classification you have suggested.  In this case, we could add a synonym of "charcot-marie-tooth disease, type 2a2a" to the existing term (Orphanet_99947) - which I've added to the below list.

## To Do:

- [ ] Review Webulous for HP import
     - Submission fails due to definition_editor error
- [ ] Review Webulous for Add EFO Disease
- [ ] Review Webulous for Add EFO Phenotype
- [ ] **EFO:EDIT** breast neoplasm (EFO:0003869)
     - **X-refs:** HP:0100013
     - **Synonyms:** neoplasm of the breast
- [ ] **EFO:EDIT** cleft palate (HP:0000175)
     - **X-refs:** Orphanet:2014
- [ ] **EFO:EDIT** Autosomal dominant Charcot-Marie-Tooth disease type 2A2 (Orphanet_99947)
     - **Synonyms:** charcot-marie-tooth disease, type 2a2a
- [ ] **EFO:EDIT** DOORS syndrome (Orphanet_79500)
     - **Synonyms:** digitorenocerebral syndrome

**Comment by zoependlington** [comment]
@hannah-mclaren another answer for you:
The Orphanet terms will need to be added as new terms in EFO, so they can be added through the Add EFO Disease Webulous template with an Orphanet X-ref (ORDO:def_cite).

**Comment by hannah-mclaren** [comment]
Added a new Webulous template to the shared folder for review of Orphanet terms:
https://docs.google.com/spreadsheets/d/1oxuY4tWZey3AvfJNxb0vT2IkPq9Ozs22vP3K0LbMTuk/edit?usp=sharing
