### ISSUE TITLE
Hemorrhagic Fever

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#854]
For new term requests, please provide the following information:

## Preferred term label

hemorrhagic fever

## Synonyms

viral hemorrhagic fever
viral haemorrhagic fever
haemorrhagic fever
Haemorrhagic Fevers, Viral
Hemorrhagic Fevers
VHF
VHFs

## Textual definition

Please see https://medlineplus.gov/hemorrhagicfevers.html

## Suggested parent term

Defined as a sign or symptom. Parent term could be 'Fever' but this is too broad.
The classification based on the definition above is much better and aligned with WHO.
MeSH would define the following term
https://meshb.nlm.nih.gov/record/ui?ui=D006482
that will encompass RNA virus infections.
Note that EFO contains multiple virus infection terms with related hemmorrhagic fever symptoms. Therefore, you may consider reclassifying those in line with official classification.

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by paolaroncaglia** [comment]
Hi @gkos-bio ,

- [ ] I will import MONDO:0018087 'viral hemorrhagic fever', defined very similarly to the MedlinePlus entry you suggested ("Viral hemorrhagic fever is a group of recently discovered contagious viral infections characterized by severe, multiple, and often fatal hemorrhages. African fevers include Lassa fever discovered in 1969, Marburg's disease that first occurred in 1967, and Ebola fever that appeared in 1976. Other viruses may also cause hemorrhagic fevers (for example, arbovirus fever)."). The Mondo term cross-references the same MeSH entry you listed. As for the synonyms, the Mondo term has none, so I can 
- [ ] Ask Mondo to add the following synonyms to MONDO:0018087 'viral hemorrhagic fever':
hemorrhagic fever [narrow or related]
haemorrhagic fever [narrow or related]
viral haemorrhagic fever [exact]
Haemorrhagic Fevers, Viral [exact]
Hemorrhagic Fevers [narrow or related]
VHF [acronym if feasible; otherwise narrow or related]
VHFs [acronym if feasible; otherwise narrow or related]

Let me know if you have any objection. 
- [ ] I will also look into your note "Note that EFO contains multiple virus infection terms with related hemmorrhagic fever symptoms. Therefore, you may consider reclassifying those in line with official classification."

**Comment by paolaroncaglia** [comment]
@gkos-bio 
Correction, MONDO:0018087 'viral hemorrhagic fever' is already in EFO. I'll ask Mondo to add the synonyms above.

**Comment by paolaroncaglia** [comment]
@gkos-bio 
I looked into other 'hemorrhagic fever' terms in EFO. Their placement seems mostly correct. There are 2 that may require further action:
- [ ] EFO:0004227 Dengue Hemorrhagic Fever (mapping to MONDO:0005358)
We could ask Mondo to assert 'viral hemorrhagic fever' as a superclass, based on the gloss in their def of the latter ("...Other viruses may also cause hemorrhagic fevers (for example, arbovirus fever)")
- [ ] EFO:0007299 hemorrhagic fever with renal syndrome ("A viral infectious disease that is a hemorrhagic fever, located_in kidney, has_material_basis_in Hantaan virus, has_material_basis_in Dobrava-Belgrade virus, has_material_basis_in Seoul virus, or has_material_basis_in Puumala virus, which are carried and transmitted_by rodents. The infection has_symptom headache, has_symptom fever, has_symptom muscle pains, has_symptom facial flush, has_symptom petechiae, has_symptom hemorrhagic features, has_symptom proteinuria, and has_symptom renal failure.")
Are these viruses covered by the def of 'viral hemorrhagic fever'? If yes, I can assert the parentage.
Thanks.

**Comment by gkos-bio** [comment]
@paolaroncaglia 
It looks fine to me. 
Regarding the existence of this 'hemorrhagic fever' term in EFO,  I think I was tricked by the 'ae' in 'haemorrhagic' so having synonyms would definitively help. I'll double-check next time before asking for a new term though (same for 'aenemia', etc.)

**Comment by paolaroncaglia** [comment]
@gkos-bio 
All tasks above are now done. EFO edits will be visible after tomorrow's EFO release, while edits requested to Mondo, if approved, will be visible after their next release (usually around start of each month) and then ingested by EFO after a couple of weeks. Thanks.
