### ISSUE TITLE
[NTR] SDS-PAGE 

### ISSUE THREAD

**Issue by mshadbolt** [EBISPOT/efo#905]
For new term requests, please provide the following information:

## Preferred term label

SDS-PAGE

## Synonyms

SDS Polyacrylamide Gel Electrophoresis, sodium dodecyl sulphate–polyacrylamide gel electrophoresis, SDS Polyacrylamide Gel Electrophoresis of Proteins, SDS-PAGE electrophoresis

## Textual definition

SDS-PAGE is an electrophoresis method that allows protein separation by mass in a polyacrylamide-based discontinuous gel.

https://en.wikipedia.org/wiki/SDS-PAGE
https://pubmed.ncbi.nlm.nih.gov/20512673/
PMID: 20512673 
DOI: 10.1385/0-89603-062-8:41

exists in PRIDE ontology here: https://www.ebi.ac.uk/ols/ontologies/pride/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPRIDE_0000568

## Suggested parent term

There don't appear to be any terms related to gel electrophoresis currently, so not really sure. Perhaps underneath 'assay'

There is a 'gel' term and 'PAGE' term in BAO, I would then put SDS-PAGE, under the existing PAGE term if you are going to import the hierarchy

https://www.ebi.ac.uk/ols/ontologies/bao/terms?iri=http%3A%2F%2Fwww.bioassayontology.org%2Fbao%23BAO_0010018&viewMode=All&siblings=false

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

@paolaroncaglia @zoependlington

**Comment by paolaroncaglia** [comment]
Hi @mshadbolt ,
I’ll add as follows:

EFO:NEW SDS-PAGE
subclass of ‘protein assay’
“A protein assay that allows protein separation by mass in a polyacrylamide-based discontinuous gel.”
Wikipedia:SDS-PAGE
PMID:20512673
PRIDE:0000568
CHMO:0001027
https://orcid.org/0000-0001-7505-5418

Synonyms: 
SDS polyacrylamide gel electrophoresis
sodium dodecyl sulphate–polyacrylamide gel electrophoresis
SDS polyacrylamide gel electrophoresis of proteins
SDS-PAGE electrophoresis

Thanks,
Paola

**Comment by paolaroncaglia** [comment]
@mshadbolt 
The term you requested is now in EFO as EFO:0010936 SDS-PAGE.
It will be visible in the EFO release scheduled for tomorrow, and will be included in the HCAO release scheduled for Jan 21st.
(We last released HCAO on Dec 3rd, and we won't do another release in December due to the holidays, but going forward we plan to do regular monthly HCAO releases around the 18th-21st of each month, see point 6) in the minutes of the [Dec 9th meeting](https://docs.google.com/document/d/1PXLco-VtpRIFA1DuDDafxqQl2PSW2ZZMG82qA_-1xIE/edit#)).

**Comment by mshadbolt** [comment]
Thank you!
