### ISSUE TITLE
EFO_0001059 & HP_0011142 - merging cataract ontologies

### ISSUE THREAD

**Issue by fauman** [EBISPOT/efo#972]
Could HP_0011142 (Age-related nuclear cataract) be made a child term of EFO_0001059 (cataracts)?

ORCID: 0000-0002-9739-0249

**Comment by paolaroncaglia** [comment]
Hi @fauman ,

EFO_0001059 (cataracts) is in the disease branch, while HP_0011142 (Age-related nuclear cataract) is - as expected - in the phenotype branch. I agree that the line between the two is blurred (pardon the pun). We come across this issue often. The ambiguity should be addressed at source in HPO, also because EFO imports HP terms dynamically (so even if we moved the HP term to sit in the EFO disease branch, we'd keep inheriting the phenotype parent from HP unless we forced the HP term - something we can do, but not ideal in terms of sustainability). You might want to open a ticket in the HP and/or Mondo tracker and ask if these two terms are equivalent:  
 
HP_0011142 (Age-related nuclear cataract) 
A type of cataract (opacification of the lens) that forms during the course of aging. [ http://www.ncbi.nlm.nih.gov/pubmed/15708105 HPO:probinson ]  

MONDO:0004847 (senile cataract)
A cataract with no obvious cause occurring in persons over 50 years old. [ https://medical-dictionary.thefreedictionary.com/senile+cataract ] 

Or you may use the Mondo term. Let us know if you'd like us to import it in EFO.

Thanks,
Paola

**Comment by fauman** [comment]
Thanks @paolaroncaglia for that detailed answer.

My use case is primarily around the gwas catalog. I have been using the EFO annotations there to help guide gene-disease associations.
Previously we had a bunch of associations tagged with EFO_0001059 (cataract).
A new study was just published with associations tagged with HP_0011142.

It's clear these traits share biological features, but this is not reflected in the ontology.

My preference would be for the gwas trait to be tagged with a child term of EFO_0001059.
The most obvious approach to me was to move HP_0011142 under EFO_0001059, but I guess an alternative would be to simply create a new EFO_ID for "Age-related nuclear cataract".

Does this make sense?

**Comment by paolaroncaglia** [comment]
Thanks @fauman for your reply. 

If you wanted the GWAS trait to be annotated with a disease term that is a child of EFO_0001059, yes one option would be to create a new EFO class for "Age-related nuclear cataract", but a more sustainable option would be to import a disease ontology term if a fitting one already exist. If you believe that this one is appropriate
MONDO:0004847 (senile cataract)
A cataract with no obvious cause occurring in persons over 50 years old. [ https://medical-dictionary.thefreedictionary.com/senile+cataract ]
we can import it more quickly and easily than we'd create a new EFO class. Otherwise, we'll do the latter.
Either way, please note that the monthly EFO release just went ahead earlier today, so the solution above would be implemented in time for the next release (March 15th).

Thanks,
Paola

**Comment by paolaroncaglia** [comment]
P.S. Yes the disease and phenotype terms related to cataract should be connected, that would be for Mondo to do, you could ask them to please add an axiom 
MONDO:0005129 'cataract (disease)' disease has feature HP:0000518 'Cataract'
The Mondo tracker is https://github.com/monarch-initiative/mondo/issues.

**Comment by paolaroncaglia** [comment]
@fauman 
Apologies, I missed the detail about "nuclear" cataract. The Mondo term MONDO:0001847 'nuclear senile cataract' seems fitting for 'Age-related nuclear cataract'. If you confirm, we can import that (and, possibly, ask Mondo to add a synonym?).

**Comment by fauman** [comment]
@paolaroncaglia - Just so it's clear, I'm just a GWAS Catalog consumer. I don't actually know the process for curating the new GWAS catalog entries with EFO terms.
For this specific case, seems like we need input from the study authors as well as the gwas catalog curators (and maybe MONDO folks).

**Comment by paolaroncaglia** [comment]
@fauman 
Thank you. My colleague @zoependlington will look at this ticket then, as she's the EFO contact for GWAS issues. 
Best wishes,
Paola

**Comment by aoifemcm** [comment]
Hi @paolaroncaglia @fauman @zoependlington ,
I've reviewed as a GWAS curator, this all seems fine.  

To recap the issue - age-related nuclear cataract (HP_0011142) is in phenotype branch, while broad cataract term (EFO_0001059) is in disease branch.

Proposed solution - import ‘senile cataract’ from Mondo MONDO_0004847, as child of EFO_0001059 in disease branch.
Note there are studies mapped to both HP_0011142 (age-related cataract) and HP_0011141 (age-related nuclear cataract), so both MONDO_0004847 (senile cataract) and MONDO_0001847 (nuclear senile cataract) should be imported.  I agree that ‘age-related’ should be added as a synonym.

After they are imported we can re-map the GWAS studies to the mondo terms.  I’ve done a quick check on the publications and the new terms are suitable.

Here are the studies that will need re-mapping:
PMID 25352737 (2014) -GCST002619, GCST002618
PMID 24951543 (2014) -GCST002498
PMID 33311586 (2020) -GCST90013423

Best,
Aoife

**Comment by zoependlington** [comment]
I have imported both Mondo terms into EFO, which will be available at our next release (15th March). Any new synonyms desired to Mondo terms however will need to be requested on the [Mondo ticket tracker](https://github.com/monarch-initiative/mondo/issues/).
