### ISSUE TITLE
Add atlas subset annotations into EFO

### ISSUE THREAD

**Issue by simonjupp** [EBISPOT/efo#99]
Gene expression atlas need a slim of cell types and anatomy terms. They are providing the terms here https://github.com/gxa/atlas-metadata/tree/master/curated. We need an automated process the annotate EFO with atlas slim terms.

**Comment by zoependlington** [comment]
Some terms after adding the atlas slim annotations were discovered to either not be in EFO or already exist in EFO under another label or URI. These terms and the templates used to generate owl files in ROBOT can be found here:
https://docs.google.com/spreadsheets/d/1e34LxE1PjM_XjHJYsuAqYzWr1-PKtCLqAzL6jkwXj-0/edit?usp=sharing

I have removed these terms from the templates used to create the slims for now in order to test the addition of the slim annotation.

**Comment by zoependlington** [comment]
The makefile has been edited to create the atlas slims (atlas_organ, atlas_anatomy atlas_cell) on the terms currently in EFO (those highlighted in the above comment's Google sheet as not being in EFO or being under a different URI have not been annotated). 

This can be viewed on the atlas_slim branch (https://github.com/EBISPOT/efo/tree/atlas-slim).

**Comment by simonjupp** [comment]
Zoe to create pull request for review by Simon

**Comment by S2Ola** [comment]
The curated files have been cleaned and input into templates to be driven by SPARQL. The makefile runs successfully with EFO2. Further documentation and improvement is still on-going for scripts to automate the process further for different levels of requests.
